/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/base.proto */

#pragma once

#include <cstdint>
#include <string>
#include <optional>
#include <turbo/utility/status.h>

#include <turbo/container/flat_hash_map.h>

#include <xtoml/toml.h>
#include <turbo/container/flat_hash_map.h>



namespace my::base {

    class Base;



    /// --- enums ---


    /// --- messages --- 


    //////////////////////////////////////////////////////////////////////
    /// Base 
    class  Base {
    public:

    ///  runtime identify for traits
    static constexpr bool is_runtime_type = true;


    public:
        /// -----enums-------- 
    public:
        ///////////////////////////////////////////////////////////////////////// 
        /// transfers 
        turbo::Status parse_toml_str(const std::string& path);

        turbo::Status parse_toml_file(const std::string& str);

        void add_checker(std::unique_ptr<xtoml::BasicHandler> handler);

        const xtoml::HandlerMap &checkers() const;

        turbo::Status parse_toml(const xtoml::Value& v, const xtoml::TomlUri &prefix, const xtoml::HandlerMap &map);

        xtoml::Value serialize_toml() const;

        turbo::Result<std::string> serialize_to_string() const;


    //////////////////////////////////////////////////////////////////////
    /// members
    /// Keep members protected for inheritance and extension
    public:
        std::string name{"default_name"};
        int32_t age{0};
        bool enabled{1};

        //////////////////////////////////////////////////////////////////////
        /// global checkers

        xtoml::TomlUri    _uri_prefix;
        xtoml::HandlerMap _handler_map;
    };


    ///////////////////////////////////////////////////////////

}  // my::base


