/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/config.proto */

/* Do not generate deprecated warnings for self */

#include <tests/config.sk.h>
#include <google/protobuf/json/json.h>



namespace granite {
  std::optional<JsonStorageFormat> parse_JsonStorageFormat(std::string_view value) {
    static turbo::flat_hash_map<std::string, JsonStorageFormat> enum_map = {
      {"JSON_DEFAULT", static_cast<JsonStorageFormat>(0)},
      {"JSON", static_cast<JsonStorageFormat>(1)},
      {"CBOR", static_cast<JsonStorageFormat>(2)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  std::optional<BlockCacheType> parse_BlockCacheType(std::string_view value) {
    static turbo::flat_hash_map<std::string, BlockCacheType> enum_map = {
      {"LRU", static_cast<BlockCacheType>(0)},
      {"CLOCK", static_cast<BlockCacheType>(1)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  std::optional<CompressionType> parse_CompressionType(std::string_view value) {
    static turbo::flat_hash_map<std::string, CompressionType> enum_map = {
      {"K_NO_COMPRESSION", static_cast<CompressionType>(0)},
      {"K_SNAPPY_COMPRESSION", static_cast<CompressionType>(1)},
      {"K_ZLIB_COMPRESSION", static_cast<CompressionType>(2)},
      {"K_BZIP2_COMPRESSION", static_cast<CompressionType>(3)},
      {"K_LZ4_COMPRESSION", static_cast<CompressionType>(4)},
      {"K_LZ4HC_COMPRESSION", static_cast<CompressionType>(5)},
      {"K_XPRESS_COMPRESSION", static_cast<CompressionType>(6)},
      {"K_ZSTD", static_cast<CompressionType>(7)},
      {"K_LAST_BUILTIN_COMPRESSION", static_cast<CompressionType>(7)},
      {"K_CUSTOM_COMPRESSION_80", static_cast<CompressionType>(128)},
      {"K_FIRST_CUSTOM_COMPRESSION", static_cast<CompressionType>(128)},
      {"K_CUSTOM_COMPRESSION_81", static_cast<CompressionType>(129)},
      {"K_CUSTOM_COMPRESSION_82", static_cast<CompressionType>(130)},
      {"K_CUSTOM_COMPRESSION_83", static_cast<CompressionType>(131)},
      {"K_CUSTOM_COMPRESSION_84", static_cast<CompressionType>(132)},
      {"K_CUSTOM_COMPRESSION_85", static_cast<CompressionType>(133)},
      {"K_CUSTOM_COMPRESSION_86", static_cast<CompressionType>(134)},
      {"K_CUSTOM_COMPRESSION_87", static_cast<CompressionType>(135)},
      {"K_CUSTOM_COMPRESSION_88", static_cast<CompressionType>(136)},
      {"K_CUSTOM_COMPRESSION_89", static_cast<CompressionType>(137)},
      {"K_CUSTOM_COMPRESSION_8A", static_cast<CompressionType>(138)},
      {"K_CUSTOM_COMPRESSION_8B", static_cast<CompressionType>(139)},
      {"K_CUSTOM_COMPRESSION_8C", static_cast<CompressionType>(140)},
      {"K_CUSTOM_COMPRESSION_8D", static_cast<CompressionType>(141)},
      {"K_CUSTOM_COMPRESSION_8E", static_cast<CompressionType>(142)},
      {"K_CUSTOM_COMPRESSION_8F", static_cast<CompressionType>(143)},
      {"K_CUSTOM_COMPRESSION_90", static_cast<CompressionType>(144)},
      {"K_CUSTOM_COMPRESSION_91", static_cast<CompressionType>(145)},
      {"K_CUSTOM_COMPRESSION_92", static_cast<CompressionType>(146)},
      {"K_CUSTOM_COMPRESSION_93", static_cast<CompressionType>(147)},
      {"K_CUSTOM_COMPRESSION_94", static_cast<CompressionType>(148)},
      {"K_CUSTOM_COMPRESSION_95", static_cast<CompressionType>(149)},
      {"K_CUSTOM_COMPRESSION_96", static_cast<CompressionType>(150)},
      {"K_CUSTOM_COMPRESSION_97", static_cast<CompressionType>(151)},
      {"K_CUSTOM_COMPRESSION_98", static_cast<CompressionType>(152)},
      {"K_CUSTOM_COMPRESSION_99", static_cast<CompressionType>(153)},
      {"K_CUSTOM_COMPRESSION_9A", static_cast<CompressionType>(154)},
      {"K_CUSTOM_COMPRESSION_9B", static_cast<CompressionType>(155)},
      {"K_CUSTOM_COMPRESSION_9C", static_cast<CompressionType>(156)},
      {"K_CUSTOM_COMPRESSION_9D", static_cast<CompressionType>(157)},
      {"K_CUSTOM_COMPRESSION_9E", static_cast<CompressionType>(158)},
      {"K_CUSTOM_COMPRESSION_9F", static_cast<CompressionType>(159)},
      {"K_CUSTOM_COMPRESSION_A0", static_cast<CompressionType>(160)},
      {"K_CUSTOM_COMPRESSION_A1", static_cast<CompressionType>(161)},
      {"K_CUSTOM_COMPRESSION_A2", static_cast<CompressionType>(162)},
      {"K_CUSTOM_COMPRESSION_A3", static_cast<CompressionType>(163)},
      {"K_CUSTOM_COMPRESSION_A4", static_cast<CompressionType>(164)},
      {"K_CUSTOM_COMPRESSION_A5", static_cast<CompressionType>(165)},
      {"K_CUSTOM_COMPRESSION_A6", static_cast<CompressionType>(166)},
      {"K_CUSTOM_COMPRESSION_A7", static_cast<CompressionType>(167)},
      {"K_CUSTOM_COMPRESSION_A8", static_cast<CompressionType>(168)},
      {"K_CUSTOM_COMPRESSION_A9", static_cast<CompressionType>(169)},
      {"K_CUSTOM_COMPRESSION_AA", static_cast<CompressionType>(170)},
      {"K_CUSTOM_COMPRESSION_AB", static_cast<CompressionType>(171)},
      {"K_CUSTOM_COMPRESSION_AC", static_cast<CompressionType>(172)},
      {"K_CUSTOM_COMPRESSION_AD", static_cast<CompressionType>(173)},
      {"K_CUSTOM_COMPRESSION_AE", static_cast<CompressionType>(174)},
      {"K_CUSTOM_COMPRESSION_AF", static_cast<CompressionType>(175)},
      {"K_CUSTOM_COMPRESSION_B0", static_cast<CompressionType>(176)},
      {"K_CUSTOM_COMPRESSION_B1", static_cast<CompressionType>(177)},
      {"K_CUSTOM_COMPRESSION_B2", static_cast<CompressionType>(178)},
      {"K_CUSTOM_COMPRESSION_B3", static_cast<CompressionType>(179)},
      {"K_CUSTOM_COMPRESSION_B4", static_cast<CompressionType>(180)},
      {"K_CUSTOM_COMPRESSION_B5", static_cast<CompressionType>(181)},
      {"K_CUSTOM_COMPRESSION_B6", static_cast<CompressionType>(182)},
      {"K_CUSTOM_COMPRESSION_B7", static_cast<CompressionType>(183)},
      {"K_CUSTOM_COMPRESSION_B8", static_cast<CompressionType>(184)},
      {"K_CUSTOM_COMPRESSION_B9", static_cast<CompressionType>(185)},
      {"K_CUSTOM_COMPRESSION_BA", static_cast<CompressionType>(186)},
      {"K_CUSTOM_COMPRESSION_BB", static_cast<CompressionType>(187)},
      {"K_CUSTOM_COMPRESSION_BC", static_cast<CompressionType>(188)},
      {"K_CUSTOM_COMPRESSION_BD", static_cast<CompressionType>(189)},
      {"K_CUSTOM_COMPRESSION_BE", static_cast<CompressionType>(190)},
      {"K_CUSTOM_COMPRESSION_BF", static_cast<CompressionType>(191)},
      {"K_CUSTOM_COMPRESSION_C0", static_cast<CompressionType>(192)},
      {"K_CUSTOM_COMPRESSION_C1", static_cast<CompressionType>(193)},
      {"K_CUSTOM_COMPRESSION_C2", static_cast<CompressionType>(194)},
      {"K_CUSTOM_COMPRESSION_C3", static_cast<CompressionType>(195)},
      {"K_CUSTOM_COMPRESSION_C4", static_cast<CompressionType>(196)},
      {"K_CUSTOM_COMPRESSION_C5", static_cast<CompressionType>(197)},
      {"K_CUSTOM_COMPRESSION_C6", static_cast<CompressionType>(198)},
      {"K_CUSTOM_COMPRESSION_C7", static_cast<CompressionType>(199)},
      {"K_CUSTOM_COMPRESSION_C8", static_cast<CompressionType>(200)},
      {"K_CUSTOM_COMPRESSION_C9", static_cast<CompressionType>(201)},
      {"K_CUSTOM_COMPRESSION_CA", static_cast<CompressionType>(202)},
      {"K_CUSTOM_COMPRESSION_CB", static_cast<CompressionType>(203)},
      {"K_CUSTOM_COMPRESSION_CC", static_cast<CompressionType>(204)},
      {"K_CUSTOM_COMPRESSION_CD", static_cast<CompressionType>(205)},
      {"K_CUSTOM_COMPRESSION_CE", static_cast<CompressionType>(206)},
      {"K_CUSTOM_COMPRESSION_CF", static_cast<CompressionType>(207)},
      {"K_CUSTOM_COMPRESSION_D0", static_cast<CompressionType>(208)},
      {"K_CUSTOM_COMPRESSION_D1", static_cast<CompressionType>(209)},
      {"K_CUSTOM_COMPRESSION_D2", static_cast<CompressionType>(210)},
      {"K_CUSTOM_COMPRESSION_D3", static_cast<CompressionType>(211)},
      {"K_CUSTOM_COMPRESSION_D4", static_cast<CompressionType>(212)},
      {"K_CUSTOM_COMPRESSION_D5", static_cast<CompressionType>(213)},
      {"K_CUSTOM_COMPRESSION_D6", static_cast<CompressionType>(214)},
      {"K_CUSTOM_COMPRESSION_D7", static_cast<CompressionType>(215)},
      {"K_CUSTOM_COMPRESSION_D8", static_cast<CompressionType>(216)},
      {"K_CUSTOM_COMPRESSION_D9", static_cast<CompressionType>(217)},
      {"K_CUSTOM_COMPRESSION_DA", static_cast<CompressionType>(218)},
      {"K_CUSTOM_COMPRESSION_DB", static_cast<CompressionType>(219)},
      {"K_CUSTOM_COMPRESSION_DC", static_cast<CompressionType>(220)},
      {"K_CUSTOM_COMPRESSION_DD", static_cast<CompressionType>(221)},
      {"K_CUSTOM_COMPRESSION_DE", static_cast<CompressionType>(222)},
      {"K_CUSTOM_COMPRESSION_DF", static_cast<CompressionType>(223)},
      {"K_CUSTOM_COMPRESSION_E0", static_cast<CompressionType>(224)},
      {"K_CUSTOM_COMPRESSION_E1", static_cast<CompressionType>(225)},
      {"K_CUSTOM_COMPRESSION_E2", static_cast<CompressionType>(226)},
      {"K_CUSTOM_COMPRESSION_E3", static_cast<CompressionType>(227)},
      {"K_CUSTOM_COMPRESSION_E4", static_cast<CompressionType>(228)},
      {"K_CUSTOM_COMPRESSION_E5", static_cast<CompressionType>(229)},
      {"K_CUSTOM_COMPRESSION_E6", static_cast<CompressionType>(230)},
      {"K_CUSTOM_COMPRESSION_E7", static_cast<CompressionType>(231)},
      {"K_CUSTOM_COMPRESSION_E8", static_cast<CompressionType>(232)},
      {"K_CUSTOM_COMPRESSION_E9", static_cast<CompressionType>(233)},
      {"K_CUSTOM_COMPRESSION_EA", static_cast<CompressionType>(234)},
      {"K_CUSTOM_COMPRESSION_EB", static_cast<CompressionType>(235)},
      {"K_CUSTOM_COMPRESSION_EC", static_cast<CompressionType>(236)},
      {"K_CUSTOM_COMPRESSION_ED", static_cast<CompressionType>(237)},
      {"K_CUSTOM_COMPRESSION_EE", static_cast<CompressionType>(238)},
      {"K_CUSTOM_COMPRESSION_EF", static_cast<CompressionType>(239)},
      {"K_CUSTOM_COMPRESSION_F0", static_cast<CompressionType>(240)},
      {"K_CUSTOM_COMPRESSION_F1", static_cast<CompressionType>(241)},
      {"K_CUSTOM_COMPRESSION_F2", static_cast<CompressionType>(242)},
      {"K_CUSTOM_COMPRESSION_F3", static_cast<CompressionType>(243)},
      {"K_CUSTOM_COMPRESSION_F4", static_cast<CompressionType>(244)},
      {"K_CUSTOM_COMPRESSION_F5", static_cast<CompressionType>(245)},
      {"K_CUSTOM_COMPRESSION_F6", static_cast<CompressionType>(246)},
      {"K_CUSTOM_COMPRESSION_F7", static_cast<CompressionType>(247)},
      {"K_CUSTOM_COMPRESSION_F8", static_cast<CompressionType>(248)},
      {"K_CUSTOM_COMPRESSION_F9", static_cast<CompressionType>(249)},
      {"K_CUSTOM_COMPRESSION_FA", static_cast<CompressionType>(250)},
      {"K_CUSTOM_COMPRESSION_FB", static_cast<CompressionType>(251)},
      {"K_CUSTOM_COMPRESSION_FC", static_cast<CompressionType>(252)},
      {"K_CUSTOM_COMPRESSION_FD", static_cast<CompressionType>(253)},
      {"K_CUSTOM_COMPRESSION_FE", static_cast<CompressionType>(254)},
      {"K_LAST_CUSTOM_COMPRESSION", static_cast<CompressionType>(254)},
      {"K_DISABLE_COMPRESSION_OPTION", static_cast<CompressionType>(255)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* ReadOptions::get_descriptor() {
    return granite::pb::ReadOptions::descriptor();
  }

  ReadOptions::ReadOptions() {
  }

  ReadOptions::~ReadOptions() {
  }

  ReadOptions::ReadOptions(const ReadOptions& rhs) {
    _async_io = rhs._async_io;
  }

  ReadOptions& ReadOptions::operator= (const ReadOptions& rhs) {
    _async_io = rhs._async_io;
    return *this;
  }

  ReadOptions::ReadOptions(ReadOptions&& rhs) noexcept {
    _async_io = rhs._async_io;
  }

  ReadOptions& ReadOptions::operator= (ReadOptions&& rhs) noexcept {
    _async_io = rhs._async_io;
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void ReadOptions::parse_from_proto(const granite::pb::ReadOptions& pb) {
    _async_io = pb.async_io();
  }

  void ReadOptions::serialize_to_proto(granite::pb::ReadOptions& pb) const {
    pb.set_async_io(_async_io);
  }

  turbo::Status ReadOptions::parse_from_json(const std::string& json) {
    granite::pb::ReadOptions pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status ReadOptions::serialize_to_json(std::string& json) const {
    granite::pb::ReadOptions pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string ReadOptions::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* WriteOptions::get_descriptor() {
    return granite::pb::WriteOptions::descriptor();
  }

  WriteOptions::WriteOptions() {
  }

  WriteOptions::~WriteOptions() {
  }

  WriteOptions::WriteOptions(const WriteOptions& rhs) {
    _sync = rhs._sync;
    _disable_wal = rhs._disable_wal;
    _no_slowdown = rhs._no_slowdown;
    _low_pri = rhs._low_pri;
    _memtable_insert_hint_per_batch = rhs._memtable_insert_hint_per_batch;
    _write_batch_max_bytes = rhs._write_batch_max_bytes;
  }

  WriteOptions& WriteOptions::operator= (const WriteOptions& rhs) {
    _sync = rhs._sync;
    _disable_wal = rhs._disable_wal;
    _no_slowdown = rhs._no_slowdown;
    _low_pri = rhs._low_pri;
    _memtable_insert_hint_per_batch = rhs._memtable_insert_hint_per_batch;
    _write_batch_max_bytes = rhs._write_batch_max_bytes;
    return *this;
  }

  WriteOptions::WriteOptions(WriteOptions&& rhs) noexcept {
    _sync = rhs._sync;
    _disable_wal = rhs._disable_wal;
    _no_slowdown = rhs._no_slowdown;
    _low_pri = rhs._low_pri;
    _memtable_insert_hint_per_batch = rhs._memtable_insert_hint_per_batch;
    _write_batch_max_bytes = rhs._write_batch_max_bytes;
  }

  WriteOptions& WriteOptions::operator= (WriteOptions&& rhs) noexcept {
    _sync = rhs._sync;
    _disable_wal = rhs._disable_wal;
    _no_slowdown = rhs._no_slowdown;
    _low_pri = rhs._low_pri;
    _memtable_insert_hint_per_batch = rhs._memtable_insert_hint_per_batch;
    _write_batch_max_bytes = rhs._write_batch_max_bytes;
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void WriteOptions::parse_from_proto(const granite::pb::WriteOptions& pb) {
    _sync = pb.sync();
    _disable_wal = pb.disable_wal();
    _no_slowdown = pb.no_slowdown();
    _low_pri = pb.low_pri();
    _memtable_insert_hint_per_batch = pb.memtable_insert_hint_per_batch();
    _write_batch_max_bytes = pb.write_batch_max_bytes();
  }

  void WriteOptions::serialize_to_proto(granite::pb::WriteOptions& pb) const {
    pb.set_sync(_sync);
    pb.set_disable_wal(_disable_wal);
    pb.set_no_slowdown(_no_slowdown);
    pb.set_low_pri(_low_pri);
    pb.set_memtable_insert_hint_per_batch(_memtable_insert_hint_per_batch);
    pb.set_write_batch_max_bytes(_write_batch_max_bytes);
  }

  turbo::Status WriteOptions::parse_from_json(const std::string& json) {
    granite::pb::WriteOptions pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status WriteOptions::serialize_to_json(std::string& json) const {
    granite::pb::WriteOptions pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string WriteOptions::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* RocksDBConfig::get_descriptor() {
    return granite::pb::RocksDBConfig::descriptor();
  }

  RocksDBConfig::RocksDBConfig() {
  }

  RocksDBConfig::~RocksDBConfig() {
  }

  RocksDBConfig::RocksDBConfig(const RocksDBConfig& rhs) {
    _block_size = rhs._block_size;
    _cache_index_and_filter_blocks = rhs._cache_index_and_filter_blocks;
    _block_cache_size = rhs._block_cache_size;
    _block_cache_type = rhs._block_cache_type;
    _metadata_block_cache_size = rhs._metadata_block_cache_size;
    _subkey_block_cache_size = rhs._subkey_block_cache_size;
    _share_metadata_and_subkey_block_cache = rhs._share_metadata_and_subkey_block_cache;
    _max_open_files = rhs._max_open_files;
    _write_buffer_size = rhs._write_buffer_size;
    _max_write_buffer_number = rhs._max_write_buffer_number;
    _min_write_buffer_number_to_merge = rhs._min_write_buffer_number_to_merge;
    _max_background_compactions = rhs._max_background_compactions;
    _max_background_flushes = rhs._max_background_flushes;
    _max_subcompactions = rhs._max_subcompactions;
    _stats_dump_period_sec = rhs._stats_dump_period_sec;
    _enable_pipelined_write = rhs._enable_pipelined_write;
    _delayed_write_rate = rhs._delayed_write_rate;
    _compaction_readahead_size = rhs._compaction_readahead_size;
    _target_file_size_base = rhs._target_file_size_base;
    _wal_compression = rhs._wal_compression;
    _wal_ttl_seconds = rhs._wal_ttl_seconds;
    _wal_size_limit_mb = rhs._wal_size_limit_mb;
    _max_total_wal_size = rhs._max_total_wal_size;
    _dump_malloc_stats = rhs._dump_malloc_stats;
    _level0_slowdown_writes_trigger = rhs._level0_slowdown_writes_trigger;
    _level0_stop_writes_trigger = rhs._level0_stop_writes_trigger;
    _level0_file_num_compaction_trigger = rhs._level0_file_num_compaction_trigger;
    _compression = rhs._compression;
    _compression_start_level = rhs._compression_start_level;
    _compression_level = rhs._compression_level;
    _compression_max_dict_bytes = rhs._compression_max_dict_bytes;
    _compression_zstd_max_train_bytes = rhs._compression_zstd_max_train_bytes;
    _disable_auto_compactions = rhs._disable_auto_compactions;
    _enable_blob_files = rhs._enable_blob_files;
    _min_blob_size = rhs._min_blob_size;
    _blob_file_size = rhs._blob_file_size;
    _enable_blob_garbage_collection = rhs._enable_blob_garbage_collection;
    _blob_garbage_collection_age_cutoff = rhs._blob_garbage_collection_age_cutoff;
    _max_bytes_for_level_base = rhs._max_bytes_for_level_base;
    _max_bytes_for_level_multiplier = rhs._max_bytes_for_level_multiplier;
    _level_compaction_dynamic_level_bytes = rhs._level_compaction_dynamic_level_bytes;
    _max_background_jobs = rhs._max_background_jobs;
    _rate_limiter_auto_tuned = rhs._rate_limiter_auto_tuned;
    _avoid_unnecessary_blocking_io = rhs._avoid_unnecessary_blocking_io;
    _partition_filters = rhs._partition_filters;
    _max_compaction_bytes = rhs._max_compaction_bytes;
    _sst_file_delete_rate_bytes_per_sec = rhs._sst_file_delete_rate_bytes_per_sec;
    _periodic_compaction_seconds = rhs._periodic_compaction_seconds;
    _ttl = rhs._ttl;
    _daily_offpeak_time_utc = rhs._daily_offpeak_time_utc;
    _write_options = rhs._write_options;
    _read_options = rhs._read_options;
  }

  RocksDBConfig& RocksDBConfig::operator= (const RocksDBConfig& rhs) {
    _block_size = rhs._block_size;
    _cache_index_and_filter_blocks = rhs._cache_index_and_filter_blocks;
    _block_cache_size = rhs._block_cache_size;
    _block_cache_type = rhs._block_cache_type;
    _metadata_block_cache_size = rhs._metadata_block_cache_size;
    _subkey_block_cache_size = rhs._subkey_block_cache_size;
    _share_metadata_and_subkey_block_cache = rhs._share_metadata_and_subkey_block_cache;
    _max_open_files = rhs._max_open_files;
    _write_buffer_size = rhs._write_buffer_size;
    _max_write_buffer_number = rhs._max_write_buffer_number;
    _min_write_buffer_number_to_merge = rhs._min_write_buffer_number_to_merge;
    _max_background_compactions = rhs._max_background_compactions;
    _max_background_flushes = rhs._max_background_flushes;
    _max_subcompactions = rhs._max_subcompactions;
    _stats_dump_period_sec = rhs._stats_dump_period_sec;
    _enable_pipelined_write = rhs._enable_pipelined_write;
    _delayed_write_rate = rhs._delayed_write_rate;
    _compaction_readahead_size = rhs._compaction_readahead_size;
    _target_file_size_base = rhs._target_file_size_base;
    _wal_compression = rhs._wal_compression;
    _wal_ttl_seconds = rhs._wal_ttl_seconds;
    _wal_size_limit_mb = rhs._wal_size_limit_mb;
    _max_total_wal_size = rhs._max_total_wal_size;
    _dump_malloc_stats = rhs._dump_malloc_stats;
    _level0_slowdown_writes_trigger = rhs._level0_slowdown_writes_trigger;
    _level0_stop_writes_trigger = rhs._level0_stop_writes_trigger;
    _level0_file_num_compaction_trigger = rhs._level0_file_num_compaction_trigger;
    _compression = rhs._compression;
    _compression_start_level = rhs._compression_start_level;
    _compression_level = rhs._compression_level;
    _compression_max_dict_bytes = rhs._compression_max_dict_bytes;
    _compression_zstd_max_train_bytes = rhs._compression_zstd_max_train_bytes;
    _disable_auto_compactions = rhs._disable_auto_compactions;
    _enable_blob_files = rhs._enable_blob_files;
    _min_blob_size = rhs._min_blob_size;
    _blob_file_size = rhs._blob_file_size;
    _enable_blob_garbage_collection = rhs._enable_blob_garbage_collection;
    _blob_garbage_collection_age_cutoff = rhs._blob_garbage_collection_age_cutoff;
    _max_bytes_for_level_base = rhs._max_bytes_for_level_base;
    _max_bytes_for_level_multiplier = rhs._max_bytes_for_level_multiplier;
    _level_compaction_dynamic_level_bytes = rhs._level_compaction_dynamic_level_bytes;
    _max_background_jobs = rhs._max_background_jobs;
    _rate_limiter_auto_tuned = rhs._rate_limiter_auto_tuned;
    _avoid_unnecessary_blocking_io = rhs._avoid_unnecessary_blocking_io;
    _partition_filters = rhs._partition_filters;
    _max_compaction_bytes = rhs._max_compaction_bytes;
    _sst_file_delete_rate_bytes_per_sec = rhs._sst_file_delete_rate_bytes_per_sec;
    _periodic_compaction_seconds = rhs._periodic_compaction_seconds;
    _ttl = rhs._ttl;
    _daily_offpeak_time_utc = rhs._daily_offpeak_time_utc;
    _write_options = rhs._write_options;
    _read_options = rhs._read_options;
    return *this;
  }

  RocksDBConfig::RocksDBConfig(RocksDBConfig&& rhs) noexcept {
    _block_size = rhs._block_size;
    _cache_index_and_filter_blocks = rhs._cache_index_and_filter_blocks;
    _block_cache_size = rhs._block_cache_size;
    _block_cache_type = rhs._block_cache_type;
    _metadata_block_cache_size = rhs._metadata_block_cache_size;
    _subkey_block_cache_size = rhs._subkey_block_cache_size;
    _share_metadata_and_subkey_block_cache = rhs._share_metadata_and_subkey_block_cache;
    _max_open_files = rhs._max_open_files;
    _write_buffer_size = rhs._write_buffer_size;
    _max_write_buffer_number = rhs._max_write_buffer_number;
    _min_write_buffer_number_to_merge = rhs._min_write_buffer_number_to_merge;
    _max_background_compactions = rhs._max_background_compactions;
    _max_background_flushes = rhs._max_background_flushes;
    _max_subcompactions = rhs._max_subcompactions;
    _stats_dump_period_sec = rhs._stats_dump_period_sec;
    _enable_pipelined_write = rhs._enable_pipelined_write;
    _delayed_write_rate = rhs._delayed_write_rate;
    _compaction_readahead_size = rhs._compaction_readahead_size;
    _target_file_size_base = rhs._target_file_size_base;
    _wal_compression = rhs._wal_compression;
    _wal_ttl_seconds = rhs._wal_ttl_seconds;
    _wal_size_limit_mb = rhs._wal_size_limit_mb;
    _max_total_wal_size = rhs._max_total_wal_size;
    _dump_malloc_stats = rhs._dump_malloc_stats;
    _level0_slowdown_writes_trigger = rhs._level0_slowdown_writes_trigger;
    _level0_stop_writes_trigger = rhs._level0_stop_writes_trigger;
    _level0_file_num_compaction_trigger = rhs._level0_file_num_compaction_trigger;
    _compression = rhs._compression;
    _compression_start_level = rhs._compression_start_level;
    _compression_level = rhs._compression_level;
    _compression_max_dict_bytes = rhs._compression_max_dict_bytes;
    _compression_zstd_max_train_bytes = rhs._compression_zstd_max_train_bytes;
    _disable_auto_compactions = rhs._disable_auto_compactions;
    _enable_blob_files = rhs._enable_blob_files;
    _min_blob_size = rhs._min_blob_size;
    _blob_file_size = rhs._blob_file_size;
    _enable_blob_garbage_collection = rhs._enable_blob_garbage_collection;
    _blob_garbage_collection_age_cutoff = rhs._blob_garbage_collection_age_cutoff;
    _max_bytes_for_level_base = rhs._max_bytes_for_level_base;
    _max_bytes_for_level_multiplier = rhs._max_bytes_for_level_multiplier;
    _level_compaction_dynamic_level_bytes = rhs._level_compaction_dynamic_level_bytes;
    _max_background_jobs = rhs._max_background_jobs;
    _rate_limiter_auto_tuned = rhs._rate_limiter_auto_tuned;
    _avoid_unnecessary_blocking_io = rhs._avoid_unnecessary_blocking_io;
    _partition_filters = rhs._partition_filters;
    _max_compaction_bytes = rhs._max_compaction_bytes;
    _sst_file_delete_rate_bytes_per_sec = rhs._sst_file_delete_rate_bytes_per_sec;
    _periodic_compaction_seconds = rhs._periodic_compaction_seconds;
    _ttl = rhs._ttl;
    _daily_offpeak_time_utc = std::move(rhs._daily_offpeak_time_utc);
    _write_options = std::move(rhs._write_options);
    _read_options = std::move(rhs._read_options);
  }

  RocksDBConfig& RocksDBConfig::operator= (RocksDBConfig&& rhs) noexcept {
    _block_size = rhs._block_size;
    _cache_index_and_filter_blocks = rhs._cache_index_and_filter_blocks;
    _block_cache_size = rhs._block_cache_size;
    _block_cache_type = rhs._block_cache_type;
    _metadata_block_cache_size = rhs._metadata_block_cache_size;
    _subkey_block_cache_size = rhs._subkey_block_cache_size;
    _share_metadata_and_subkey_block_cache = rhs._share_metadata_and_subkey_block_cache;
    _max_open_files = rhs._max_open_files;
    _write_buffer_size = rhs._write_buffer_size;
    _max_write_buffer_number = rhs._max_write_buffer_number;
    _min_write_buffer_number_to_merge = rhs._min_write_buffer_number_to_merge;
    _max_background_compactions = rhs._max_background_compactions;
    _max_background_flushes = rhs._max_background_flushes;
    _max_subcompactions = rhs._max_subcompactions;
    _stats_dump_period_sec = rhs._stats_dump_period_sec;
    _enable_pipelined_write = rhs._enable_pipelined_write;
    _delayed_write_rate = rhs._delayed_write_rate;
    _compaction_readahead_size = rhs._compaction_readahead_size;
    _target_file_size_base = rhs._target_file_size_base;
    _wal_compression = rhs._wal_compression;
    _wal_ttl_seconds = rhs._wal_ttl_seconds;
    _wal_size_limit_mb = rhs._wal_size_limit_mb;
    _max_total_wal_size = rhs._max_total_wal_size;
    _dump_malloc_stats = rhs._dump_malloc_stats;
    _level0_slowdown_writes_trigger = rhs._level0_slowdown_writes_trigger;
    _level0_stop_writes_trigger = rhs._level0_stop_writes_trigger;
    _level0_file_num_compaction_trigger = rhs._level0_file_num_compaction_trigger;
    _compression = rhs._compression;
    _compression_start_level = rhs._compression_start_level;
    _compression_level = rhs._compression_level;
    _compression_max_dict_bytes = rhs._compression_max_dict_bytes;
    _compression_zstd_max_train_bytes = rhs._compression_zstd_max_train_bytes;
    _disable_auto_compactions = rhs._disable_auto_compactions;
    _enable_blob_files = rhs._enable_blob_files;
    _min_blob_size = rhs._min_blob_size;
    _blob_file_size = rhs._blob_file_size;
    _enable_blob_garbage_collection = rhs._enable_blob_garbage_collection;
    _blob_garbage_collection_age_cutoff = rhs._blob_garbage_collection_age_cutoff;
    _max_bytes_for_level_base = rhs._max_bytes_for_level_base;
    _max_bytes_for_level_multiplier = rhs._max_bytes_for_level_multiplier;
    _level_compaction_dynamic_level_bytes = rhs._level_compaction_dynamic_level_bytes;
    _max_background_jobs = rhs._max_background_jobs;
    _rate_limiter_auto_tuned = rhs._rate_limiter_auto_tuned;
    _avoid_unnecessary_blocking_io = rhs._avoid_unnecessary_blocking_io;
    _partition_filters = rhs._partition_filters;
    _max_compaction_bytes = rhs._max_compaction_bytes;
    _sst_file_delete_rate_bytes_per_sec = rhs._sst_file_delete_rate_bytes_per_sec;
    _periodic_compaction_seconds = rhs._periodic_compaction_seconds;
    _ttl = rhs._ttl;
    _daily_offpeak_time_utc = std::move(rhs._daily_offpeak_time_utc);
    _write_options = std::move(rhs._write_options);
    _read_options = std::move(rhs._read_options);
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void RocksDBConfig::parse_from_proto(const granite::pb::RocksDBConfig& pb) {
    _block_size = pb.block_size();
    _cache_index_and_filter_blocks = pb.cache_index_and_filter_blocks();
    _block_cache_size = pb.block_cache_size();
    _block_cache_type = static_cast<BlockCacheType>(pb.block_cache_type());
    _metadata_block_cache_size = pb.metadata_block_cache_size();
    _subkey_block_cache_size = pb.subkey_block_cache_size();
    _share_metadata_and_subkey_block_cache = pb.share_metadata_and_subkey_block_cache();
    _max_open_files = pb.max_open_files();
    _write_buffer_size = pb.write_buffer_size();
    _max_write_buffer_number = pb.max_write_buffer_number();
    _min_write_buffer_number_to_merge = pb.min_write_buffer_number_to_merge();
    _max_background_compactions = pb.max_background_compactions();
    _max_background_flushes = pb.max_background_flushes();
    _max_subcompactions = pb.max_subcompactions();
    _stats_dump_period_sec = pb.stats_dump_period_sec();
    _enable_pipelined_write = pb.enable_pipelined_write();
    _delayed_write_rate = pb.delayed_write_rate();
    _compaction_readahead_size = pb.compaction_readahead_size();
    _target_file_size_base = pb.target_file_size_base();
    _wal_compression = static_cast<CompressionType>(pb.wal_compression());
    _wal_ttl_seconds = pb.wal_ttl_seconds();
    _wal_size_limit_mb = pb.wal_size_limit_mb();
    _max_total_wal_size = pb.max_total_wal_size();
    _dump_malloc_stats = pb.dump_malloc_stats();
    _level0_slowdown_writes_trigger = pb.level0_slowdown_writes_trigger();
    _level0_stop_writes_trigger = pb.level0_stop_writes_trigger();
    _level0_file_num_compaction_trigger = pb.level0_file_num_compaction_trigger();
    _compression = static_cast<CompressionType>(pb.compression());
    _compression_start_level = pb.compression_start_level();
    _compression_level = pb.compression_level();
    _compression_max_dict_bytes = pb.compression_max_dict_bytes();
    _compression_zstd_max_train_bytes = pb.compression_zstd_max_train_bytes();
    _disable_auto_compactions = pb.disable_auto_compactions();
    _enable_blob_files = pb.enable_blob_files();
    _min_blob_size = pb.min_blob_size();
    _blob_file_size = pb.blob_file_size();
    _enable_blob_garbage_collection = pb.enable_blob_garbage_collection();
    _blob_garbage_collection_age_cutoff = pb.blob_garbage_collection_age_cutoff();
    _max_bytes_for_level_base = pb.max_bytes_for_level_base();
    _max_bytes_for_level_multiplier = pb.max_bytes_for_level_multiplier();
    _level_compaction_dynamic_level_bytes = pb.level_compaction_dynamic_level_bytes();
    _max_background_jobs = pb.max_background_jobs();
    _rate_limiter_auto_tuned = pb.rate_limiter_auto_tuned();
    _avoid_unnecessary_blocking_io = pb.avoid_unnecessary_blocking_io();
    _partition_filters = pb.partition_filters();
    _max_compaction_bytes = pb.max_compaction_bytes();
    _sst_file_delete_rate_bytes_per_sec = pb.sst_file_delete_rate_bytes_per_sec();
    _periodic_compaction_seconds = pb.periodic_compaction_seconds();
    _ttl = pb.ttl();
    _daily_offpeak_time_utc = pb.daily_offpeak_time_utc();
    _write_options.parse_from_proto(pb.write_options());
    _read_options.parse_from_proto(pb.read_options());
  }

  void RocksDBConfig::serialize_to_proto(granite::pb::RocksDBConfig& pb) const {
    pb.set_block_size(_block_size);
    pb.set_cache_index_and_filter_blocks(_cache_index_and_filter_blocks);
    pb.set_block_cache_size(_block_cache_size);
    pb.set_block_cache_type(static_cast<granite::pb::BlockCacheType>(_block_cache_type));
    pb.set_metadata_block_cache_size(_metadata_block_cache_size);
    pb.set_subkey_block_cache_size(_subkey_block_cache_size);
    pb.set_share_metadata_and_subkey_block_cache(_share_metadata_and_subkey_block_cache);
    pb.set_max_open_files(_max_open_files);
    pb.set_write_buffer_size(_write_buffer_size);
    pb.set_max_write_buffer_number(_max_write_buffer_number);
    pb.set_min_write_buffer_number_to_merge(_min_write_buffer_number_to_merge);
    pb.set_max_background_compactions(_max_background_compactions);
    pb.set_max_background_flushes(_max_background_flushes);
    pb.set_max_subcompactions(_max_subcompactions);
    pb.set_stats_dump_period_sec(_stats_dump_period_sec);
    pb.set_enable_pipelined_write(_enable_pipelined_write);
    pb.set_delayed_write_rate(_delayed_write_rate);
    pb.set_compaction_readahead_size(_compaction_readahead_size);
    pb.set_target_file_size_base(_target_file_size_base);
    pb.set_wal_compression(static_cast<granite::pb::CompressionType>(_wal_compression));
    pb.set_wal_ttl_seconds(_wal_ttl_seconds);
    pb.set_wal_size_limit_mb(_wal_size_limit_mb);
    pb.set_max_total_wal_size(_max_total_wal_size);
    pb.set_dump_malloc_stats(_dump_malloc_stats);
    pb.set_level0_slowdown_writes_trigger(_level0_slowdown_writes_trigger);
    pb.set_level0_stop_writes_trigger(_level0_stop_writes_trigger);
    pb.set_level0_file_num_compaction_trigger(_level0_file_num_compaction_trigger);
    pb.set_compression(static_cast<granite::pb::CompressionType>(_compression));
    pb.set_compression_start_level(_compression_start_level);
    pb.set_compression_level(_compression_level);
    pb.set_compression_max_dict_bytes(_compression_max_dict_bytes);
    pb.set_compression_zstd_max_train_bytes(_compression_zstd_max_train_bytes);
    pb.set_disable_auto_compactions(_disable_auto_compactions);
    pb.set_enable_blob_files(_enable_blob_files);
    pb.set_min_blob_size(_min_blob_size);
    pb.set_blob_file_size(_blob_file_size);
    pb.set_enable_blob_garbage_collection(_enable_blob_garbage_collection);
    pb.set_blob_garbage_collection_age_cutoff(_blob_garbage_collection_age_cutoff);
    pb.set_max_bytes_for_level_base(_max_bytes_for_level_base);
    pb.set_max_bytes_for_level_multiplier(_max_bytes_for_level_multiplier);
    pb.set_level_compaction_dynamic_level_bytes(_level_compaction_dynamic_level_bytes);
    pb.set_max_background_jobs(_max_background_jobs);
    pb.set_rate_limiter_auto_tuned(_rate_limiter_auto_tuned);
    pb.set_avoid_unnecessary_blocking_io(_avoid_unnecessary_blocking_io);
    pb.set_partition_filters(_partition_filters);
    pb.set_max_compaction_bytes(_max_compaction_bytes);
    pb.set_sst_file_delete_rate_bytes_per_sec(_sst_file_delete_rate_bytes_per_sec);
    pb.set_periodic_compaction_seconds(_periodic_compaction_seconds);
    pb.set_ttl(_ttl);
    pb.set_daily_offpeak_time_utc(_daily_offpeak_time_utc);
    _write_options.serialize_to_proto(*pb.mutable_write_options());
    _read_options.serialize_to_proto(*pb.mutable_read_options());
  }

  turbo::Status RocksDBConfig::parse_from_json(const std::string& json) {
    granite::pb::RocksDBConfig pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status RocksDBConfig::serialize_to_json(std::string& json) const {
    granite::pb::RocksDBConfig pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string RocksDBConfig::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* Config::get_descriptor() {
    return granite::pb::Config::descriptor();
  }

  Config::Config() {
  }

  Config::~Config() {
  }

  Config::Config(const Config& rhs) {
    _max_backup_to_keep = rhs._max_backup_to_keep;
    _max_backup_keep_hours = rhs._max_backup_keep_hours;
    _proto_max_bulk_len = rhs._proto_max_bulk_len;
    _max_db_size = rhs._max_db_size;
    _max_io_mb = rhs._max_io_mb;
    _enable_blob_cache = rhs._enable_blob_cache;
    _max_bitmap_to_string_mb = rhs._max_bitmap_to_string_mb;
    _use_rsid_psync = rhs._use_rsid_psync;
    _dir = rhs._dir;
    _db_dir = rhs._db_dir;
    _backup_dir = rhs._backup_dir;
    _backup_sync_dir = rhs._backup_sync_dir;
    _checkpoint_dir = rhs._checkpoint_dir;
    _sync_checkpoint_dir = rhs._sync_checkpoint_dir;
    _db_name = rhs._db_name;
    _compact_cron = rhs._compact_cron;
    _bgsave_cron = rhs._bgsave_cron;
    _dbsize_scan_cron = rhs._dbsize_scan_cron;
    _compaction_checker_cron = rhs._compaction_checker_cron;
    _force_compact_file_age = rhs._force_compact_file_age;
    _force_compact_file_min_deleted_percentage = rhs._force_compact_file_min_deleted_percentage;
    _redis_cursor_compatible = rhs._redis_cursor_compatible;
    _redis_databases = rhs._redis_databases;
    _resp3_enabled = rhs._resp3_enabled;
    _load_tokens = rhs._load_tokens;
    _profiling_sample_ratio = rhs._profiling_sample_ratio;
    _profiling_sample_record_threshold_ms = rhs._profiling_sample_record_threshold_ms;
    _profiling_sample_record_max_len = rhs._profiling_sample_record_max_len;
    _profiling_sample_commands = rhs._profiling_sample_commands;
    _profiling_sample_all_commands = rhs._profiling_sample_all_commands;
    _json_max_nesting_depth = rhs._json_max_nesting_depth;
    _json_storage_format = rhs._json_storage_format;
    _txn_context_enabled = rhs._txn_context_enabled;
    _skip_block_cache_deallocation_on_close = rhs._skip_block_cache_deallocation_on_close;
    _histogram_bucket_boundaries = rhs._histogram_bucket_boundaries;
    _rocks_db = rhs._rocks_db;
  }

  Config& Config::operator= (const Config& rhs) {
    _max_backup_to_keep = rhs._max_backup_to_keep;
    _max_backup_keep_hours = rhs._max_backup_keep_hours;
    _proto_max_bulk_len = rhs._proto_max_bulk_len;
    _max_db_size = rhs._max_db_size;
    _max_io_mb = rhs._max_io_mb;
    _enable_blob_cache = rhs._enable_blob_cache;
    _max_bitmap_to_string_mb = rhs._max_bitmap_to_string_mb;
    _use_rsid_psync = rhs._use_rsid_psync;
    _dir = rhs._dir;
    _db_dir = rhs._db_dir;
    _backup_dir = rhs._backup_dir;
    _backup_sync_dir = rhs._backup_sync_dir;
    _checkpoint_dir = rhs._checkpoint_dir;
    _sync_checkpoint_dir = rhs._sync_checkpoint_dir;
    _db_name = rhs._db_name;
    _compact_cron = rhs._compact_cron;
    _bgsave_cron = rhs._bgsave_cron;
    _dbsize_scan_cron = rhs._dbsize_scan_cron;
    _compaction_checker_cron = rhs._compaction_checker_cron;
    _force_compact_file_age = rhs._force_compact_file_age;
    _force_compact_file_min_deleted_percentage = rhs._force_compact_file_min_deleted_percentage;
    _redis_cursor_compatible = rhs._redis_cursor_compatible;
    _redis_databases = rhs._redis_databases;
    _resp3_enabled = rhs._resp3_enabled;
    _load_tokens = rhs._load_tokens;
    _profiling_sample_ratio = rhs._profiling_sample_ratio;
    _profiling_sample_record_threshold_ms = rhs._profiling_sample_record_threshold_ms;
    _profiling_sample_record_max_len = rhs._profiling_sample_record_max_len;
    _profiling_sample_commands = rhs._profiling_sample_commands;
    _profiling_sample_all_commands = rhs._profiling_sample_all_commands;
    _json_max_nesting_depth = rhs._json_max_nesting_depth;
    _json_storage_format = rhs._json_storage_format;
    _txn_context_enabled = rhs._txn_context_enabled;
    _skip_block_cache_deallocation_on_close = rhs._skip_block_cache_deallocation_on_close;
    _histogram_bucket_boundaries = rhs._histogram_bucket_boundaries;
    _rocks_db = rhs._rocks_db;
    return *this;
  }

  Config::Config(Config&& rhs) noexcept {
    _max_backup_to_keep = rhs._max_backup_to_keep;
    _max_backup_keep_hours = rhs._max_backup_keep_hours;
    _proto_max_bulk_len = rhs._proto_max_bulk_len;
    _max_db_size = rhs._max_db_size;
    _max_io_mb = rhs._max_io_mb;
    _enable_blob_cache = rhs._enable_blob_cache;
    _max_bitmap_to_string_mb = rhs._max_bitmap_to_string_mb;
    _use_rsid_psync = rhs._use_rsid_psync;
    _dir = std::move(rhs._dir);
    _db_dir = std::move(rhs._db_dir);
    _backup_dir = std::move(rhs._backup_dir);
    _backup_sync_dir = std::move(rhs._backup_sync_dir);
    _checkpoint_dir = std::move(rhs._checkpoint_dir);
    _sync_checkpoint_dir = std::move(rhs._sync_checkpoint_dir);
    _db_name = std::move(rhs._db_name);
    _compact_cron = std::move(rhs._compact_cron);
    _bgsave_cron = std::move(rhs._bgsave_cron);
    _dbsize_scan_cron = std::move(rhs._dbsize_scan_cron);
    _compaction_checker_cron = std::move(rhs._compaction_checker_cron);
    _force_compact_file_age = rhs._force_compact_file_age;
    _force_compact_file_min_deleted_percentage = rhs._force_compact_file_min_deleted_percentage;
    _redis_cursor_compatible = rhs._redis_cursor_compatible;
    _redis_databases = rhs._redis_databases;
    _resp3_enabled = rhs._resp3_enabled;
    _load_tokens = std::move(rhs._load_tokens);
    _profiling_sample_ratio = rhs._profiling_sample_ratio;
    _profiling_sample_record_threshold_ms = rhs._profiling_sample_record_threshold_ms;
    _profiling_sample_record_max_len = rhs._profiling_sample_record_max_len;
    _profiling_sample_commands = std::move(rhs._profiling_sample_commands);
    _profiling_sample_all_commands = rhs._profiling_sample_all_commands;
    _json_max_nesting_depth = rhs._json_max_nesting_depth;
    _json_storage_format = rhs._json_storage_format;
    _txn_context_enabled = rhs._txn_context_enabled;
    _skip_block_cache_deallocation_on_close = rhs._skip_block_cache_deallocation_on_close;
    _histogram_bucket_boundaries = std::move(rhs._histogram_bucket_boundaries);
    _rocks_db = std::move(rhs._rocks_db);
  }

  Config& Config::operator= (Config&& rhs) noexcept {
    _max_backup_to_keep = rhs._max_backup_to_keep;
    _max_backup_keep_hours = rhs._max_backup_keep_hours;
    _proto_max_bulk_len = rhs._proto_max_bulk_len;
    _max_db_size = rhs._max_db_size;
    _max_io_mb = rhs._max_io_mb;
    _enable_blob_cache = rhs._enable_blob_cache;
    _max_bitmap_to_string_mb = rhs._max_bitmap_to_string_mb;
    _use_rsid_psync = rhs._use_rsid_psync;
    _dir = std::move(rhs._dir);
    _db_dir = std::move(rhs._db_dir);
    _backup_dir = std::move(rhs._backup_dir);
    _backup_sync_dir = std::move(rhs._backup_sync_dir);
    _checkpoint_dir = std::move(rhs._checkpoint_dir);
    _sync_checkpoint_dir = std::move(rhs._sync_checkpoint_dir);
    _db_name = std::move(rhs._db_name);
    _compact_cron = std::move(rhs._compact_cron);
    _bgsave_cron = std::move(rhs._bgsave_cron);
    _dbsize_scan_cron = std::move(rhs._dbsize_scan_cron);
    _compaction_checker_cron = std::move(rhs._compaction_checker_cron);
    _force_compact_file_age = rhs._force_compact_file_age;
    _force_compact_file_min_deleted_percentage = rhs._force_compact_file_min_deleted_percentage;
    _redis_cursor_compatible = rhs._redis_cursor_compatible;
    _redis_databases = rhs._redis_databases;
    _resp3_enabled = rhs._resp3_enabled;
    _load_tokens = std::move(rhs._load_tokens);
    _profiling_sample_ratio = rhs._profiling_sample_ratio;
    _profiling_sample_record_threshold_ms = rhs._profiling_sample_record_threshold_ms;
    _profiling_sample_record_max_len = rhs._profiling_sample_record_max_len;
    _profiling_sample_commands = std::move(rhs._profiling_sample_commands);
    _profiling_sample_all_commands = rhs._profiling_sample_all_commands;
    _json_max_nesting_depth = rhs._json_max_nesting_depth;
    _json_storage_format = rhs._json_storage_format;
    _txn_context_enabled = rhs._txn_context_enabled;
    _skip_block_cache_deallocation_on_close = rhs._skip_block_cache_deallocation_on_close;
    _histogram_bucket_boundaries = std::move(rhs._histogram_bucket_boundaries);
    _rocks_db = std::move(rhs._rocks_db);
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void Config::parse_from_proto(const granite::pb::Config& pb) {
    _max_backup_to_keep = pb.max_backup_to_keep();
    _max_backup_keep_hours = pb.max_backup_keep_hours();
    _proto_max_bulk_len = pb.proto_max_bulk_len();
    _max_db_size = pb.max_db_size();
    _max_io_mb = pb.max_io_mb();
    _enable_blob_cache = pb.enable_blob_cache();
    _max_bitmap_to_string_mb = pb.max_bitmap_to_string_mb();
    _use_rsid_psync = pb.use_rsid_psync();
    _dir = pb.dir();
    _db_dir = pb.db_dir();
    _backup_dir = pb.backup_dir();
    _backup_sync_dir = pb.backup_sync_dir();
    _checkpoint_dir = pb.checkpoint_dir();
    _sync_checkpoint_dir = pb.sync_checkpoint_dir();
    _db_name = pb.db_name();
    _compact_cron = pb.compact_cron();
    _bgsave_cron = pb.bgsave_cron();
    _dbsize_scan_cron = pb.dbsize_scan_cron();
    _compaction_checker_cron = pb.compaction_checker_cron();
    _force_compact_file_age = pb.force_compact_file_age();
    _force_compact_file_min_deleted_percentage = pb.force_compact_file_min_deleted_percentage();
    _redis_cursor_compatible = pb.redis_cursor_compatible();
    _redis_databases = pb.redis_databases();
    _resp3_enabled = pb.resp3_enabled();
    _load_tokens.reserve(pb.load_tokens_size());
    for(auto &it : pb.load_tokens()) {
      _load_tokens[it.first] = it.second;
    }
    _profiling_sample_ratio = pb.profiling_sample_ratio();
    _profiling_sample_record_threshold_ms = pb.profiling_sample_record_threshold_ms();
    _profiling_sample_record_max_len = pb.profiling_sample_record_max_len();
    _profiling_sample_commands.reserve(pb.profiling_sample_commands_size());
    for(size_t i = 0; i < pb.profiling_sample_commands_size(); ++i) {
      _profiling_sample_commands.push_back(pb.profiling_sample_commands(i));
    }
    _profiling_sample_all_commands = pb.profiling_sample_all_commands();
    _json_max_nesting_depth = pb.json_max_nesting_depth();
    _json_storage_format = static_cast<JsonStorageFormat>(pb.json_storage_format());
    _txn_context_enabled = pb.txn_context_enabled();
    _skip_block_cache_deallocation_on_close = pb.skip_block_cache_deallocation_on_close();
    _histogram_bucket_boundaries.reserve(pb.histogram_bucket_boundaries_size());
    auto &ref = pb.histogram_bucket_boundaries();
    for(size_t i = 0; i < pb.histogram_bucket_boundaries_size(); ++i) {
      _histogram_bucket_boundaries.push_back(ref[i]);
    }
    _rocks_db.parse_from_proto(pb.rocks_db());
  }

  void Config::serialize_to_proto(granite::pb::Config& pb) const {
    pb.set_max_backup_to_keep(_max_backup_to_keep);
    pb.set_max_backup_keep_hours(_max_backup_keep_hours);
    pb.set_proto_max_bulk_len(_proto_max_bulk_len);
    pb.set_max_db_size(_max_db_size);
    pb.set_max_io_mb(_max_io_mb);
    pb.set_enable_blob_cache(_enable_blob_cache);
    pb.set_max_bitmap_to_string_mb(_max_bitmap_to_string_mb);
    pb.set_use_rsid_psync(_use_rsid_psync);
    pb.set_dir(_dir);
    pb.set_db_dir(_db_dir);
    pb.set_backup_dir(_backup_dir);
    pb.set_backup_sync_dir(_backup_sync_dir);
    pb.set_checkpoint_dir(_checkpoint_dir);
    pb.set_sync_checkpoint_dir(_sync_checkpoint_dir);
    pb.set_db_name(_db_name);
    pb.set_compact_cron(_compact_cron);
    pb.set_bgsave_cron(_bgsave_cron);
    pb.set_dbsize_scan_cron(_dbsize_scan_cron);
    pb.set_compaction_checker_cron(_compaction_checker_cron);
    pb.set_force_compact_file_age(_force_compact_file_age);
    pb.set_force_compact_file_min_deleted_percentage(_force_compact_file_min_deleted_percentage);
    pb.set_redis_cursor_compatible(_redis_cursor_compatible);
    pb.set_redis_databases(_redis_databases);
    pb.set_resp3_enabled(_resp3_enabled);
    for(auto &it : _load_tokens) {
      (*pb.mutable_load_tokens())[it.first] = it.second;
    }
    pb.set_profiling_sample_ratio(_profiling_sample_ratio);
    pb.set_profiling_sample_record_threshold_ms(_profiling_sample_record_threshold_ms);
    pb.set_profiling_sample_record_max_len(_profiling_sample_record_max_len);
    pb.mutable_profiling_sample_commands()->Reserve(_profiling_sample_commands.size());
    for(size_t i = 0; i < _profiling_sample_commands.size(); ++i) {
      *pb.mutable_profiling_sample_commands()->Add() = _profiling_sample_commands[i];
    }
    pb.set_profiling_sample_all_commands(_profiling_sample_all_commands);
    pb.set_json_max_nesting_depth(_json_max_nesting_depth);
    pb.set_json_storage_format(static_cast<granite::pb::JsonStorageFormat>(_json_storage_format));
    pb.set_txn_context_enabled(_txn_context_enabled);
    pb.set_skip_block_cache_deallocation_on_close(_skip_block_cache_deallocation_on_close);
    pb.mutable_histogram_bucket_boundaries()->Reserve(_histogram_bucket_boundaries.size());
    for(size_t i = 0; i < _histogram_bucket_boundaries.size(); ++i) {
      *pb.mutable_histogram_bucket_boundaries()->Add() = _histogram_bucket_boundaries[i];
    }
    _rocks_db.serialize_to_proto(*pb.mutable_rocks_db());
  }

  turbo::Status Config::parse_from_json(const std::string& json) {
    granite::pb::Config pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status Config::serialize_to_json(std::string& json) const {
    granite::pb::Config pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string Config::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

}  // granite

