/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/config.proto */

#pragma once

#include <cstdint>
#include <string>
#include <optional>
#include <turbo/utility/status.h>

#include <google/protobuf/descriptor.h>
#include <tests/config.pb.h>
#include <turbo/container/flat_hash_map.h>



namespace granite {

  class ReadOptions;
  class WriteOptions;
  class RocksDBConfig;
  class Config;



  /// --- enums ---

  enum class JsonStorageFormat : uint32_t{
    JSON_DEFAULT = 0,
    JSON = 1,
    CBOR = 2
  };  // 
  std::optional<JsonStorageFormat> parse_JsonStorageFormat(std::string_view value);
  enum class BlockCacheType : uint32_t{
    LRU = 0,
    CLOCK = 1
  };  // 
  std::optional<BlockCacheType> parse_BlockCacheType(std::string_view value);
  enum class CompressionType : uint32_t{
    K_NO_COMPRESSION = 0,
    K_SNAPPY_COMPRESSION = 1,
    K_ZLIB_COMPRESSION = 2,
    K_BZIP2_COMPRESSION = 3,
    K_LZ4_COMPRESSION = 4,
    K_LZ4HC_COMPRESSION = 5,
    K_XPRESS_COMPRESSION = 6,
    K_ZSTD = 7,
    K_LAST_BUILTIN_COMPRESSION = 7,
    K_CUSTOM_COMPRESSION_80 = 128,
    K_FIRST_CUSTOM_COMPRESSION = 128,
    K_CUSTOM_COMPRESSION_81 = 129,
    K_CUSTOM_COMPRESSION_82 = 130,
    K_CUSTOM_COMPRESSION_83 = 131,
    K_CUSTOM_COMPRESSION_84 = 132,
    K_CUSTOM_COMPRESSION_85 = 133,
    K_CUSTOM_COMPRESSION_86 = 134,
    K_CUSTOM_COMPRESSION_87 = 135,
    K_CUSTOM_COMPRESSION_88 = 136,
    K_CUSTOM_COMPRESSION_89 = 137,
    K_CUSTOM_COMPRESSION_8A = 138,
    K_CUSTOM_COMPRESSION_8B = 139,
    K_CUSTOM_COMPRESSION_8C = 140,
    K_CUSTOM_COMPRESSION_8D = 141,
    K_CUSTOM_COMPRESSION_8E = 142,
    K_CUSTOM_COMPRESSION_8F = 143,
    K_CUSTOM_COMPRESSION_90 = 144,
    K_CUSTOM_COMPRESSION_91 = 145,
    K_CUSTOM_COMPRESSION_92 = 146,
    K_CUSTOM_COMPRESSION_93 = 147,
    K_CUSTOM_COMPRESSION_94 = 148,
    K_CUSTOM_COMPRESSION_95 = 149,
    K_CUSTOM_COMPRESSION_96 = 150,
    K_CUSTOM_COMPRESSION_97 = 151,
    K_CUSTOM_COMPRESSION_98 = 152,
    K_CUSTOM_COMPRESSION_99 = 153,
    K_CUSTOM_COMPRESSION_9A = 154,
    K_CUSTOM_COMPRESSION_9B = 155,
    K_CUSTOM_COMPRESSION_9C = 156,
    K_CUSTOM_COMPRESSION_9D = 157,
    K_CUSTOM_COMPRESSION_9E = 158,
    K_CUSTOM_COMPRESSION_9F = 159,
    K_CUSTOM_COMPRESSION_A0 = 160,
    K_CUSTOM_COMPRESSION_A1 = 161,
    K_CUSTOM_COMPRESSION_A2 = 162,
    K_CUSTOM_COMPRESSION_A3 = 163,
    K_CUSTOM_COMPRESSION_A4 = 164,
    K_CUSTOM_COMPRESSION_A5 = 165,
    K_CUSTOM_COMPRESSION_A6 = 166,
    K_CUSTOM_COMPRESSION_A7 = 167,
    K_CUSTOM_COMPRESSION_A8 = 168,
    K_CUSTOM_COMPRESSION_A9 = 169,
    K_CUSTOM_COMPRESSION_AA = 170,
    K_CUSTOM_COMPRESSION_AB = 171,
    K_CUSTOM_COMPRESSION_AC = 172,
    K_CUSTOM_COMPRESSION_AD = 173,
    K_CUSTOM_COMPRESSION_AE = 174,
    K_CUSTOM_COMPRESSION_AF = 175,
    K_CUSTOM_COMPRESSION_B0 = 176,
    K_CUSTOM_COMPRESSION_B1 = 177,
    K_CUSTOM_COMPRESSION_B2 = 178,
    K_CUSTOM_COMPRESSION_B3 = 179,
    K_CUSTOM_COMPRESSION_B4 = 180,
    K_CUSTOM_COMPRESSION_B5 = 181,
    K_CUSTOM_COMPRESSION_B6 = 182,
    K_CUSTOM_COMPRESSION_B7 = 183,
    K_CUSTOM_COMPRESSION_B8 = 184,
    K_CUSTOM_COMPRESSION_B9 = 185,
    K_CUSTOM_COMPRESSION_BA = 186,
    K_CUSTOM_COMPRESSION_BB = 187,
    K_CUSTOM_COMPRESSION_BC = 188,
    K_CUSTOM_COMPRESSION_BD = 189,
    K_CUSTOM_COMPRESSION_BE = 190,
    K_CUSTOM_COMPRESSION_BF = 191,
    K_CUSTOM_COMPRESSION_C0 = 192,
    K_CUSTOM_COMPRESSION_C1 = 193,
    K_CUSTOM_COMPRESSION_C2 = 194,
    K_CUSTOM_COMPRESSION_C3 = 195,
    K_CUSTOM_COMPRESSION_C4 = 196,
    K_CUSTOM_COMPRESSION_C5 = 197,
    K_CUSTOM_COMPRESSION_C6 = 198,
    K_CUSTOM_COMPRESSION_C7 = 199,
    K_CUSTOM_COMPRESSION_C8 = 200,
    K_CUSTOM_COMPRESSION_C9 = 201,
    K_CUSTOM_COMPRESSION_CA = 202,
    K_CUSTOM_COMPRESSION_CB = 203,
    K_CUSTOM_COMPRESSION_CC = 204,
    K_CUSTOM_COMPRESSION_CD = 205,
    K_CUSTOM_COMPRESSION_CE = 206,
    K_CUSTOM_COMPRESSION_CF = 207,
    K_CUSTOM_COMPRESSION_D0 = 208,
    K_CUSTOM_COMPRESSION_D1 = 209,
    K_CUSTOM_COMPRESSION_D2 = 210,
    K_CUSTOM_COMPRESSION_D3 = 211,
    K_CUSTOM_COMPRESSION_D4 = 212,
    K_CUSTOM_COMPRESSION_D5 = 213,
    K_CUSTOM_COMPRESSION_D6 = 214,
    K_CUSTOM_COMPRESSION_D7 = 215,
    K_CUSTOM_COMPRESSION_D8 = 216,
    K_CUSTOM_COMPRESSION_D9 = 217,
    K_CUSTOM_COMPRESSION_DA = 218,
    K_CUSTOM_COMPRESSION_DB = 219,
    K_CUSTOM_COMPRESSION_DC = 220,
    K_CUSTOM_COMPRESSION_DD = 221,
    K_CUSTOM_COMPRESSION_DE = 222,
    K_CUSTOM_COMPRESSION_DF = 223,
    K_CUSTOM_COMPRESSION_E0 = 224,
    K_CUSTOM_COMPRESSION_E1 = 225,
    K_CUSTOM_COMPRESSION_E2 = 226,
    K_CUSTOM_COMPRESSION_E3 = 227,
    K_CUSTOM_COMPRESSION_E4 = 228,
    K_CUSTOM_COMPRESSION_E5 = 229,
    K_CUSTOM_COMPRESSION_E6 = 230,
    K_CUSTOM_COMPRESSION_E7 = 231,
    K_CUSTOM_COMPRESSION_E8 = 232,
    K_CUSTOM_COMPRESSION_E9 = 233,
    K_CUSTOM_COMPRESSION_EA = 234,
    K_CUSTOM_COMPRESSION_EB = 235,
    K_CUSTOM_COMPRESSION_EC = 236,
    K_CUSTOM_COMPRESSION_ED = 237,
    K_CUSTOM_COMPRESSION_EE = 238,
    K_CUSTOM_COMPRESSION_EF = 239,
    K_CUSTOM_COMPRESSION_F0 = 240,
    K_CUSTOM_COMPRESSION_F1 = 241,
    K_CUSTOM_COMPRESSION_F2 = 242,
    K_CUSTOM_COMPRESSION_F3 = 243,
    K_CUSTOM_COMPRESSION_F4 = 244,
    K_CUSTOM_COMPRESSION_F5 = 245,
    K_CUSTOM_COMPRESSION_F6 = 246,
    K_CUSTOM_COMPRESSION_F7 = 247,
    K_CUSTOM_COMPRESSION_F8 = 248,
    K_CUSTOM_COMPRESSION_F9 = 249,
    K_CUSTOM_COMPRESSION_FA = 250,
    K_CUSTOM_COMPRESSION_FB = 251,
    K_CUSTOM_COMPRESSION_FC = 252,
    K_CUSTOM_COMPRESSION_FD = 253,
    K_CUSTOM_COMPRESSION_FE = 254,
    K_LAST_CUSTOM_COMPRESSION = 254,
    K_DISABLE_COMPRESSION_OPTION = 255
  };  // 
  std::optional<CompressionType> parse_CompressionType(std::string_view value);

  /// --- messages --- 

  class  ReadOptions {
  public:

  static const google::protobuf::Descriptor* get_descriptor();

  ///  runtime identify for traits
  static constexpr bool is_runtime_type = true;

  using proto_type = granite::pb::ReadOptions;


  public:
    /// constructor
    ReadOptions();

    /// destructor
    ~ReadOptions();

    ReadOptions(const ReadOptions& rhs);

    ReadOptions& operator= (const ReadOptions& rhs);

    ReadOptions(ReadOptions&& rhs) noexcept;

    ReadOptions& operator= (ReadOptions&& rhs) noexcept;

    /// -----enums-------- 
  public:
    ////////////////////// getters/setters

    inline bool async_io() const;
    inline void async_io(bool value);
    ///////////////////////////////////////////////////////////////////////// 
    /// transfers 
    void parse_from_proto(const granite::pb::ReadOptions& pb);

    void serialize_to_proto(granite::pb::ReadOptions& pb) const;

    turbo::Status parse_from_json(const std::string& json);

    turbo::Status serialize_to_json(std::string& json) const;

    std::string to_string() const;


  //////////////////////////////////////////////////////////////////////
  /// members
  /// Keep members protected for inheritance and extension
  protected:
    bool _async_io{1};
    ////////////////////// unions
  };
  class  WriteOptions {
  public:

  static const google::protobuf::Descriptor* get_descriptor();

  ///  runtime identify for traits
  static constexpr bool is_runtime_type = true;

  using proto_type = granite::pb::WriteOptions;


  public:
    /// constructor
    WriteOptions();

    /// destructor
    ~WriteOptions();

    WriteOptions(const WriteOptions& rhs);

    WriteOptions& operator= (const WriteOptions& rhs);

    WriteOptions(WriteOptions&& rhs) noexcept;

    WriteOptions& operator= (WriteOptions&& rhs) noexcept;

    /// -----enums-------- 
  public:
    ////////////////////// getters/setters

    inline bool sync() const;
    inline void sync(bool value);
    inline bool disable_wal() const;
    inline void disable_wal(bool value);
    inline bool no_slowdown() const;
    inline void no_slowdown(bool value);
    inline bool low_pri() const;
    inline void low_pri(bool value);
    inline bool memtable_insert_hint_per_batch() const;
    inline void memtable_insert_hint_per_batch(bool value);
    inline int32_t write_batch_max_bytes() const;
    inline void write_batch_max_bytes(int32_t value);
    ///////////////////////////////////////////////////////////////////////// 
    /// transfers 
    void parse_from_proto(const granite::pb::WriteOptions& pb);

    void serialize_to_proto(granite::pb::WriteOptions& pb) const;

    turbo::Status parse_from_json(const std::string& json);

    turbo::Status serialize_to_json(std::string& json) const;

    std::string to_string() const;


  //////////////////////////////////////////////////////////////////////
  /// members
  /// Keep members protected for inheritance and extension
  protected:
    bool _sync{0};
    bool _disable_wal{0};
    bool _no_slowdown{0};
    bool _low_pri{0};
    bool _memtable_insert_hint_per_batch{0};
    int32_t _write_batch_max_bytes{0};
    ////////////////////// unions
  };
  class  RocksDBConfig {
  public:

  static const google::protobuf::Descriptor* get_descriptor();

  ///  runtime identify for traits
  static constexpr bool is_runtime_type = true;

  using proto_type = granite::pb::RocksDBConfig;


  public:
    /// constructor
    RocksDBConfig();

    /// destructor
    ~RocksDBConfig();

    RocksDBConfig(const RocksDBConfig& rhs);

    RocksDBConfig& operator= (const RocksDBConfig& rhs);

    RocksDBConfig(RocksDBConfig&& rhs) noexcept;

    RocksDBConfig& operator= (RocksDBConfig&& rhs) noexcept;

    /// -----enums-------- 
  public:
    ////////////////////// getters/setters

    inline int32_t block_size() const;
    inline void block_size(int32_t value);
    inline bool cache_index_and_filter_blocks() const;
    inline void cache_index_and_filter_blocks(bool value);
    inline int64_t block_cache_size() const;
    inline void block_cache_size(int64_t value);
    inline BlockCacheType block_cache_type() const;
    inline void set_block_cache_type(BlockCacheType value);
    inline int64_t metadata_block_cache_size() const;
    inline void metadata_block_cache_size(int64_t value);
    inline int64_t subkey_block_cache_size() const;
    inline void subkey_block_cache_size(int64_t value);
    inline bool share_metadata_and_subkey_block_cache() const;
    inline void share_metadata_and_subkey_block_cache(bool value);
    inline int32_t max_open_files() const;
    inline void max_open_files(int32_t value);
    inline int64_t write_buffer_size() const;
    inline void write_buffer_size(int64_t value);
    inline int32_t max_write_buffer_number() const;
    inline void max_write_buffer_number(int32_t value);
    inline int32_t min_write_buffer_number_to_merge() const;
    inline void min_write_buffer_number_to_merge(int32_t value);
    inline int32_t max_background_compactions() const;
    inline void max_background_compactions(int32_t value);
    inline int32_t max_background_flushes() const;
    inline void max_background_flushes(int32_t value);
    inline int32_t max_subcompactions() const;
    inline void max_subcompactions(int32_t value);
    inline int32_t stats_dump_period_sec() const;
    inline void stats_dump_period_sec(int32_t value);
    inline bool enable_pipelined_write() const;
    inline void enable_pipelined_write(bool value);
    inline int64_t delayed_write_rate() const;
    inline void delayed_write_rate(int64_t value);
    inline int32_t compaction_readahead_size() const;
    inline void compaction_readahead_size(int32_t value);
    inline int64_t target_file_size_base() const;
    inline void target_file_size_base(int64_t value);
    inline CompressionType wal_compression() const;
    inline void set_wal_compression(CompressionType value);
    inline int32_t wal_ttl_seconds() const;
    inline void wal_ttl_seconds(int32_t value);
    inline int32_t wal_size_limit_mb() const;
    inline void wal_size_limit_mb(int32_t value);
    inline int64_t max_total_wal_size() const;
    inline void max_total_wal_size(int64_t value);
    inline bool dump_malloc_stats() const;
    inline void dump_malloc_stats(bool value);
    inline int32_t level0_slowdown_writes_trigger() const;
    inline void level0_slowdown_writes_trigger(int32_t value);
    inline int32_t level0_stop_writes_trigger() const;
    inline void level0_stop_writes_trigger(int32_t value);
    inline int32_t level0_file_num_compaction_trigger() const;
    inline void level0_file_num_compaction_trigger(int32_t value);
    inline CompressionType compression() const;
    inline void set_compression(CompressionType value);
    inline int32_t compression_start_level() const;
    inline void compression_start_level(int32_t value);
    inline int32_t compression_level() const;
    inline void compression_level(int32_t value);
    inline uint32_t compression_max_dict_bytes() const;
    inline void compression_max_dict_bytes(uint32_t value);
    inline uint32_t compression_zstd_max_train_bytes() const;
    inline void compression_zstd_max_train_bytes(uint32_t value);
    inline bool disable_auto_compactions() const;
    inline void disable_auto_compactions(bool value);
    inline bool enable_blob_files() const;
    inline void enable_blob_files(bool value);
    inline int32_t min_blob_size() const;
    inline void min_blob_size(int32_t value);
    inline int32_t blob_file_size() const;
    inline void blob_file_size(int32_t value);
    inline bool enable_blob_garbage_collection() const;
    inline void enable_blob_garbage_collection(bool value);
    inline int32_t blob_garbage_collection_age_cutoff() const;
    inline void blob_garbage_collection_age_cutoff(int32_t value);
    inline uint64_t max_bytes_for_level_base() const;
    inline void max_bytes_for_level_base(uint64_t value);
    inline int32_t max_bytes_for_level_multiplier() const;
    inline void max_bytes_for_level_multiplier(int32_t value);
    inline bool level_compaction_dynamic_level_bytes() const;
    inline void level_compaction_dynamic_level_bytes(bool value);
    inline int32_t max_background_jobs() const;
    inline void max_background_jobs(int32_t value);
    inline bool rate_limiter_auto_tuned() const;
    inline void rate_limiter_auto_tuned(bool value);
    inline bool avoid_unnecessary_blocking_io() const;
    inline void avoid_unnecessary_blocking_io(bool value);
    inline bool partition_filters() const;
    inline void partition_filters(bool value);
    inline int64_t max_compaction_bytes() const;
    inline void max_compaction_bytes(int64_t value);
    inline int64_t sst_file_delete_rate_bytes_per_sec() const;
    inline void sst_file_delete_rate_bytes_per_sec(int64_t value);
    inline uint64_t periodic_compaction_seconds() const;
    inline void periodic_compaction_seconds(uint64_t value);
    inline uint64_t ttl() const;
    inline void ttl(uint64_t value);
    inline const std::string& daily_offpeak_time_utc() const;
    inline void set_daily_offpeak_time_utc(std::string v);
    inline const WriteOptions& write_options() const;
    inline void set_write_options(const WriteOptions& val);
    inline void set_write_options(WriteOptions&& val);
    inline const ReadOptions& read_options() const;
    inline void set_read_options(const ReadOptions& val);
    inline void set_read_options(ReadOptions&& val);
    ///////////////////////////////////////////////////////////////////////// 
    /// transfers 
    void parse_from_proto(const granite::pb::RocksDBConfig& pb);

    void serialize_to_proto(granite::pb::RocksDBConfig& pb) const;

    turbo::Status parse_from_json(const std::string& json);

    turbo::Status serialize_to_json(std::string& json) const;

    std::string to_string() const;


  //////////////////////////////////////////////////////////////////////
  /// members
  /// Keep members protected for inheritance and extension
  protected:
    int32_t _block_size{16384};
    bool _cache_index_and_filter_blocks{1};
    int64_t _block_cache_size{0ll};
    BlockCacheType _block_cache_type{BlockCacheType::LRU};
    int64_t _metadata_block_cache_size{2048ll};
    int64_t _subkey_block_cache_size{2048ll};
    bool _share_metadata_and_subkey_block_cache{1};
    int32_t _max_open_files{8096};
    int64_t _write_buffer_size{67108864ll};
    int32_t _max_write_buffer_number{4};
    int32_t _min_write_buffer_number_to_merge{1};
    int32_t _max_background_compactions{-1};
    int32_t _max_background_flushes{-1};
    int32_t _max_subcompactions{2};
    int32_t _stats_dump_period_sec{0};
    bool _enable_pipelined_write{0};
    int64_t _delayed_write_rate{0ll};
    int32_t _compaction_readahead_size{2097152};
    int64_t _target_file_size_base{134217728ll};
    CompressionType _wal_compression{CompressionType::K_NO_COMPRESSION};
    int32_t _wal_ttl_seconds{10800};
    int32_t _wal_size_limit_mb{16384};
    int64_t _max_total_wal_size{536870912ll};
    bool _dump_malloc_stats{1};
    int32_t _level0_slowdown_writes_trigger{20};
    int32_t _level0_stop_writes_trigger{40};
    int32_t _level0_file_num_compaction_trigger{4};
    CompressionType _compression{CompressionType::K_NO_COMPRESSION};
    int32_t _compression_start_level{2};
    int32_t _compression_level{32767};
    uint32_t _compression_max_dict_bytes{0u};
    uint32_t _compression_zstd_max_train_bytes{0u};
    bool _disable_auto_compactions{0};
    bool _enable_blob_files{0};
    int32_t _min_blob_size{4096};
    int32_t _blob_file_size{268435456};
    bool _enable_blob_garbage_collection{1};
    int32_t _blob_garbage_collection_age_cutoff{25};
    uint64_t _max_bytes_for_level_base{268435456ull};
    int32_t _max_bytes_for_level_multiplier{10};
    bool _level_compaction_dynamic_level_bytes{1};
    int32_t _max_background_jobs{4};
    bool _rate_limiter_auto_tuned{1};
    bool _avoid_unnecessary_blocking_io{1};
    bool _partition_filters{1};
    int64_t _max_compaction_bytes{0ll};
    int64_t _sst_file_delete_rate_bytes_per_sec{0ll};
    uint64_t _periodic_compaction_seconds{0ull};
    uint64_t _ttl{0ull};
    std::string _daily_offpeak_time_utc{""};
    WriteOptions _write_options;
    ReadOptions _read_options;
    ////////////////////// unions
  };
  class  Config {
  public:

  static const google::protobuf::Descriptor* get_descriptor();

  ///  runtime identify for traits
  static constexpr bool is_runtime_type = true;

  using proto_type = granite::pb::Config;


  public:
    /// constructor
    Config();

    /// destructor
    ~Config();

    Config(const Config& rhs);

    Config& operator= (const Config& rhs);

    Config(Config&& rhs) noexcept;

    Config& operator= (Config&& rhs) noexcept;

    /*
     * Main server configuration structure
 Matches your C++ Config struct 1:1

     */
    /// -----enums-------- 
  public:
    ////////////////////// getters/setters

    /*
     * Basic backup and retention settings

     */
    inline int32_t max_backup_to_keep() const;
    inline void max_backup_to_keep(int32_t value);
    inline int32_t max_backup_keep_hours() const;
    inline void max_backup_keep_hours(int32_t value);
    inline uint64_t proto_max_bulk_len() const;
    inline void proto_max_bulk_len(uint64_t value);
    inline int32_t max_db_size() const;
    inline void max_db_size(int32_t value);
    inline int32_t max_io_mb() const;
    inline void max_io_mb(int32_t value);
    inline bool enable_blob_cache() const;
    inline void enable_blob_cache(bool value);
    inline int32_t max_bitmap_to_string_mb() const;
    inline void max_bitmap_to_string_mb(int32_t value);
    inline bool use_rsid_psync() const;
    inline void use_rsid_psync(bool value);
    /*
     * Core directory paths

     */
    inline const std::string& dir() const;
    inline void set_dir(std::string v);
    inline const std::string& db_dir() const;
    inline void set_db_dir(std::string v);
    inline const std::string& backup_dir() const;
    inline void set_backup_dir(std::string v);
    inline const std::string& backup_sync_dir() const;
    inline void set_backup_sync_dir(std::string v);
    inline const std::string& checkpoint_dir() const;
    inline void set_checkpoint_dir(std::string v);
    inline const std::string& sync_checkpoint_dir() const;
    inline void set_sync_checkpoint_dir(std::string v);
    inline const std::string& db_name() const;
    inline void set_db_name(std::string v);
    /*
     * Cron schedule expressions

     */
    inline const std::string& compact_cron() const;
    inline void set_compact_cron(std::string v);
    inline const std::string& bgsave_cron() const;
    inline void set_bgsave_cron(std::string v);
    inline const std::string& dbsize_scan_cron() const;
    inline void set_dbsize_scan_cron(std::string v);
    inline const std::string& compaction_checker_cron() const;
    inline void set_compaction_checker_cron(std::string v);
    /*
     * Compaction policy

     */
    inline int64_t force_compact_file_age() const;
    inline void force_compact_file_age(int64_t value);
    inline int32_t force_compact_file_min_deleted_percentage() const;
    inline void force_compact_file_min_deleted_percentage(int32_t value);
    /*
     * Redis compatibility flags

     */
    inline bool redis_cursor_compatible() const;
    inline void redis_cursor_compatible(bool value);
    inline int32_t redis_databases() const;
    inline void redis_databases(int32_t value);
    inline bool resp3_enabled() const;
    inline void resp3_enabled(bool value);
    /*
     * Authentication tokens (loaded only, not persisted)

     */
    inline const turbo::flat_hash_map<std::string,std::string>& load_tokens() const;
    inline void set_load_tokens(const turbo::flat_hash_map<std::string,std::string> &v);
    /*
     * Profiling and sampling settings

     */
    inline int32_t profiling_sample_ratio() const;
    inline void profiling_sample_ratio(int32_t value);
    inline int32_t profiling_sample_record_threshold_ms() const;
    inline void profiling_sample_record_threshold_ms(int32_t value);
    inline int32_t profiling_sample_record_max_len() const;
    inline void profiling_sample_record_max_len(int32_t value);
    inline const std::vector<std::string>& profiling_sample_commands() const;
    inline std::vector<std::string>& mutable_profiling_sample_commands();
    inline bool profiling_sample_all_commands() const;
    inline void profiling_sample_all_commands(bool value);
    /*
     * JSON processing configuration

     */
    inline int32_t json_max_nesting_depth() const;
    inline void json_max_nesting_depth(int32_t value);
    inline JsonStorageFormat json_storage_format() const;
    inline void set_json_storage_format(JsonStorageFormat value);
    /*
     * Transaction context mode

     */
    inline bool txn_context_enabled() const;
    inline void txn_context_enabled(bool value);
    /*
     * Performance tuning flags

     */
    inline bool skip_block_cache_deallocation_on_close() const;
    inline void skip_block_cache_deallocation_on_close(bool value);
    /*
     * Histogram metrics bucket boundaries

     */
    inline const std::vector<double>& histogram_bucket_boundaries() const;
    inline std::vector<double>& mutable_histogram_bucket_boundaries();
    inline const RocksDBConfig& rocks_db() const;
    inline void set_rocks_db(const RocksDBConfig& val);
    inline void set_rocks_db(RocksDBConfig&& val);
    ///////////////////////////////////////////////////////////////////////// 
    /// transfers 
    void parse_from_proto(const granite::pb::Config& pb);

    void serialize_to_proto(granite::pb::Config& pb) const;

    turbo::Status parse_from_json(const std::string& json);

    turbo::Status serialize_to_json(std::string& json) const;

    std::string to_string() const;


  //////////////////////////////////////////////////////////////////////
  /// members
  /// Keep members protected for inheritance and extension
  protected:
    /*
     * Basic backup and retention settings

     */
    int32_t _max_backup_to_keep{1};
    int32_t _max_backup_keep_hours{24};
    uint64_t _proto_max_bulk_len{536870912ull};
    int32_t _max_db_size{0};
    int32_t _max_io_mb{0};
    bool _enable_blob_cache{0};
    int32_t _max_bitmap_to_string_mb{16};
    bool _use_rsid_psync{0};
    /*
     * Core directory paths

     */
    std::string _dir{"/tmp/granite"};
    std::string _db_dir{"/tmp/granite/db"};
    std::string _backup_dir{"/tmp/granite/backup"};
    std::string _backup_sync_dir{"/tmp/granite/backup_for_sync"};
    std::string _checkpoint_dir{"/tmp/granite/checkpoint"};
    std::string _sync_checkpoint_dir{"/tmp/granite/sync_checkpoint"};
    std::string _db_name{"change.me.db"};
    /*
     * Cron schedule expressions

     */
    std::string _compact_cron{""};
    std::string _bgsave_cron{""};
    std::string _dbsize_scan_cron{""};
    std::string _compaction_checker_cron{""};
    /*
     * Compaction policy

     */
    int64_t _force_compact_file_age{172800ll};
    int32_t _force_compact_file_min_deleted_percentage{10};
    /*
     * Redis compatibility flags

     */
    bool _redis_cursor_compatible{1};
    int32_t _redis_databases{0};
    bool _resp3_enabled{1};
    /*
     * Authentication tokens (loaded only, not persisted)

     */
    turbo::flat_hash_map<std::string,std::string> _load_tokens;
    /*
     * Profiling and sampling settings

     */
    int32_t _profiling_sample_ratio{0};
    int32_t _profiling_sample_record_threshold_ms{100};
    int32_t _profiling_sample_record_max_len{128};
    std::vector<std::string> _profiling_sample_commands;
    bool _profiling_sample_all_commands{0};
    /*
     * JSON processing configuration

     */
    int32_t _json_max_nesting_depth{1024};
    JsonStorageFormat _json_storage_format{JsonStorageFormat::JSON};
    /*
     * Transaction context mode

     */
    bool _txn_context_enabled{0};
    /*
     * Performance tuning flags

     */
    bool _skip_block_cache_deallocation_on_close{0};
    /*
     * Histogram metrics bucket boundaries

     */
    std::vector<double> _histogram_bucket_boundaries;
    RocksDBConfig _rocks_db;
    ////////////////////// unions
  };

  //////////////////////////////////

  ///  services


  ///////////////////////////////////////////////////////////
  inline std::string_view to_string(JsonStorageFormat value) {
    switch (value) {
      case JsonStorageFormat::JSON_DEFAULT: return "JSON_DEFAULT";
      case JsonStorageFormat::JSON: return "JSON";
      case JsonStorageFormat::CBOR: return "CBOR";
      default: return "UNKNOWN";
    }
  }
  inline std::string_view to_string(BlockCacheType value) {
    switch (value) {
      case BlockCacheType::LRU: return "LRU";
      case BlockCacheType::CLOCK: return "CLOCK";
      default: return "UNKNOWN";
    }
  }
  inline std::string_view to_string(CompressionType value) {
    switch (value) {
      case CompressionType::K_NO_COMPRESSION: return "K_NO_COMPRESSION";
      case CompressionType::K_SNAPPY_COMPRESSION: return "K_SNAPPY_COMPRESSION";
      case CompressionType::K_ZLIB_COMPRESSION: return "K_ZLIB_COMPRESSION";
      case CompressionType::K_BZIP2_COMPRESSION: return "K_BZIP2_COMPRESSION";
      case CompressionType::K_LZ4_COMPRESSION: return "K_LZ4_COMPRESSION";
      case CompressionType::K_LZ4HC_COMPRESSION: return "K_LZ4HC_COMPRESSION";
      case CompressionType::K_XPRESS_COMPRESSION: return "K_XPRESS_COMPRESSION";
      case CompressionType::K_ZSTD: return "K_ZSTD";
      case CompressionType::K_CUSTOM_COMPRESSION_80: return "K_CUSTOM_COMPRESSION_80";
      case CompressionType::K_CUSTOM_COMPRESSION_81: return "K_CUSTOM_COMPRESSION_81";
      case CompressionType::K_CUSTOM_COMPRESSION_82: return "K_CUSTOM_COMPRESSION_82";
      case CompressionType::K_CUSTOM_COMPRESSION_83: return "K_CUSTOM_COMPRESSION_83";
      case CompressionType::K_CUSTOM_COMPRESSION_84: return "K_CUSTOM_COMPRESSION_84";
      case CompressionType::K_CUSTOM_COMPRESSION_85: return "K_CUSTOM_COMPRESSION_85";
      case CompressionType::K_CUSTOM_COMPRESSION_86: return "K_CUSTOM_COMPRESSION_86";
      case CompressionType::K_CUSTOM_COMPRESSION_87: return "K_CUSTOM_COMPRESSION_87";
      case CompressionType::K_CUSTOM_COMPRESSION_88: return "K_CUSTOM_COMPRESSION_88";
      case CompressionType::K_CUSTOM_COMPRESSION_89: return "K_CUSTOM_COMPRESSION_89";
      case CompressionType::K_CUSTOM_COMPRESSION_8A: return "K_CUSTOM_COMPRESSION_8A";
      case CompressionType::K_CUSTOM_COMPRESSION_8B: return "K_CUSTOM_COMPRESSION_8B";
      case CompressionType::K_CUSTOM_COMPRESSION_8C: return "K_CUSTOM_COMPRESSION_8C";
      case CompressionType::K_CUSTOM_COMPRESSION_8D: return "K_CUSTOM_COMPRESSION_8D";
      case CompressionType::K_CUSTOM_COMPRESSION_8E: return "K_CUSTOM_COMPRESSION_8E";
      case CompressionType::K_CUSTOM_COMPRESSION_8F: return "K_CUSTOM_COMPRESSION_8F";
      case CompressionType::K_CUSTOM_COMPRESSION_90: return "K_CUSTOM_COMPRESSION_90";
      case CompressionType::K_CUSTOM_COMPRESSION_91: return "K_CUSTOM_COMPRESSION_91";
      case CompressionType::K_CUSTOM_COMPRESSION_92: return "K_CUSTOM_COMPRESSION_92";
      case CompressionType::K_CUSTOM_COMPRESSION_93: return "K_CUSTOM_COMPRESSION_93";
      case CompressionType::K_CUSTOM_COMPRESSION_94: return "K_CUSTOM_COMPRESSION_94";
      case CompressionType::K_CUSTOM_COMPRESSION_95: return "K_CUSTOM_COMPRESSION_95";
      case CompressionType::K_CUSTOM_COMPRESSION_96: return "K_CUSTOM_COMPRESSION_96";
      case CompressionType::K_CUSTOM_COMPRESSION_97: return "K_CUSTOM_COMPRESSION_97";
      case CompressionType::K_CUSTOM_COMPRESSION_98: return "K_CUSTOM_COMPRESSION_98";
      case CompressionType::K_CUSTOM_COMPRESSION_99: return "K_CUSTOM_COMPRESSION_99";
      case CompressionType::K_CUSTOM_COMPRESSION_9A: return "K_CUSTOM_COMPRESSION_9A";
      case CompressionType::K_CUSTOM_COMPRESSION_9B: return "K_CUSTOM_COMPRESSION_9B";
      case CompressionType::K_CUSTOM_COMPRESSION_9C: return "K_CUSTOM_COMPRESSION_9C";
      case CompressionType::K_CUSTOM_COMPRESSION_9D: return "K_CUSTOM_COMPRESSION_9D";
      case CompressionType::K_CUSTOM_COMPRESSION_9E: return "K_CUSTOM_COMPRESSION_9E";
      case CompressionType::K_CUSTOM_COMPRESSION_9F: return "K_CUSTOM_COMPRESSION_9F";
      case CompressionType::K_CUSTOM_COMPRESSION_A0: return "K_CUSTOM_COMPRESSION_A0";
      case CompressionType::K_CUSTOM_COMPRESSION_A1: return "K_CUSTOM_COMPRESSION_A1";
      case CompressionType::K_CUSTOM_COMPRESSION_A2: return "K_CUSTOM_COMPRESSION_A2";
      case CompressionType::K_CUSTOM_COMPRESSION_A3: return "K_CUSTOM_COMPRESSION_A3";
      case CompressionType::K_CUSTOM_COMPRESSION_A4: return "K_CUSTOM_COMPRESSION_A4";
      case CompressionType::K_CUSTOM_COMPRESSION_A5: return "K_CUSTOM_COMPRESSION_A5";
      case CompressionType::K_CUSTOM_COMPRESSION_A6: return "K_CUSTOM_COMPRESSION_A6";
      case CompressionType::K_CUSTOM_COMPRESSION_A7: return "K_CUSTOM_COMPRESSION_A7";
      case CompressionType::K_CUSTOM_COMPRESSION_A8: return "K_CUSTOM_COMPRESSION_A8";
      case CompressionType::K_CUSTOM_COMPRESSION_A9: return "K_CUSTOM_COMPRESSION_A9";
      case CompressionType::K_CUSTOM_COMPRESSION_AA: return "K_CUSTOM_COMPRESSION_AA";
      case CompressionType::K_CUSTOM_COMPRESSION_AB: return "K_CUSTOM_COMPRESSION_AB";
      case CompressionType::K_CUSTOM_COMPRESSION_AC: return "K_CUSTOM_COMPRESSION_AC";
      case CompressionType::K_CUSTOM_COMPRESSION_AD: return "K_CUSTOM_COMPRESSION_AD";
      case CompressionType::K_CUSTOM_COMPRESSION_AE: return "K_CUSTOM_COMPRESSION_AE";
      case CompressionType::K_CUSTOM_COMPRESSION_AF: return "K_CUSTOM_COMPRESSION_AF";
      case CompressionType::K_CUSTOM_COMPRESSION_B0: return "K_CUSTOM_COMPRESSION_B0";
      case CompressionType::K_CUSTOM_COMPRESSION_B1: return "K_CUSTOM_COMPRESSION_B1";
      case CompressionType::K_CUSTOM_COMPRESSION_B2: return "K_CUSTOM_COMPRESSION_B2";
      case CompressionType::K_CUSTOM_COMPRESSION_B3: return "K_CUSTOM_COMPRESSION_B3";
      case CompressionType::K_CUSTOM_COMPRESSION_B4: return "K_CUSTOM_COMPRESSION_B4";
      case CompressionType::K_CUSTOM_COMPRESSION_B5: return "K_CUSTOM_COMPRESSION_B5";
      case CompressionType::K_CUSTOM_COMPRESSION_B6: return "K_CUSTOM_COMPRESSION_B6";
      case CompressionType::K_CUSTOM_COMPRESSION_B7: return "K_CUSTOM_COMPRESSION_B7";
      case CompressionType::K_CUSTOM_COMPRESSION_B8: return "K_CUSTOM_COMPRESSION_B8";
      case CompressionType::K_CUSTOM_COMPRESSION_B9: return "K_CUSTOM_COMPRESSION_B9";
      case CompressionType::K_CUSTOM_COMPRESSION_BA: return "K_CUSTOM_COMPRESSION_BA";
      case CompressionType::K_CUSTOM_COMPRESSION_BB: return "K_CUSTOM_COMPRESSION_BB";
      case CompressionType::K_CUSTOM_COMPRESSION_BC: return "K_CUSTOM_COMPRESSION_BC";
      case CompressionType::K_CUSTOM_COMPRESSION_BD: return "K_CUSTOM_COMPRESSION_BD";
      case CompressionType::K_CUSTOM_COMPRESSION_BE: return "K_CUSTOM_COMPRESSION_BE";
      case CompressionType::K_CUSTOM_COMPRESSION_BF: return "K_CUSTOM_COMPRESSION_BF";
      case CompressionType::K_CUSTOM_COMPRESSION_C0: return "K_CUSTOM_COMPRESSION_C0";
      case CompressionType::K_CUSTOM_COMPRESSION_C1: return "K_CUSTOM_COMPRESSION_C1";
      case CompressionType::K_CUSTOM_COMPRESSION_C2: return "K_CUSTOM_COMPRESSION_C2";
      case CompressionType::K_CUSTOM_COMPRESSION_C3: return "K_CUSTOM_COMPRESSION_C3";
      case CompressionType::K_CUSTOM_COMPRESSION_C4: return "K_CUSTOM_COMPRESSION_C4";
      case CompressionType::K_CUSTOM_COMPRESSION_C5: return "K_CUSTOM_COMPRESSION_C5";
      case CompressionType::K_CUSTOM_COMPRESSION_C6: return "K_CUSTOM_COMPRESSION_C6";
      case CompressionType::K_CUSTOM_COMPRESSION_C7: return "K_CUSTOM_COMPRESSION_C7";
      case CompressionType::K_CUSTOM_COMPRESSION_C8: return "K_CUSTOM_COMPRESSION_C8";
      case CompressionType::K_CUSTOM_COMPRESSION_C9: return "K_CUSTOM_COMPRESSION_C9";
      case CompressionType::K_CUSTOM_COMPRESSION_CA: return "K_CUSTOM_COMPRESSION_CA";
      case CompressionType::K_CUSTOM_COMPRESSION_CB: return "K_CUSTOM_COMPRESSION_CB";
      case CompressionType::K_CUSTOM_COMPRESSION_CC: return "K_CUSTOM_COMPRESSION_CC";
      case CompressionType::K_CUSTOM_COMPRESSION_CD: return "K_CUSTOM_COMPRESSION_CD";
      case CompressionType::K_CUSTOM_COMPRESSION_CE: return "K_CUSTOM_COMPRESSION_CE";
      case CompressionType::K_CUSTOM_COMPRESSION_CF: return "K_CUSTOM_COMPRESSION_CF";
      case CompressionType::K_CUSTOM_COMPRESSION_D0: return "K_CUSTOM_COMPRESSION_D0";
      case CompressionType::K_CUSTOM_COMPRESSION_D1: return "K_CUSTOM_COMPRESSION_D1";
      case CompressionType::K_CUSTOM_COMPRESSION_D2: return "K_CUSTOM_COMPRESSION_D2";
      case CompressionType::K_CUSTOM_COMPRESSION_D3: return "K_CUSTOM_COMPRESSION_D3";
      case CompressionType::K_CUSTOM_COMPRESSION_D4: return "K_CUSTOM_COMPRESSION_D4";
      case CompressionType::K_CUSTOM_COMPRESSION_D5: return "K_CUSTOM_COMPRESSION_D5";
      case CompressionType::K_CUSTOM_COMPRESSION_D6: return "K_CUSTOM_COMPRESSION_D6";
      case CompressionType::K_CUSTOM_COMPRESSION_D7: return "K_CUSTOM_COMPRESSION_D7";
      case CompressionType::K_CUSTOM_COMPRESSION_D8: return "K_CUSTOM_COMPRESSION_D8";
      case CompressionType::K_CUSTOM_COMPRESSION_D9: return "K_CUSTOM_COMPRESSION_D9";
      case CompressionType::K_CUSTOM_COMPRESSION_DA: return "K_CUSTOM_COMPRESSION_DA";
      case CompressionType::K_CUSTOM_COMPRESSION_DB: return "K_CUSTOM_COMPRESSION_DB";
      case CompressionType::K_CUSTOM_COMPRESSION_DC: return "K_CUSTOM_COMPRESSION_DC";
      case CompressionType::K_CUSTOM_COMPRESSION_DD: return "K_CUSTOM_COMPRESSION_DD";
      case CompressionType::K_CUSTOM_COMPRESSION_DE: return "K_CUSTOM_COMPRESSION_DE";
      case CompressionType::K_CUSTOM_COMPRESSION_DF: return "K_CUSTOM_COMPRESSION_DF";
      case CompressionType::K_CUSTOM_COMPRESSION_E0: return "K_CUSTOM_COMPRESSION_E0";
      case CompressionType::K_CUSTOM_COMPRESSION_E1: return "K_CUSTOM_COMPRESSION_E1";
      case CompressionType::K_CUSTOM_COMPRESSION_E2: return "K_CUSTOM_COMPRESSION_E2";
      case CompressionType::K_CUSTOM_COMPRESSION_E3: return "K_CUSTOM_COMPRESSION_E3";
      case CompressionType::K_CUSTOM_COMPRESSION_E4: return "K_CUSTOM_COMPRESSION_E4";
      case CompressionType::K_CUSTOM_COMPRESSION_E5: return "K_CUSTOM_COMPRESSION_E5";
      case CompressionType::K_CUSTOM_COMPRESSION_E6: return "K_CUSTOM_COMPRESSION_E6";
      case CompressionType::K_CUSTOM_COMPRESSION_E7: return "K_CUSTOM_COMPRESSION_E7";
      case CompressionType::K_CUSTOM_COMPRESSION_E8: return "K_CUSTOM_COMPRESSION_E8";
      case CompressionType::K_CUSTOM_COMPRESSION_E9: return "K_CUSTOM_COMPRESSION_E9";
      case CompressionType::K_CUSTOM_COMPRESSION_EA: return "K_CUSTOM_COMPRESSION_EA";
      case CompressionType::K_CUSTOM_COMPRESSION_EB: return "K_CUSTOM_COMPRESSION_EB";
      case CompressionType::K_CUSTOM_COMPRESSION_EC: return "K_CUSTOM_COMPRESSION_EC";
      case CompressionType::K_CUSTOM_COMPRESSION_ED: return "K_CUSTOM_COMPRESSION_ED";
      case CompressionType::K_CUSTOM_COMPRESSION_EE: return "K_CUSTOM_COMPRESSION_EE";
      case CompressionType::K_CUSTOM_COMPRESSION_EF: return "K_CUSTOM_COMPRESSION_EF";
      case CompressionType::K_CUSTOM_COMPRESSION_F0: return "K_CUSTOM_COMPRESSION_F0";
      case CompressionType::K_CUSTOM_COMPRESSION_F1: return "K_CUSTOM_COMPRESSION_F1";
      case CompressionType::K_CUSTOM_COMPRESSION_F2: return "K_CUSTOM_COMPRESSION_F2";
      case CompressionType::K_CUSTOM_COMPRESSION_F3: return "K_CUSTOM_COMPRESSION_F3";
      case CompressionType::K_CUSTOM_COMPRESSION_F4: return "K_CUSTOM_COMPRESSION_F4";
      case CompressionType::K_CUSTOM_COMPRESSION_F5: return "K_CUSTOM_COMPRESSION_F5";
      case CompressionType::K_CUSTOM_COMPRESSION_F6: return "K_CUSTOM_COMPRESSION_F6";
      case CompressionType::K_CUSTOM_COMPRESSION_F7: return "K_CUSTOM_COMPRESSION_F7";
      case CompressionType::K_CUSTOM_COMPRESSION_F8: return "K_CUSTOM_COMPRESSION_F8";
      case CompressionType::K_CUSTOM_COMPRESSION_F9: return "K_CUSTOM_COMPRESSION_F9";
      case CompressionType::K_CUSTOM_COMPRESSION_FA: return "K_CUSTOM_COMPRESSION_FA";
      case CompressionType::K_CUSTOM_COMPRESSION_FB: return "K_CUSTOM_COMPRESSION_FB";
      case CompressionType::K_CUSTOM_COMPRESSION_FC: return "K_CUSTOM_COMPRESSION_FC";
      case CompressionType::K_CUSTOM_COMPRESSION_FD: return "K_CUSTOM_COMPRESSION_FD";
      case CompressionType::K_CUSTOM_COMPRESSION_FE: return "K_CUSTOM_COMPRESSION_FE";
      case CompressionType::K_DISABLE_COMPRESSION_OPTION: return "K_DISABLE_COMPRESSION_OPTION";
      default: return "UNKNOWN";
    }
  }
  inline bool ReadOptions::async_io() const {
    return _async_io;
  }
  inline void ReadOptions::async_io(bool value) {
    _async_io = value;
  }
  inline bool WriteOptions::sync() const {
    return _sync;
  }
  inline void WriteOptions::sync(bool value) {
    _sync = value;
  }
  inline bool WriteOptions::disable_wal() const {
    return _disable_wal;
  }
  inline void WriteOptions::disable_wal(bool value) {
    _disable_wal = value;
  }
  inline bool WriteOptions::no_slowdown() const {
    return _no_slowdown;
  }
  inline void WriteOptions::no_slowdown(bool value) {
    _no_slowdown = value;
  }
  inline bool WriteOptions::low_pri() const {
    return _low_pri;
  }
  inline void WriteOptions::low_pri(bool value) {
    _low_pri = value;
  }
  inline bool WriteOptions::memtable_insert_hint_per_batch() const {
    return _memtable_insert_hint_per_batch;
  }
  inline void WriteOptions::memtable_insert_hint_per_batch(bool value) {
    _memtable_insert_hint_per_batch = value;
  }
  inline int32_t WriteOptions::write_batch_max_bytes() const {
    return _write_batch_max_bytes;
  }
  inline void WriteOptions::write_batch_max_bytes(int32_t value) {
    _write_batch_max_bytes = value;
  }
  inline int32_t RocksDBConfig::block_size() const {
    return _block_size;
  }
  inline void RocksDBConfig::block_size(int32_t value) {
    _block_size = value;
  }
  inline bool RocksDBConfig::cache_index_and_filter_blocks() const {
    return _cache_index_and_filter_blocks;
  }
  inline void RocksDBConfig::cache_index_and_filter_blocks(bool value) {
    _cache_index_and_filter_blocks = value;
  }
  inline int64_t RocksDBConfig::block_cache_size() const {
    return _block_cache_size;
  }
  inline void RocksDBConfig::block_cache_size(int64_t value) {
    _block_cache_size = value;
  }
  inline BlockCacheType RocksDBConfig::block_cache_type() const {
    return _block_cache_type;
  }
  inline void RocksDBConfig::set_block_cache_type(BlockCacheType value) {
    _block_cache_type = value;
  }
  inline int64_t RocksDBConfig::metadata_block_cache_size() const {
    return _metadata_block_cache_size;
  }
  inline void RocksDBConfig::metadata_block_cache_size(int64_t value) {
    _metadata_block_cache_size = value;
  }
  inline int64_t RocksDBConfig::subkey_block_cache_size() const {
    return _subkey_block_cache_size;
  }
  inline void RocksDBConfig::subkey_block_cache_size(int64_t value) {
    _subkey_block_cache_size = value;
  }
  inline bool RocksDBConfig::share_metadata_and_subkey_block_cache() const {
    return _share_metadata_and_subkey_block_cache;
  }
  inline void RocksDBConfig::share_metadata_and_subkey_block_cache(bool value) {
    _share_metadata_and_subkey_block_cache = value;
  }
  inline int32_t RocksDBConfig::max_open_files() const {
    return _max_open_files;
  }
  inline void RocksDBConfig::max_open_files(int32_t value) {
    _max_open_files = value;
  }
  inline int64_t RocksDBConfig::write_buffer_size() const {
    return _write_buffer_size;
  }
  inline void RocksDBConfig::write_buffer_size(int64_t value) {
    _write_buffer_size = value;
  }
  inline int32_t RocksDBConfig::max_write_buffer_number() const {
    return _max_write_buffer_number;
  }
  inline void RocksDBConfig::max_write_buffer_number(int32_t value) {
    _max_write_buffer_number = value;
  }
  inline int32_t RocksDBConfig::min_write_buffer_number_to_merge() const {
    return _min_write_buffer_number_to_merge;
  }
  inline void RocksDBConfig::min_write_buffer_number_to_merge(int32_t value) {
    _min_write_buffer_number_to_merge = value;
  }
  inline int32_t RocksDBConfig::max_background_compactions() const {
    return _max_background_compactions;
  }
  inline void RocksDBConfig::max_background_compactions(int32_t value) {
    _max_background_compactions = value;
  }
  inline int32_t RocksDBConfig::max_background_flushes() const {
    return _max_background_flushes;
  }
  inline void RocksDBConfig::max_background_flushes(int32_t value) {
    _max_background_flushes = value;
  }
  inline int32_t RocksDBConfig::max_subcompactions() const {
    return _max_subcompactions;
  }
  inline void RocksDBConfig::max_subcompactions(int32_t value) {
    _max_subcompactions = value;
  }
  inline int32_t RocksDBConfig::stats_dump_period_sec() const {
    return _stats_dump_period_sec;
  }
  inline void RocksDBConfig::stats_dump_period_sec(int32_t value) {
    _stats_dump_period_sec = value;
  }
  inline bool RocksDBConfig::enable_pipelined_write() const {
    return _enable_pipelined_write;
  }
  inline void RocksDBConfig::enable_pipelined_write(bool value) {
    _enable_pipelined_write = value;
  }
  inline int64_t RocksDBConfig::delayed_write_rate() const {
    return _delayed_write_rate;
  }
  inline void RocksDBConfig::delayed_write_rate(int64_t value) {
    _delayed_write_rate = value;
  }
  inline int32_t RocksDBConfig::compaction_readahead_size() const {
    return _compaction_readahead_size;
  }
  inline void RocksDBConfig::compaction_readahead_size(int32_t value) {
    _compaction_readahead_size = value;
  }
  inline int64_t RocksDBConfig::target_file_size_base() const {
    return _target_file_size_base;
  }
  inline void RocksDBConfig::target_file_size_base(int64_t value) {
    _target_file_size_base = value;
  }
  inline CompressionType RocksDBConfig::wal_compression() const {
    return _wal_compression;
  }
  inline void RocksDBConfig::set_wal_compression(CompressionType value) {
    _wal_compression = value;
  }
  inline int32_t RocksDBConfig::wal_ttl_seconds() const {
    return _wal_ttl_seconds;
  }
  inline void RocksDBConfig::wal_ttl_seconds(int32_t value) {
    _wal_ttl_seconds = value;
  }
  inline int32_t RocksDBConfig::wal_size_limit_mb() const {
    return _wal_size_limit_mb;
  }
  inline void RocksDBConfig::wal_size_limit_mb(int32_t value) {
    _wal_size_limit_mb = value;
  }
  inline int64_t RocksDBConfig::max_total_wal_size() const {
    return _max_total_wal_size;
  }
  inline void RocksDBConfig::max_total_wal_size(int64_t value) {
    _max_total_wal_size = value;
  }
  inline bool RocksDBConfig::dump_malloc_stats() const {
    return _dump_malloc_stats;
  }
  inline void RocksDBConfig::dump_malloc_stats(bool value) {
    _dump_malloc_stats = value;
  }
  inline int32_t RocksDBConfig::level0_slowdown_writes_trigger() const {
    return _level0_slowdown_writes_trigger;
  }
  inline void RocksDBConfig::level0_slowdown_writes_trigger(int32_t value) {
    _level0_slowdown_writes_trigger = value;
  }
  inline int32_t RocksDBConfig::level0_stop_writes_trigger() const {
    return _level0_stop_writes_trigger;
  }
  inline void RocksDBConfig::level0_stop_writes_trigger(int32_t value) {
    _level0_stop_writes_trigger = value;
  }
  inline int32_t RocksDBConfig::level0_file_num_compaction_trigger() const {
    return _level0_file_num_compaction_trigger;
  }
  inline void RocksDBConfig::level0_file_num_compaction_trigger(int32_t value) {
    _level0_file_num_compaction_trigger = value;
  }
  inline CompressionType RocksDBConfig::compression() const {
    return _compression;
  }
  inline void RocksDBConfig::set_compression(CompressionType value) {
    _compression = value;
  }
  inline int32_t RocksDBConfig::compression_start_level() const {
    return _compression_start_level;
  }
  inline void RocksDBConfig::compression_start_level(int32_t value) {
    _compression_start_level = value;
  }
  inline int32_t RocksDBConfig::compression_level() const {
    return _compression_level;
  }
  inline void RocksDBConfig::compression_level(int32_t value) {
    _compression_level = value;
  }
  inline uint32_t RocksDBConfig::compression_max_dict_bytes() const {
    return _compression_max_dict_bytes;
  }
  inline void RocksDBConfig::compression_max_dict_bytes(uint32_t value) {
    _compression_max_dict_bytes = value;
  }
  inline uint32_t RocksDBConfig::compression_zstd_max_train_bytes() const {
    return _compression_zstd_max_train_bytes;
  }
  inline void RocksDBConfig::compression_zstd_max_train_bytes(uint32_t value) {
    _compression_zstd_max_train_bytes = value;
  }
  inline bool RocksDBConfig::disable_auto_compactions() const {
    return _disable_auto_compactions;
  }
  inline void RocksDBConfig::disable_auto_compactions(bool value) {
    _disable_auto_compactions = value;
  }
  inline bool RocksDBConfig::enable_blob_files() const {
    return _enable_blob_files;
  }
  inline void RocksDBConfig::enable_blob_files(bool value) {
    _enable_blob_files = value;
  }
  inline int32_t RocksDBConfig::min_blob_size() const {
    return _min_blob_size;
  }
  inline void RocksDBConfig::min_blob_size(int32_t value) {
    _min_blob_size = value;
  }
  inline int32_t RocksDBConfig::blob_file_size() const {
    return _blob_file_size;
  }
  inline void RocksDBConfig::blob_file_size(int32_t value) {
    _blob_file_size = value;
  }
  inline bool RocksDBConfig::enable_blob_garbage_collection() const {
    return _enable_blob_garbage_collection;
  }
  inline void RocksDBConfig::enable_blob_garbage_collection(bool value) {
    _enable_blob_garbage_collection = value;
  }
  inline int32_t RocksDBConfig::blob_garbage_collection_age_cutoff() const {
    return _blob_garbage_collection_age_cutoff;
  }
  inline void RocksDBConfig::blob_garbage_collection_age_cutoff(int32_t value) {
    _blob_garbage_collection_age_cutoff = value;
  }
  inline uint64_t RocksDBConfig::max_bytes_for_level_base() const {
    return _max_bytes_for_level_base;
  }
  inline void RocksDBConfig::max_bytes_for_level_base(uint64_t value) {
    _max_bytes_for_level_base = value;
  }
  inline int32_t RocksDBConfig::max_bytes_for_level_multiplier() const {
    return _max_bytes_for_level_multiplier;
  }
  inline void RocksDBConfig::max_bytes_for_level_multiplier(int32_t value) {
    _max_bytes_for_level_multiplier = value;
  }
  inline bool RocksDBConfig::level_compaction_dynamic_level_bytes() const {
    return _level_compaction_dynamic_level_bytes;
  }
  inline void RocksDBConfig::level_compaction_dynamic_level_bytes(bool value) {
    _level_compaction_dynamic_level_bytes = value;
  }
  inline int32_t RocksDBConfig::max_background_jobs() const {
    return _max_background_jobs;
  }
  inline void RocksDBConfig::max_background_jobs(int32_t value) {
    _max_background_jobs = value;
  }
  inline bool RocksDBConfig::rate_limiter_auto_tuned() const {
    return _rate_limiter_auto_tuned;
  }
  inline void RocksDBConfig::rate_limiter_auto_tuned(bool value) {
    _rate_limiter_auto_tuned = value;
  }
  inline bool RocksDBConfig::avoid_unnecessary_blocking_io() const {
    return _avoid_unnecessary_blocking_io;
  }
  inline void RocksDBConfig::avoid_unnecessary_blocking_io(bool value) {
    _avoid_unnecessary_blocking_io = value;
  }
  inline bool RocksDBConfig::partition_filters() const {
    return _partition_filters;
  }
  inline void RocksDBConfig::partition_filters(bool value) {
    _partition_filters = value;
  }
  inline int64_t RocksDBConfig::max_compaction_bytes() const {
    return _max_compaction_bytes;
  }
  inline void RocksDBConfig::max_compaction_bytes(int64_t value) {
    _max_compaction_bytes = value;
  }
  inline int64_t RocksDBConfig::sst_file_delete_rate_bytes_per_sec() const {
    return _sst_file_delete_rate_bytes_per_sec;
  }
  inline void RocksDBConfig::sst_file_delete_rate_bytes_per_sec(int64_t value) {
    _sst_file_delete_rate_bytes_per_sec = value;
  }
  inline uint64_t RocksDBConfig::periodic_compaction_seconds() const {
    return _periodic_compaction_seconds;
  }
  inline void RocksDBConfig::periodic_compaction_seconds(uint64_t value) {
    _periodic_compaction_seconds = value;
  }
  inline uint64_t RocksDBConfig::ttl() const {
    return _ttl;
  }
  inline void RocksDBConfig::ttl(uint64_t value) {
    _ttl = value;
  }
  /// getter
  inline const std::string& RocksDBConfig::daily_offpeak_time_utc() const {
    return _daily_offpeak_time_utc;
  }
  /// setter
  inline void RocksDBConfig::set_daily_offpeak_time_utc(std::string v) {
    _daily_offpeak_time_utc = std::move(v);
  }
  inline const WriteOptions& RocksDBConfig::write_options() const {
    return _write_options;
  }
  inline void RocksDBConfig::set_write_options(const WriteOptions& val) {
    _write_options = val;
  }
  inline void RocksDBConfig::set_write_options(WriteOptions&& val) {
    _write_options = std::move(val);
  }
  inline const ReadOptions& RocksDBConfig::read_options() const {
    return _read_options;
  }
  inline void RocksDBConfig::set_read_options(const ReadOptions& val) {
    _read_options = val;
  }
  inline void RocksDBConfig::set_read_options(ReadOptions&& val) {
    _read_options = std::move(val);
  }
  /*
   * Basic backup and retention settings

   */
  inline int32_t Config::max_backup_to_keep() const {
    return _max_backup_to_keep;
  }
  inline void Config::max_backup_to_keep(int32_t value) {
    _max_backup_to_keep = value;
  }
  inline int32_t Config::max_backup_keep_hours() const {
    return _max_backup_keep_hours;
  }
  inline void Config::max_backup_keep_hours(int32_t value) {
    _max_backup_keep_hours = value;
  }
  inline uint64_t Config::proto_max_bulk_len() const {
    return _proto_max_bulk_len;
  }
  inline void Config::proto_max_bulk_len(uint64_t value) {
    _proto_max_bulk_len = value;
  }
  inline int32_t Config::max_db_size() const {
    return _max_db_size;
  }
  inline void Config::max_db_size(int32_t value) {
    _max_db_size = value;
  }
  inline int32_t Config::max_io_mb() const {
    return _max_io_mb;
  }
  inline void Config::max_io_mb(int32_t value) {
    _max_io_mb = value;
  }
  inline bool Config::enable_blob_cache() const {
    return _enable_blob_cache;
  }
  inline void Config::enable_blob_cache(bool value) {
    _enable_blob_cache = value;
  }
  inline int32_t Config::max_bitmap_to_string_mb() const {
    return _max_bitmap_to_string_mb;
  }
  inline void Config::max_bitmap_to_string_mb(int32_t value) {
    _max_bitmap_to_string_mb = value;
  }
  inline bool Config::use_rsid_psync() const {
    return _use_rsid_psync;
  }
  inline void Config::use_rsid_psync(bool value) {
    _use_rsid_psync = value;
  }
  /*
   * Core directory paths

   */
  /// getter
  inline const std::string& Config::dir() const {
    return _dir;
  }
  /// setter
  inline void Config::set_dir(std::string v) {
    _dir = std::move(v);
  }
  /// getter
  inline const std::string& Config::db_dir() const {
    return _db_dir;
  }
  /// setter
  inline void Config::set_db_dir(std::string v) {
    _db_dir = std::move(v);
  }
  /// getter
  inline const std::string& Config::backup_dir() const {
    return _backup_dir;
  }
  /// setter
  inline void Config::set_backup_dir(std::string v) {
    _backup_dir = std::move(v);
  }
  /// getter
  inline const std::string& Config::backup_sync_dir() const {
    return _backup_sync_dir;
  }
  /// setter
  inline void Config::set_backup_sync_dir(std::string v) {
    _backup_sync_dir = std::move(v);
  }
  /// getter
  inline const std::string& Config::checkpoint_dir() const {
    return _checkpoint_dir;
  }
  /// setter
  inline void Config::set_checkpoint_dir(std::string v) {
    _checkpoint_dir = std::move(v);
  }
  /// getter
  inline const std::string& Config::sync_checkpoint_dir() const {
    return _sync_checkpoint_dir;
  }
  /// setter
  inline void Config::set_sync_checkpoint_dir(std::string v) {
    _sync_checkpoint_dir = std::move(v);
  }
  /// getter
  inline const std::string& Config::db_name() const {
    return _db_name;
  }
  /// setter
  inline void Config::set_db_name(std::string v) {
    _db_name = std::move(v);
  }
  /*
   * Cron schedule expressions

   */
  /// getter
  inline const std::string& Config::compact_cron() const {
    return _compact_cron;
  }
  /// setter
  inline void Config::set_compact_cron(std::string v) {
    _compact_cron = std::move(v);
  }
  /// getter
  inline const std::string& Config::bgsave_cron() const {
    return _bgsave_cron;
  }
  /// setter
  inline void Config::set_bgsave_cron(std::string v) {
    _bgsave_cron = std::move(v);
  }
  /// getter
  inline const std::string& Config::dbsize_scan_cron() const {
    return _dbsize_scan_cron;
  }
  /// setter
  inline void Config::set_dbsize_scan_cron(std::string v) {
    _dbsize_scan_cron = std::move(v);
  }
  /// getter
  inline const std::string& Config::compaction_checker_cron() const {
    return _compaction_checker_cron;
  }
  /// setter
  inline void Config::set_compaction_checker_cron(std::string v) {
    _compaction_checker_cron = std::move(v);
  }
  /*
   * Compaction policy

   */
  inline int64_t Config::force_compact_file_age() const {
    return _force_compact_file_age;
  }
  inline void Config::force_compact_file_age(int64_t value) {
    _force_compact_file_age = value;
  }
  inline int32_t Config::force_compact_file_min_deleted_percentage() const {
    return _force_compact_file_min_deleted_percentage;
  }
  inline void Config::force_compact_file_min_deleted_percentage(int32_t value) {
    _force_compact_file_min_deleted_percentage = value;
  }
  /*
   * Redis compatibility flags

   */
  inline bool Config::redis_cursor_compatible() const {
    return _redis_cursor_compatible;
  }
  inline void Config::redis_cursor_compatible(bool value) {
    _redis_cursor_compatible = value;
  }
  inline int32_t Config::redis_databases() const {
    return _redis_databases;
  }
  inline void Config::redis_databases(int32_t value) {
    _redis_databases = value;
  }
  inline bool Config::resp3_enabled() const {
    return _resp3_enabled;
  }
  inline void Config::resp3_enabled(bool value) {
    _resp3_enabled = value;
  }
  /*
   * Authentication tokens (loaded only, not persisted)

   */
  /// getter
  inline const turbo::flat_hash_map<std::string,std::string>& Config::load_tokens() const {
    return _load_tokens;
  }
  /// setter
  inline void Config::set_load_tokens(const turbo::flat_hash_map<std::string,std::string> &v) {
    _load_tokens = v;
  }
  /*
   * Profiling and sampling settings

   */
  inline int32_t Config::profiling_sample_ratio() const {
    return _profiling_sample_ratio;
  }
  inline void Config::profiling_sample_ratio(int32_t value) {
    _profiling_sample_ratio = value;
  }
  inline int32_t Config::profiling_sample_record_threshold_ms() const {
    return _profiling_sample_record_threshold_ms;
  }
  inline void Config::profiling_sample_record_threshold_ms(int32_t value) {
    _profiling_sample_record_threshold_ms = value;
  }
  inline int32_t Config::profiling_sample_record_max_len() const {
    return _profiling_sample_record_max_len;
  }
  inline void Config::profiling_sample_record_max_len(int32_t value) {
    _profiling_sample_record_max_len = value;
  }
  /// getter
  inline const std::vector<std::string>& Config::profiling_sample_commands() const {
    return _profiling_sample_commands;
  }

  /// setter
  inline std::vector<std::string>& Config::mutable_profiling_sample_commands() {
    return _profiling_sample_commands;
  }

  inline bool Config::profiling_sample_all_commands() const {
    return _profiling_sample_all_commands;
  }
  inline void Config::profiling_sample_all_commands(bool value) {
    _profiling_sample_all_commands = value;
  }
  /*
   * JSON processing configuration

   */
  inline int32_t Config::json_max_nesting_depth() const {
    return _json_max_nesting_depth;
  }
  inline void Config::json_max_nesting_depth(int32_t value) {
    _json_max_nesting_depth = value;
  }
  inline JsonStorageFormat Config::json_storage_format() const {
    return _json_storage_format;
  }
  inline void Config::set_json_storage_format(JsonStorageFormat value) {
    _json_storage_format = value;
  }
  /*
   * Transaction context mode

   */
  inline bool Config::txn_context_enabled() const {
    return _txn_context_enabled;
  }
  inline void Config::txn_context_enabled(bool value) {
    _txn_context_enabled = value;
  }
  /*
   * Performance tuning flags

   */
  inline bool Config::skip_block_cache_deallocation_on_close() const {
    return _skip_block_cache_deallocation_on_close;
  }
  inline void Config::skip_block_cache_deallocation_on_close(bool value) {
    _skip_block_cache_deallocation_on_close = value;
  }
  /*
   * Histogram metrics bucket boundaries

   */
  inline const std::vector<double>& Config::histogram_bucket_boundaries() const {
    return _histogram_bucket_boundaries;
  }
  inline std::vector<double>& Config::mutable_histogram_bucket_boundaries() {
    return _histogram_bucket_boundaries;
  }
  inline const RocksDBConfig& Config::rocks_db() const {
    return _rocks_db;
  }
  inline void Config::set_rocks_db(const RocksDBConfig& val) {
    _rocks_db = val;
  }
  inline void Config::set_rocks_db(RocksDBConfig&& val) {
    _rocks_db = std::move(val);
  }

}  // granite


