/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/config.proto */

/* Do not generate deprecated warnings for self */

#include <tests/config.tml.h>

#include <turbo/log/logging.h>



namespace my::custom::ns {
  turbo::Status Config::parse_toml_str(const std::string& str) {

    try {
      TURBO_MOVE_OR_RAISE(auto val , xtoml::parse_string(str));
      return  parse_toml(val, {});
    } catch(const std::exception &e) {
      return turbo::unknown_error(e.what());
    }

  }

  turbo::Status Config::parse_toml_file(const std::string& path) {
    try {
      TURBO_MOVE_OR_RAISE(auto val , xtoml::parse_file(path));
      return  parse_toml(val, {});
    } catch(const std::exception &e) {
      return turbo::unknown_error(e.what());
    }

  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  turbo::Status Config::parse_toml(const xtoml::Value& config, const std::vector<std::string> &prefix) {
    std::vector<std::string> uri = prefix;
    {
      uri.push_back("name");
      uri.pop_back();
      name = xtoml::find_key(config, "name", name);
    }
    {
      uri.push_back("age");
      uri.pop_back();
      age = xtoml::find_key(config, "age", age);
    }
    {
      uri.push_back("enabled");
      uri.pop_back();
      enabled = xtoml::find_key(config, "enabled", enabled);
    }
  return turbo::OkStatus();
  }

  xtoml::Value Config::serialize_toml() const {
    xtoml::Value result;
    {
      xtoml::Value val = name;
      result["name"] = val;
    }
    {
      xtoml::Value val = age;
      result["age"] = val;
    }
    {
      xtoml::Value val = enabled;
      result["enabled"] = val;
    }
    return result;
  }

  turbo::Result<std::string> Config::serialize_to_string() const {

    auto v = serialize_toml();

    return xtoml::serialize(v);

  }

}  // my::custom::ns

