/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/test.proto */

#pragma once

#include <cstdint>
#include <string>
#include <optional>
#include <google/protobuf/descriptor.h>
#include <tests/test.pb.h>
#include <tests/test.sk.h>
#include <shark/shark.h>
#include <atomic>
#include <turbo/container/flat_hash_map.h>



namespace my::custom::ns {

  class PersonBuilder;
  class AddressBuilder;
  class DetailBuilder;
  class PersonView;
  class AddressView;
  class DetailView;


  /// --- enums ---


  //////////////////////////////////////////////////////////////////////////
  /// --- builders --- 

  class  PersonBuilder {
  public:
    /// constructor
    PersonBuilder();

    /// destructor
    ~PersonBuilder();

    PersonBuilder(const PersonBuilder& rhs) = delete;

    PersonBuilder& operator= (const PersonBuilder& rhs) = delete;

    PersonBuilder(PersonBuilder&& rhs) noexcept = default;

    PersonBuilder& operator= (PersonBuilder&& rhs) noexcept = default;

    /////////////////////////////////////////////////////////////////////// 
    /// meta describe 
    static const google::protobuf::Descriptor* get_descriptor();

    const google::protobuf::Descriptor *descriptor() const;

    /////////////////////////////////////////////////////////////////////// 
    /// static default options region 
    static constexpr shark::idl::SharkFormat kDefaultFormat = shark::idl::SharkFormat::SKB_PURE;

    /////////////////////////////////////////////////////////////////////// 
    /// using PtrContainer = std::variant<>
    using PtrContainer = std::variant<test::pb::pa::Person,Person>;
    using kind = Person::kindCase;

    /// -----enums-------- 
    using Dolor = Person::Dolor;


  public:
    ///////////////////////////////////////////////////////////////////////// 
    /// @name Appenders
    /// @{

    /// Appends a protobuf message via pointer.
    /// @param pb Pointer to the protobuf message object. Must not be null.
    /// @return Reference to this builder for method chaining.
    /// @warning The caller must guarantee that the pointed-to object remains valid
    ///          until the builder is destroyed or `build()` is called. The builder
    ///          does not take ownership and will not delete the pointer.
    PersonBuilder& append(const test::pb::pa::Person* pb);

    /// Appends a runtime message via pointer.
    /// @param rt Pointer to the runtime message object. Must not be null.
    /// @return Reference to this builder for method chaining.
    /// @warning The caller must ensure the pointed-to object outlives this builder
    ///          and any call to `build()`. No ownership is transferred.
    PersonBuilder& append(const Person* rt);

    /// Appends multiple messages from a vector of value objects.
    /// @param rt Vector of messages (by value). The builder will copy/move each element
    ///           as needed; no external lifetime management is required.
    /// @return Reference to this builder for method chaining.
    PersonBuilder& append(const std::vector<PtrContainer>& rt);

    /// @}

    ///////////////////////////////////////////////////////////////////////// 
    /// builder 
    /// Serializes all appended messages into the output buffer.
    /// @param result Output buffer. If `append` is false, buffer is cleared first.
    /// @param error If non-null, set to a descriptive error message on failure.
    /// @param append If true, append to existing buffer; otherwise overwrite.
    /// @return true on success, false on error (e.g., invalid message).
    bool build(std::vector<uint8_t>& result, std::string* error = nullptr, bool append = false) const;

  private:
    ////////////////////// members
    std::vector<PtrContainer> _messages;
    ////////////////////// unions
  };

  //////////////////////////////////////////////////////////////////////////
  /// --- views ---

  class  PersonView {
  public:
    /// constructor
    PersonView() = default;

    /// destructor
    ~PersonView() = default;

    PersonView(const PersonView& rhs) = default;

    PersonView& operator= (const PersonView& rhs) = default;

    PersonView(PersonView&& rhs) noexcept = default;

    PersonView& operator= (PersonView&& rhs) noexcept = default;

    /////////////////////////////////////////////////////////////////////// 
    /// meta describe 
    static const google::protobuf::Descriptor* get_descriptor();

    const google::protobuf::Descriptor *descriptor() const;

    class  AddressView {
    public:
      /// constructor
      AddressView() = default;

      /// destructor
      ~AddressView() = default;

      AddressView(const AddressView& rhs) = default;

      AddressView& operator= (const AddressView& rhs) = default;

      AddressView(AddressView&& rhs) noexcept = default;

      AddressView& operator= (AddressView&& rhs) noexcept = default;

      /////////////////////////////////////////////////////////////////////// 
      /// meta describe 
      static const google::protobuf::Descriptor* get_descriptor();

      const google::protobuf::Descriptor *descriptor() const;

      class  DetailView {
      public:
        /// constructor
        DetailView() = default;

        /// destructor
        ~DetailView() = default;

        DetailView(const DetailView& rhs) = default;

        DetailView& operator= (const DetailView& rhs) = default;

        DetailView(DetailView&& rhs) noexcept = default;

        DetailView& operator= (DetailView&& rhs) noexcept = default;

        /////////////////////////////////////////////////////////////////////// 
        /// meta describe 
        static const google::protobuf::Descriptor* get_descriptor();

        const google::protobuf::Descriptor *descriptor() const;

        /// -----enums-------- 
      public:
        ////////////////////// getters

        inline const std::string& region() const;
        inline void set_region(const std::string &v);
        inline const std::string& prcode() const;
        inline void set_prcode(const std::string &v);
      private:
        ////////////////////// members
        std::string _region;
        std::string _prcode;
        ////////////////////// unions
      };
      /// -----enums-------- 
    public:
      ////////////////////// getters

      inline const std::string& street() const;
      inline void set_street(const std::string &v);
      inline int32_t number() const;
      inline void number(int32_t value);
      inline const Detail& detail() const;
      inline void set_detail(const Detail& val);
      inline void set_detail(Detail&& val);
    private:
      ////////////////////// members
      std::string _street;
      int32_t _number;
      Detail _detail;
      ////////////////////// unions
    };
    using kindCase = Person::kindCase;

    struct Kind {
      shark::EnumView<Person::kindCase> kind_case;
      union Data {
        shark::StringView aaa;
        shark::PrimitiveView<uint32_t> bbb;
        shark::MessageView<PersonView::AddressView> ddd;
        Data() {};

        ~Data() {};

      } data;
    };

    /// -----enums-------- 
    using Dolor = Person::Dolor;


  public:
    ////////////////////// getters

    inline const std::pair<std::string,std::string>& any_one() const;
    inline void set_any_one(const std::pair<std::string,std::string> &v);
    inline const std::vector<std::pair<std::string,std::string>>& any_two() const;
    inline std::vector<std::pair<std::string,std::string>>& mutable_any_two();
    [[deprecated]] inline const std::string& name() const;
    [[deprecated]] inline void set_name(const std::string &v);
    inline int8_t age() const;
    inline void age(int8_t value);
    inline const std::vector<std::string>& emails() const;
    inline std::vector<std::string>& mutable_emails();
    inline const std::vector<int32_t>& ages() const;
    inline std::vector<int32_t>& mutable_ages();
    inline const absl::flat_hash_map<std::string,int32_t>& scores() const;
    inline void set_scores(const absl::flat_hash_map<std::string,int32_t> &v);
    inline Color favorite_color() const;
    inline void set_favorite_color(Color value);
    inline const Address& address() const;
    inline void set_address(const Address& val);
    inline void set_address(Address&& val);
    inline const Address& address2() const;
    inline void set_address2(const Address& val);
    inline void set_address2(Address&& val);
    inline const std::string& long_name() const;
    inline void set_long_name(const std::string &v);
    inline shark::OneOfView<Kind> kind() const;
  private:
    ////////////////////// members
    std::pair<std::string,std::string> _any_one;
    std::vector<std::pair<std::string,std::string>> _any_two;
    std::string _name;
    int8_t _age;
    std::vector<std::string> _emails;
    std::vector<int32_t> _ages;
    absl::flat_hash_map<std::string,int32_t> _scores;
    Color _favorite_color;
    Address _address;
    Address _address2;
    std::string _long_name;
    ////////////////////// unions
    shark::OneOfView<Kind> _kind;

  };

  /* --- descriptors --- */


  ///////////////////////////////////////////////////////////
  /// --- inlines ---
  inline const google::protobuf::Descriptor* PersonBuilder::descriptor() const {
    return get_descriptor();
  }


  inline const google::protobuf::Descriptor* PersonView::AddressView::DetailView::descriptor() const {
    return get_descriptor();
  }

  /// getter
  inline const std::string& Person::Address::Detail::region() const {
    return _region;
  }
  /// setter
  inline void Person::Address::Detail::set_region(const std::string &v) {
    _region = v;
  }
  /// getter
  inline const std::string& Person::Address::Detail::prcode() const {
    return _prcode;
  }
  /// setter
  inline void Person::Address::Detail::set_prcode(const std::string &v) {
    _prcode = v;
  }
  inline const google::protobuf::Descriptor* PersonView::AddressView::descriptor() const {
    return get_descriptor();
  }

  /// getter
  inline const std::string& Person::Address::street() const {
    return _street;
  }
  /// setter
  inline void Person::Address::set_street(const std::string &v) {
    _street = v;
  }
  inline int32_t Person::Address::number() const {
    return _number;
  }
  inline void Person::Address::number(int32_t value) {
    _number = value;
  }
  inline const Person::Address::Detail& Person::Address::detail() const {
    return _detail;
  }
  inline void Person::Address::set_detail(const Detail& val) {
    _detail = val;
  }
  inline void Person::Address::set_detail(Detail&& val) {
    _detail = std::move(val);
  }
  inline const google::protobuf::Descriptor* PersonView::descriptor() const {
    return get_descriptor();
  }

  /// getter
  inline const std::pair<std::string,std::string>& Person::any_one() const {
    return _any_one;
  }
  /// setter
  inline void Person::set_any_one(const std::pair<std::string,std::string> &v) {
    _any_one = v;
  }
  /// getter
  inline const std::vector<std::pair<std::string,std::string>>& Person::any_two() const {
    return _any_two;
  }

  /// setter
  inline std::vector<std::pair<std::string,std::string>>& Person::mutable_any_two() {
    return _any_two;
  }

  /// getter
  inline const std::string& Person::name() const {
    return _name;
  }
  /// setter
  inline void Person::set_name(const std::string &v) {
    _name = v;
  }
  inline int8_t Person::age() const {
    return _age;
  }
  inline void Person::age(int8_t value) {
    _age = value;
  }
  /// getter
  inline const std::vector<std::string>& Person::emails() const {
    return _emails;
  }

  /// setter
  inline std::vector<std::string>& Person::mutable_emails() {
    return _emails;
  }

  inline const std::vector<int32_t>& Person::ages() const {
    return _ages;
  }
  inline std::vector<int32_t>& Person::mutable_ages() {
    return _ages;
  }
  /// getter
  inline const absl::flat_hash_map<std::string,int32_t>& Person::scores() const {
    return _scores;
  }
  /// setter
  inline void Person::set_scores(const absl::flat_hash_map<std::string,int32_t> &v) {
    _scores = v;
  }
  inline Color Person::favorite_color() const {
    return _favorite_color;
  }
  inline void Person::set_favorite_color(Color value) {
    _favorite_color = value;
  }
  inline const Person::Address& Person::address() const {
    return _address;
  }
  inline void Person::set_address(const Address& val) {
    _address = val;
  }
  inline void Person::set_address(Address&& val) {
    _address = std::move(val);
  }
  inline const Person::Address& Person::address2() const {
    return _address2;
  }
  inline void Person::set_address2(const Address& val) {
    _address2 = val;
  }
  inline void Person::set_address2(Address&& val) {
    _address2 = std::move(val);
  }
  /// getter
  inline const std::string& Person::long_name() const {
    return _long_name;
  }
  /// setter
  inline void Person::set_long_name(const std::string &v) {
    _long_name = v;
  }
  inline shark::OneOfView<PersonView::Kind> PersonView::kind() const {;
    return _kind;
  }


}  // my::custom::ns


