/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/test.proto */

/* Do not generate deprecated warnings for self */

#include <tests/test.sk.h>
#include <tests/test.skb.h>
#include <google/protobuf/json/json.h>

namespace my::custom::ns {
  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* PersonView::AddressView::DetailView::get_descriptor() {
    return test::pb::pa::Person::Address::Detail::descriptor();
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* PersonView::AddressView::get_descriptor() {
    return test::pb::pa::Person::Address::descriptor();
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* PersonView::get_descriptor() {
    return test::pb::pa::Person::descriptor();
  }

  /// Returns a static map from field path to FieldMeta.
  /// This map is initialized once and provides metadata for all fields.
  const turbo::flat_hash_map<std::string, PersonView::FieldMeta>& PersonView::uri_data() {
    static const turbo::flat_hash_map<std::string, FieldMeta> kMap = [](){
      static const turbo::flat_hash_map<std::string, FieldMeta> map;
      {
        FieldMeta m1;
        m1.index = 1;
        m1.data_index = -1;
        m1.path = "any_one";
        m1.column.push_back(15);
        m1.column.push_back(16);
        m1.repeated = false;
        m1.cpp_type = "";
        map["any_one"] = m1;
      }
      {
        FieldMeta m2;
        m2.index = 2;
        m2.data_index = -1;
        m2.path = "any_two";
        m2.column.push_back(17);
        m2.column.push_back(18);
        m2.repeated = true;
        m2.cpp_type = "";
        map["any_two"] = m2;
      }
      {
        FieldMeta m3;
        m3.index = 3;
        m3.data_index = 1;
        m3.path = "name";
        m3.repeated = false;
        m3.cpp_type = "std::string";
        map["name"] = m3;
      }
      {
        FieldMeta m4;
        m4.index = 4;
        m4.data_index = 2;
        m4.path = "age";
        m4.repeated = false;
        m4.cpp_type = "int8_t";
        map["age"] = m4;
      }
      {
        FieldMeta m5;
        m5.index = 5;
        m5.data_index = 3;
        m5.path = "emails";
        m5.repeated = true;
        m5.cpp_type = "std::string";
        map["emails"] = m5;
      }
      {
        FieldMeta m6;
        m6.index = 6;
        m6.data_index = 4;
        m6.path = "ages";
        m6.repeated = true;
        m6.cpp_type = "int32_t";
        map["ages"] = m6;
      }
      {
        FieldMeta m7;
        m7.index = 7;
        m7.data_index = -1;
        m7.path = "scores";
        m7.column.push_back(19);
        m7.column.push_back(20);
        m7.repeated = true;
        m7.cpp_type = "";
        map["scores"] = m7;
      }
      {
        FieldMeta m8;
        m8.index = 8;
        m8.data_index = 5;
        m8.path = "favorite_color";
        m8.repeated = false;
        m8.cpp_type = "enum";
        map["favorite_color"] = m8;
      }
      {
        FieldMeta m9;
        m9.index = 9;
        m9.data_index = 6;
        m9.path = "aaa";
        m9.repeated = false;
        m9.cpp_type = "std::string";
        map["aaa"] = m9;
      }
      {
        FieldMeta m10;
        m10.index = 10;
        m10.data_index = 7;
        m10.path = "bbb";
        m10.repeated = false;
        m10.cpp_type = "uint32_t";
        map["bbb"] = m10;
      }
      {
        FieldMeta m11;
        m11.index = 11;
        m11.data_index = -1;
        m11.path = "ddd";
        m11.column.push_back(21);
        m11.column.push_back(22);
        m11.column.push_back(23);
        m11.repeated = false;
        m11.cpp_type = "";
        map["ddd"] = m11;
      }
      {
        FieldMeta m12;
        m12.index = 12;
        m12.data_index = -1;
        m12.path = "address";
        m12.column.push_back(24);
        m12.column.push_back(25);
        m12.column.push_back(26);
        m12.repeated = false;
        m12.cpp_type = "";
        map["address"] = m12;
      }
      {
        FieldMeta m13;
        m13.index = 13;
        m13.data_index = -1;
        m13.path = "address2";
        m13.column.push_back(27);
        m13.column.push_back(28);
        m13.column.push_back(29);
        m13.repeated = false;
        m13.cpp_type = "";
        map["address2"] = m13;
      }
      {
        FieldMeta m14;
        m14.index = 14;
        m14.data_index = 8;
        m14.path = "long_name";
        m14.repeated = false;
        m14.cpp_type = "std::string";
        map["long_name"] = m14;
      }
      {
        FieldMeta m15;
        m15.index = 15;
        m15.data_index = 9;
        m15.path = "any_one.type_url";
        m15.repeated = false;
        m15.cpp_type = "std::string";
        map["any_one.type_url"] = m15;
      }
      {
        FieldMeta m16;
        m16.index = 16;
        m16.data_index = 10;
        m16.path = "any_one.value";
        m16.repeated = false;
        m16.cpp_type = "std::vector<uint8_t>";
        map["any_one.value"] = m16;
      }
      {
        FieldMeta m17;
        m17.index = 17;
        m17.data_index = 11;
        m17.path = "any_two.type_url";
        m17.repeated = false;
        m17.cpp_type = "std::string";
        map["any_two.type_url"] = m17;
      }
      {
        FieldMeta m18;
        m18.index = 18;
        m18.data_index = 12;
        m18.path = "any_two.value";
        m18.repeated = false;
        m18.cpp_type = "std::vector<uint8_t>";
        map["any_two.value"] = m18;
      }
      {
        FieldMeta m19;
        m19.index = 19;
        m19.data_index = 13;
        m19.path = "scores.key";
        m19.repeated = false;
        m19.cpp_type = "std::string";
        map["scores.key"] = m19;
      }
      {
        FieldMeta m20;
        m20.index = 20;
        m20.data_index = 14;
        m20.path = "scores.value";
        m20.repeated = false;
        m20.cpp_type = "int32_t";
        map["scores.value"] = m20;
      }
      {
        FieldMeta m21;
        m21.index = 21;
        m21.data_index = 15;
        m21.path = "ddd.street";
        m21.repeated = false;
        m21.cpp_type = "std::string";
        map["ddd.street"] = m21;
      }
      {
        FieldMeta m22;
        m22.index = 22;
        m22.data_index = 16;
        m22.path = "ddd.number";
        m22.repeated = false;
        m22.cpp_type = "int32_t";
        map["ddd.number"] = m22;
      }
      {
        FieldMeta m23;
        m23.index = 23;
        m23.data_index = -1;
        m23.path = "ddd.detail";
        m23.column.push_back(30);
        m23.column.push_back(31);
        m23.repeated = false;
        m23.cpp_type = "";
        map["ddd.detail"] = m23;
      }
      {
        FieldMeta m24;
        m24.index = 24;
        m24.data_index = 17;
        m24.path = "address.street";
        m24.repeated = false;
        m24.cpp_type = "std::string";
        map["address.street"] = m24;
      }
      {
        FieldMeta m25;
        m25.index = 25;
        m25.data_index = 18;
        m25.path = "address.number";
        m25.repeated = false;
        m25.cpp_type = "int32_t";
        map["address.number"] = m25;
      }
      {
        FieldMeta m26;
        m26.index = 26;
        m26.data_index = -1;
        m26.path = "address.detail";
        m26.column.push_back(32);
        m26.column.push_back(33);
        m26.repeated = false;
        m26.cpp_type = "";
        map["address.detail"] = m26;
      }
      {
        FieldMeta m27;
        m27.index = 27;
        m27.data_index = 19;
        m27.path = "address2.street";
        m27.repeated = false;
        m27.cpp_type = "std::string";
        map["address2.street"] = m27;
      }
      {
        FieldMeta m28;
        m28.index = 28;
        m28.data_index = 20;
        m28.path = "address2.number";
        m28.repeated = false;
        m28.cpp_type = "int32_t";
        map["address2.number"] = m28;
      }
      {
        FieldMeta m29;
        m29.index = 29;
        m29.data_index = -1;
        m29.path = "address2.detail";
        m29.column.push_back(34);
        m29.column.push_back(35);
        m29.repeated = false;
        m29.cpp_type = "";
        map["address2.detail"] = m29;
      }
      {
        FieldMeta m30;
        m30.index = 30;
        m30.data_index = 21;
        m30.path = "ddd.detail.region";
        m30.repeated = false;
        m30.cpp_type = "std::string";
        map["ddd.detail.region"] = m30;
      }
      {
        FieldMeta m31;
        m31.index = 31;
        m31.data_index = 22;
        m31.path = "ddd.detail.prcode";
        m31.repeated = false;
        m31.cpp_type = "std::string";
        map["ddd.detail.prcode"] = m31;
      }
      {
        FieldMeta m32;
        m32.index = 32;
        m32.data_index = 23;
        m32.path = "address.detail.region";
        m32.repeated = false;
        m32.cpp_type = "std::string";
        map["address.detail.region"] = m32;
      }
      {
        FieldMeta m33;
        m33.index = 33;
        m33.data_index = 24;
        m33.path = "address.detail.prcode";
        m33.repeated = false;
        m33.cpp_type = "std::string";
        map["address.detail.prcode"] = m33;
      }
      {
        FieldMeta m34;
        m34.index = 34;
        m34.data_index = 25;
        m34.path = "address2.detail.region";
        m34.repeated = false;
        m34.cpp_type = "std::string";
        map["address2.detail.region"] = m34;
      }
      {
        FieldMeta m35;
        m35.index = 35;
        m35.data_index = 26;
        m35.path = "address2.detail.prcode";
        m35.repeated = false;
        m35.cpp_type = "std::string";
        map["address2.detail.prcode"] = m35;
      }
      return map;
    }();

    return kMap;
  }

}  // my::custom::ns

