/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: tests/test.proto */

/* Do not generate deprecated warnings for self */

#include <tests/test.sk.h>
#include <google/protobuf/json/json.h>



namespace my::custom::ns {
  std::optional<Color> parse_Color(std::string_view value) {
    static turbo::flat_hash_map<std::string, Color> enum_map = {
      {"RED", static_cast<Color>(0)},
      {"GREEN", static_cast<Color>(1)},
      {"BLUE", static_cast<Color>(2)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  std::optional<ColorU16> parse_ColorU16(std::string_view value) {
    static turbo::flat_hash_map<std::string, ColorU16> enum_map = {
      {"RED16", static_cast<ColorU16>(0)},
      {"GREEN16", static_cast<ColorU16>(1)},
      {"BLUE16", static_cast<ColorU16>(2)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  std::optional<ColorU32> parse_ColorU32(std::string_view value) {
    static turbo::flat_hash_map<std::string, ColorU32> enum_map = {
      {"RED32", static_cast<ColorU32>(0)},
      {"GREEN32", static_cast<ColorU32>(1)},
      {"BLUE32", static_cast<ColorU32>(2)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  std::optional<Person::Dolor> Person::parse_Dolor(std::string_view value) {
    static turbo::flat_hash_map<std::string, Dolor> enum_map = {
      {"DRED", static_cast<Person::Dolor>(0)},
      {"DGREEN", static_cast<Person::Dolor>(1)},
      {"DBLUE", static_cast<Person::Dolor>(2)},
    };

    auto it = enum_map.find(value);
    if (it == enum_map.end()) {
      return std::nullopt;
    }
    return it->second;
  }
  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* Person::Address::Detail::get_descriptor() {
    return test::pb::pa::Person::Address::Detail::descriptor();
  }

  Person::Address::Detail::Detail() {
  }

  Person::Address::Detail::~Detail() {
  }

  Person::Address::Detail::Detail(const Detail& rhs) {
    _region = rhs._region;
    _prcode = rhs._prcode;
  }

  Person::Address::Detail& Person::Address::Detail::operator= (const Detail& rhs) {
    _region = rhs._region;
    _prcode = rhs._prcode;
    return *this;
  }

  Person::Address::Detail::Detail(Detail&& rhs) noexcept {
    _region = std::move(rhs._region);
    _prcode = std::move(rhs._prcode);
  }

  Person::Address::Detail& Person::Address::Detail::operator= (Detail&& rhs) noexcept {
    _region = std::move(rhs._region);
    _prcode = std::move(rhs._prcode);
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void Person::Address::Detail::parse_from_proto(const test::pb::pa::Person::Address::Detail& pb) {
    _region = pb.region();
    _prcode = pb.prcode();
  }

  void Person::Address::Detail::serialize_to_proto(test::pb::pa::Person::Address::Detail& pb) const {
    pb.set_region(_region);
    pb.set_prcode(_prcode);
  }

  turbo::Status Person::Address::Detail::parse_from_json(const std::string& json) {
    test::pb::pa::Person::Address::Detail pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status Person::Address::Detail::serialize_to_json(std::string& json) const {
    test::pb::pa::Person::Address::Detail pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string Person::Address::Detail::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* Person::Address::get_descriptor() {
    return test::pb::pa::Person::Address::descriptor();
  }

  Person::Address::Address() {
  }

  Person::Address::~Address() {
  }

  Person::Address::Address(const Address& rhs) {
    _street = rhs._street;
    _number = rhs._number;
    _detail = rhs._detail;
  }

  Person::Address& Person::Address::operator= (const Address& rhs) {
    _street = rhs._street;
    _number = rhs._number;
    _detail = rhs._detail;
    return *this;
  }

  Person::Address::Address(Address&& rhs) noexcept {
    _street = std::move(rhs._street);
    _number = rhs._number;
    _detail = std::move(rhs._detail);
  }

  Person::Address& Person::Address::operator= (Address&& rhs) noexcept {
    _street = std::move(rhs._street);
    _number = rhs._number;
    _detail = std::move(rhs._detail);
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void Person::Address::parse_from_proto(const test::pb::pa::Person::Address& pb) {
    _street = pb.street();
    _number = pb.number();
    _detail.parse_from_proto(pb.detail());
  }

  void Person::Address::serialize_to_proto(test::pb::pa::Person::Address& pb) const {
    pb.set_street(_street);
    pb.set_number(_number);
    _detail.serialize_to_proto(*pb.mutable_detail());
  }

  turbo::Status Person::Address::parse_from_json(const std::string& json) {
    test::pb::pa::Person::Address pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status Person::Address::serialize_to_json(std::string& json) const {
    test::pb::pa::Person::Address pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string Person::Address::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// metas 
  const google::protobuf::Descriptor* Person::get_descriptor() {
    return test::pb::pa::Person::descriptor();
  }

  Person::Person() {
    clear_kind(); 
  }

  Person::~Person() {
    clear_kind(); 
  }

  Person::Person(const Person& rhs) {
    clear_kind();
    switch(rhs.kind_case()) {
      case kindCase::AAA:
        _kind._aaa = std::make_unique<std::string>();
        *_kind._aaa = *rhs._kind._aaa;
        break;
      case kindCase::BBB:
        _kind._bbb = rhs._kind._bbb;
        break;
      case kindCase::DDD:
        _kind._ddd = std::make_unique<Address>();
        *_kind._ddd = *rhs._kind._ddd;
        break;
      default:
        break;
    };
    _kind_case = rhs._kind_case;
    _any_one = rhs._any_one;
    _any_two = rhs._any_two;
    _name = rhs._name;
    _age = rhs._age;
    _emails = rhs._emails;
    _ages = rhs._ages;
    _scores = rhs._scores;
    _favorite_color = rhs._favorite_color;
    _address = rhs._address;
    _address2 = rhs._address2;
    _long_name = rhs._long_name;
  }

  Person& Person::operator= (const Person& rhs) {
    clear_kind();
    switch(rhs.kind_case()) {
      case kindCase::AAA:
        _kind._aaa = std::make_unique<std::string>();
        *_kind._aaa = *rhs._kind._aaa;
        break;
      case kindCase::BBB:
        _kind._bbb = rhs._kind._bbb;
        break;
      case kindCase::DDD:
        _kind._ddd = std::make_unique<Address>();
        *_kind._ddd = *rhs._kind._ddd;
        break;
      default:
        break;
    };
    _kind_case = rhs._kind_case;
    _any_one = rhs._any_one;
    _any_two = rhs._any_two;
    _name = rhs._name;
    _age = rhs._age;
    _emails = rhs._emails;
    _ages = rhs._ages;
    _scores = rhs._scores;
    _favorite_color = rhs._favorite_color;
    _address = rhs._address;
    _address2 = rhs._address2;
    _long_name = rhs._long_name;
    return *this;
  }

  Person::Person(Person&& rhs) noexcept {
    clear_kind();
    switch(rhs.kind_case()) {
      case kindCase::AAA:
        _kind._aaa = std::move(rhs._kind._aaa);
        break;
      case kindCase::BBB:
        _kind._bbb = rhs._kind._bbb;
        break;
      case kindCase::DDD:
        _kind._ddd = std::move(rhs._kind._ddd);
        break;
      default:
        break;
    };
    _kind_case = rhs._kind_case;
    _any_one = std::move(rhs._any_one);
    _any_two = std::move(rhs._any_two);
    _name = std::move(rhs._name);
    _age = rhs._age;
    _emails = std::move(rhs._emails);
    _ages = std::move(rhs._ages);
    _scores = std::move(rhs._scores);
    _favorite_color = rhs._favorite_color;
    _address = std::move(rhs._address);
    _address2 = std::move(rhs._address2);
    _long_name = std::move(rhs._long_name);
  }

  Person& Person::operator= (Person&& rhs) noexcept {
    clear_kind();
    switch(rhs.kind_case()) {
      case kindCase::AAA:
        _kind._aaa = std::move(rhs._kind._aaa);
        break;
      case kindCase::BBB:
        _kind._bbb = rhs._kind._bbb;
        break;
      case kindCase::DDD:
        _kind._ddd = std::move(rhs._kind._ddd);
        break;
      default:
        break;
    };
    _kind_case = rhs._kind_case;
    _any_one = std::move(rhs._any_one);
    _any_two = std::move(rhs._any_two);
    _name = std::move(rhs._name);
    _age = rhs._age;
    _emails = std::move(rhs._emails);
    _ages = std::move(rhs._ages);
    _scores = std::move(rhs._scores);
    _favorite_color = rhs._favorite_color;
    _address = std::move(rhs._address);
    _address2 = std::move(rhs._address2);
    _long_name = std::move(rhs._long_name);
    return *this;
  }

  ///////////////////////////////////////////////////////////////////////// 
  /// transfers 
  void Person::parse_from_proto(const test::pb::pa::Person& pb) {
    _any_one.first = pb.any_one().type_url();
    _any_one.second = pb.any_one().value();
    _any_two.resize(pb.any_two_size());
    for(size_t i = 0; i < pb.any_two_size(); ++i) {
      _any_two[i].first = pb.any_two(i).type_url();
      _any_two[i].second = pb.any_two(i).value();
    }
    _name = pb.name();
    _age = pb.age();
    _emails.reserve(pb.emails_size());
    for(size_t i = 0; i < pb.emails_size(); ++i) {
      _emails.push_back(pb.emails(i));
    }
    _ages.reserve(pb.ages_size());
    auto &ref = pb.ages();
    for(size_t i = 0; i < pb.ages_size(); ++i) {
      _ages.push_back(ref[i]);
    }
    _scores.reserve(pb.scores_size());
    for(auto &it : pb.scores()) {
      _scores[it.first] = it.second;
    }
    _favorite_color = static_cast<Color>(pb.favorite_color());
    _address.parse_from_proto(pb.address());
    _address2.resize(pb.address2_size());for(size_t i = 0; i < pb.address2_size(); ++i) {
      _address2[i].parse_from_proto(pb.address2(i));
    }
    _long_name = pb.long_name();
    clear_kind();
    switch(pb.kind_case()) {
      case test::pb::pa::Person::KindCase::kAaa:
        _kind._aaa = std::make_unique<std::string>();
        *_kind._aaa = pb.aaa();
        _kind_case = kindCase::AAA;
        break;
      case test::pb::pa::Person::KindCase::kBbb:
        _kind._bbb = pb.bbb();
        _kind_case = kindCase::BBB;
        break;
      case test::pb::pa::Person::KindCase::kDdd:
        _kind._ddd = std::make_unique<Address>();
        _kind._ddd->parse_from_proto(pb.ddd());
        _kind_case = kindCase::DDD;
        break;
      default:
        break;
    };
  }

  void Person::serialize_to_proto(test::pb::pa::Person& pb) const {
    pb.mutable_any_one()->set_type_url(_any_one.first);
    pb.mutable_any_one()->set_value(_any_one.second);
    pb.mutable_any_two()->Reserve(_any_two.size());
    for(size_t i = 0; i < _any_two.size(); ++i) {
      auto ptr = pb.mutable_any_two()->Add();
      ptr->set_type_url(_any_two[i].first);
      ptr->set_value(_any_two[i].second);
    }
    pb.set_name(_name);
    pb.set_age(_age);
    pb.mutable_emails()->Reserve(_emails.size());
    for(size_t i = 0; i < _emails.size(); ++i) {
      *pb.mutable_emails()->Add() = _emails[i];
    }
    pb.mutable_ages()->Reserve(_ages.size());
    for(size_t i = 0; i < _ages.size(); ++i) {
      *pb.mutable_ages()->Add() = _ages[i];
    }
    for(auto &it : _scores) {
      (*pb.mutable_scores())[it.first] = it.second;
    }
    pb.set_favorite_color(static_cast<test::pb::pa::Color>(_favorite_color));
    _address.serialize_to_proto(*pb.mutable_address());
    pb.mutable_address2()->Reserve(_address2.size());
    for(size_t i = 0; i < _address2.size(); ++i) {
      _address2[i].serialize_to_proto(*pb.mutable_address2()->Add());
    }
    pb.set_long_name(_long_name);
    switch(kind_case()) {
      case kindCase::AAA:
        pb.set_aaa(aaa());
        break;
      case kindCase::BBB:
        pb.set_bbb(bbb());
        break;
      case kindCase::DDD:
        _kind._ddd->serialize_to_proto(*pb.mutable_ddd());
        break;
      default:
        break;
    };
  }

  turbo::Status Person::parse_from_json(const std::string& json) {
    test::pb::pa::Person pb;
    auto rs = google::protobuf::json::JsonStringToMessage(json, &pb, google::protobuf::json::ParseOptions());
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    parse_from_proto(pb);
    return turbo::OkStatus();
  }

  turbo::Status Person::serialize_to_json(std::string& json) const {
    test::pb::pa::Person pb;
    serialize_to_proto(pb);
    auto rs = google::protobuf::json::MessageToJsonString(pb, &json);
    if(!rs.ok()) {
      return turbo::make_status(rs.code(), rs.message());
    }

    return turbo::OkStatus();
  }

  std::string Person::to_string() const {
    std::string json;
    auto b = serialize_to_json(json);
    if(b.ok()) {
      return json;
    }

    return "";
  }

}  // my::custom::ns

