// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shark/idl/shark_options.proto
// Protobuf C++ Version: 5.29.5

#ifndef shark_2fidl_2fshark_5foptions_2eproto_2epb_2eh
#define shark_2fidl_2fshark_5foptions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_shark_2fidl_2fshark_5foptions_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_shark_2fidl_2fshark_5foptions_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_shark_2fidl_2fshark_5foptions_2eproto;
namespace shark {
namespace idl {
class SharkEnumOptions;
struct SharkEnumOptionsDefaultTypeInternal;
extern SharkEnumOptionsDefaultTypeInternal _SharkEnumOptions_default_instance_;
class SharkFieldOptions;
struct SharkFieldOptionsDefaultTypeInternal;
extern SharkFieldOptionsDefaultTypeInternal _SharkFieldOptions_default_instance_;
class SharkFileOptions;
struct SharkFileOptionsDefaultTypeInternal;
extern SharkFileOptionsDefaultTypeInternal _SharkFileOptions_default_instance_;
class SharkMessageOptions;
struct SharkMessageOptionsDefaultTypeInternal;
extern SharkMessageOptionsDefaultTypeInternal _SharkMessageOptions_default_instance_;
}  // namespace idl
}  // namespace shark
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace shark {
namespace idl {
enum EnumValueStyle : int {
  ENUM_VALUE_STYLE_UNSPECIFIED = 0,
  ENUM_VALUE_STYLE_STRICT = 1,
  ENUM_VALUE_STYLE_OPEN = 2,
  EnumValueStyle_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EnumValueStyle_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EnumValueStyle_IsValid(int value);
extern const uint32_t EnumValueStyle_internal_data_[];
constexpr EnumValueStyle EnumValueStyle_MIN = static_cast<EnumValueStyle>(0);
constexpr EnumValueStyle EnumValueStyle_MAX = static_cast<EnumValueStyle>(2);
constexpr int EnumValueStyle_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
EnumValueStyle_descriptor();
template <typename T>
const std::string& EnumValueStyle_Name(T value) {
  static_assert(std::is_same<T, EnumValueStyle>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnumValueStyle_Name().");
  return EnumValueStyle_Name(static_cast<EnumValueStyle>(value));
}
template <>
inline const std::string& EnumValueStyle_Name(EnumValueStyle value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EnumValueStyle_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool EnumValueStyle_Parse(absl::string_view name, EnumValueStyle* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumValueStyle>(
      EnumValueStyle_descriptor(), name, value);
}
enum EnumStorageKind : int {
  ENUM_STORAGE_KIND_UNSPECIFIED = 0,
  ENUM_STORAGE_KIND_INT32 = 1,
  ENUM_STORAGE_KIND_TYPED = 2,
  EnumStorageKind_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EnumStorageKind_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EnumStorageKind_IsValid(int value);
extern const uint32_t EnumStorageKind_internal_data_[];
constexpr EnumStorageKind EnumStorageKind_MIN = static_cast<EnumStorageKind>(0);
constexpr EnumStorageKind EnumStorageKind_MAX = static_cast<EnumStorageKind>(2);
constexpr int EnumStorageKind_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
EnumStorageKind_descriptor();
template <typename T>
const std::string& EnumStorageKind_Name(T value) {
  static_assert(std::is_same<T, EnumStorageKind>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnumStorageKind_Name().");
  return EnumStorageKind_Name(static_cast<EnumStorageKind>(value));
}
template <>
inline const std::string& EnumStorageKind_Name(EnumStorageKind value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EnumStorageKind_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool EnumStorageKind_Parse(absl::string_view name, EnumStorageKind* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumStorageKind>(
      EnumStorageKind_descriptor(), name, value);
}
enum EnumUnderlyingType : int {
  ENUM_UNDERLYING_TYPE_UNSPECIFIED = 0,
  ENUM_UNDERLYING_TYPE_U8 = 1,
  ENUM_UNDERLYING_TYPE_U16 = 2,
  ENUM_UNDERLYING_TYPE_U32 = 3,
  ENUM_UNDERLYING_TYPE_U64 = 4,
  EnumUnderlyingType_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EnumUnderlyingType_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EnumUnderlyingType_IsValid(int value);
extern const uint32_t EnumUnderlyingType_internal_data_[];
constexpr EnumUnderlyingType EnumUnderlyingType_MIN = static_cast<EnumUnderlyingType>(0);
constexpr EnumUnderlyingType EnumUnderlyingType_MAX = static_cast<EnumUnderlyingType>(4);
constexpr int EnumUnderlyingType_ARRAYSIZE = 4 + 1;
const ::google::protobuf::EnumDescriptor*
EnumUnderlyingType_descriptor();
template <typename T>
const std::string& EnumUnderlyingType_Name(T value) {
  static_assert(std::is_same<T, EnumUnderlyingType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnumUnderlyingType_Name().");
  return EnumUnderlyingType_Name(static_cast<EnumUnderlyingType>(value));
}
template <>
inline const std::string& EnumUnderlyingType_Name(EnumUnderlyingType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EnumUnderlyingType_descriptor,
                                                 0, 4>(
      static_cast<int>(value));
}
inline bool EnumUnderlyingType_Parse(absl::string_view name, EnumUnderlyingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumUnderlyingType>(
      EnumUnderlyingType_descriptor(), name, value);
}
enum EnumStringSource : int {
  ENUM_STRING_SOURCE_UNSPECIFIED = 0,
  ENUM_STRING_SOURCE_PROTO_REFLECTION = 1,
  ENUM_STRING_SOURCE_CUSTOM_TABLE = 2,
  EnumStringSource_INT_MIN_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::min(),
  EnumStringSource_INT_MAX_SENTINEL_DO_NOT_USE_ =
      std::numeric_limits<::int32_t>::max(),
};

bool EnumStringSource_IsValid(int value);
extern const uint32_t EnumStringSource_internal_data_[];
constexpr EnumStringSource EnumStringSource_MIN = static_cast<EnumStringSource>(0);
constexpr EnumStringSource EnumStringSource_MAX = static_cast<EnumStringSource>(2);
constexpr int EnumStringSource_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
EnumStringSource_descriptor();
template <typename T>
const std::string& EnumStringSource_Name(T value) {
  static_assert(std::is_same<T, EnumStringSource>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnumStringSource_Name().");
  return EnumStringSource_Name(static_cast<EnumStringSource>(value));
}
template <>
inline const std::string& EnumStringSource_Name(EnumStringSource value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EnumStringSource_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool EnumStringSource_Parse(absl::string_view name, EnumStringSource* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumStringSource>(
      EnumStringSource_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class SharkMessageOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkMessageOptions) */ {
 public:
  inline SharkMessageOptions() : SharkMessageOptions(nullptr) {}
  ~SharkMessageOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkMessageOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkMessageOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkMessageOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkMessageOptions(const SharkMessageOptions& from) : SharkMessageOptions(nullptr, from) {}
  inline SharkMessageOptions(SharkMessageOptions&& from) noexcept
      : SharkMessageOptions(nullptr, std::move(from)) {}
  inline SharkMessageOptions& operator=(const SharkMessageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkMessageOptions& operator=(SharkMessageOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkMessageOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkMessageOptions* internal_default_instance() {
    return reinterpret_cast<const SharkMessageOptions*>(
        &_SharkMessageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SharkMessageOptions& a, SharkMessageOptions& b) { a.Swap(&b); }
  inline void Swap(SharkMessageOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkMessageOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkMessageOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkMessageOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkMessageOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkMessageOptions& from) { SharkMessageOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkMessageOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkMessageOptions"; }

 protected:
  explicit SharkMessageOptions(::google::protobuf::Arena* arena);
  SharkMessageOptions(::google::protobuf::Arena* arena, const SharkMessageOptions& from);
  SharkMessageOptions(::google::protobuf::Arena* arena, SharkMessageOptions&& from) noexcept
      : SharkMessageOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kGenOwnedFieldNumber = 1,
    kGenViewFieldNumber = 2,
  };
  // bool gen_owned = 1;
  void clear_gen_owned() ;
  bool gen_owned() const;
  void set_gen_owned(bool value);

  private:
  bool _internal_gen_owned() const;
  void _internal_set_gen_owned(bool value);

  public:
  // bool gen_view = 2;
  void clear_gen_view() ;
  bool gen_view() const;
  void set_gen_view(bool value);

  private:
  bool _internal_gen_view() const;
  void _internal_set_gen_view(bool value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkMessageOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkMessageOptions& from_msg);
    bool gen_owned_;
    bool gen_view_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkFileOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkFileOptions) */ {
 public:
  inline SharkFileOptions() : SharkFileOptions(nullptr) {}
  ~SharkFileOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkFileOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkFileOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkFileOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkFileOptions(const SharkFileOptions& from) : SharkFileOptions(nullptr, from) {}
  inline SharkFileOptions(SharkFileOptions&& from) noexcept
      : SharkFileOptions(nullptr, std::move(from)) {}
  inline SharkFileOptions& operator=(const SharkFileOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkFileOptions& operator=(SharkFileOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkFileOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkFileOptions* internal_default_instance() {
    return reinterpret_cast<const SharkFileOptions*>(
        &_SharkFileOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SharkFileOptions& a, SharkFileOptions& b) { a.Swap(&b); }
  inline void Swap(SharkFileOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkFileOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkFileOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkFileOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkFileOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkFileOptions& from) { SharkFileOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkFileOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkFileOptions"; }

 protected:
  explicit SharkFileOptions(::google::protobuf::Arena* arena);
  SharkFileOptions(::google::protobuf::Arena* arena, const SharkFileOptions& from);
  SharkFileOptions(::google::protobuf::Arena* arena, SharkFileOptions&& from) noexcept
      : SharkFileOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kRuntimeNamespaceFieldNumber = 1,
    kGenSkFieldNumber = 2,
    kEnumValueStyleFieldNumber = 3,
    kEnumStorageFieldNumber = 4,
    kEnumUnderlyingTypeFieldNumber = 5,
    kEnumStringSourceFieldNumber = 6,
  };
  // string runtime_namespace = 1;
  void clear_runtime_namespace() ;
  const std::string& runtime_namespace() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_runtime_namespace(Arg_&& arg, Args_... args);
  std::string* mutable_runtime_namespace();
  PROTOBUF_NODISCARD std::string* release_runtime_namespace();
  void set_allocated_runtime_namespace(std::string* value);

  private:
  const std::string& _internal_runtime_namespace() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_runtime_namespace(
      const std::string& value);
  std::string* _internal_mutable_runtime_namespace();

  public:
  // bool gen_sk = 2;
  void clear_gen_sk() ;
  bool gen_sk() const;
  void set_gen_sk(bool value);

  private:
  bool _internal_gen_sk() const;
  void _internal_set_gen_sk(bool value);

  public:
  // .shark.idl.EnumValueStyle enum_value_style = 3;
  void clear_enum_value_style() ;
  ::shark::idl::EnumValueStyle enum_value_style() const;
  void set_enum_value_style(::shark::idl::EnumValueStyle value);

  private:
  ::shark::idl::EnumValueStyle _internal_enum_value_style() const;
  void _internal_set_enum_value_style(::shark::idl::EnumValueStyle value);

  public:
  // .shark.idl.EnumStorageKind enum_storage = 4;
  void clear_enum_storage() ;
  ::shark::idl::EnumStorageKind enum_storage() const;
  void set_enum_storage(::shark::idl::EnumStorageKind value);

  private:
  ::shark::idl::EnumStorageKind _internal_enum_storage() const;
  void _internal_set_enum_storage(::shark::idl::EnumStorageKind value);

  public:
  // .shark.idl.EnumUnderlyingType enum_underlying_type = 5;
  void clear_enum_underlying_type() ;
  ::shark::idl::EnumUnderlyingType enum_underlying_type() const;
  void set_enum_underlying_type(::shark::idl::EnumUnderlyingType value);

  private:
  ::shark::idl::EnumUnderlyingType _internal_enum_underlying_type() const;
  void _internal_set_enum_underlying_type(::shark::idl::EnumUnderlyingType value);

  public:
  // .shark.idl.EnumStringSource enum_string_source = 6;
  void clear_enum_string_source() ;
  ::shark::idl::EnumStringSource enum_string_source() const;
  void set_enum_string_source(::shark::idl::EnumStringSource value);

  private:
  ::shark::idl::EnumStringSource _internal_enum_string_source() const;
  void _internal_set_enum_string_source(::shark::idl::EnumStringSource value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkFileOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 0,
      52, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkFileOptions& from_msg);
    ::google::protobuf::internal::ArenaStringPtr runtime_namespace_;
    bool gen_sk_;
    int enum_value_style_;
    int enum_storage_;
    int enum_underlying_type_;
    int enum_string_source_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkFieldOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkFieldOptions) */ {
 public:
  inline SharkFieldOptions() : SharkFieldOptions(nullptr) {}
  ~SharkFieldOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkFieldOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkFieldOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkFieldOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkFieldOptions(const SharkFieldOptions& from) : SharkFieldOptions(nullptr, from) {}
  inline SharkFieldOptions(SharkFieldOptions&& from) noexcept
      : SharkFieldOptions(nullptr, std::move(from)) {}
  inline SharkFieldOptions& operator=(const SharkFieldOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkFieldOptions& operator=(SharkFieldOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkFieldOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkFieldOptions* internal_default_instance() {
    return reinterpret_cast<const SharkFieldOptions*>(
        &_SharkFieldOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SharkFieldOptions& a, SharkFieldOptions& b) { a.Swap(&b); }
  inline void Swap(SharkFieldOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkFieldOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkFieldOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkFieldOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkFieldOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkFieldOptions& from) { SharkFieldOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkFieldOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkFieldOptions"; }

 protected:
  explicit SharkFieldOptions(::google::protobuf::Arena* arena);
  SharkFieldOptions(::google::protobuf::Arena* arena, const SharkFieldOptions& from);
  SharkFieldOptions(::google::protobuf::Arena* arena, SharkFieldOptions&& from) noexcept
      : SharkFieldOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCtypeFieldNumber = 1,
    kEnumValueStyleFieldNumber = 4,
    kEnumStorageFieldNumber = 5,
    kNullableFieldNumber = 2,
    kEnumUseAliasNameFieldNumber = 3,
    kEnumBitFlagsFieldNumber = 7,
    kEnumGenToStringFieldNumber = 8,
    kEnumUnderlyingTypeFieldNumber = 6,
    kEnumStringSourceFieldNumber = 9,
  };
  // string ctype = 1;
  void clear_ctype() ;
  const std::string& ctype() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ctype(Arg_&& arg, Args_... args);
  std::string* mutable_ctype();
  PROTOBUF_NODISCARD std::string* release_ctype();
  void set_allocated_ctype(std::string* value);

  private:
  const std::string& _internal_ctype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ctype(
      const std::string& value);
  std::string* _internal_mutable_ctype();

  public:
  // .shark.idl.EnumValueStyle enum_value_style = 4;
  void clear_enum_value_style() ;
  ::shark::idl::EnumValueStyle enum_value_style() const;
  void set_enum_value_style(::shark::idl::EnumValueStyle value);

  private:
  ::shark::idl::EnumValueStyle _internal_enum_value_style() const;
  void _internal_set_enum_value_style(::shark::idl::EnumValueStyle value);

  public:
  // .shark.idl.EnumStorageKind enum_storage = 5;
  void clear_enum_storage() ;
  ::shark::idl::EnumStorageKind enum_storage() const;
  void set_enum_storage(::shark::idl::EnumStorageKind value);

  private:
  ::shark::idl::EnumStorageKind _internal_enum_storage() const;
  void _internal_set_enum_storage(::shark::idl::EnumStorageKind value);

  public:
  // bool nullable = 2;
  void clear_nullable() ;
  bool nullable() const;
  void set_nullable(bool value);

  private:
  bool _internal_nullable() const;
  void _internal_set_nullable(bool value);

  public:
  // bool enum_use_alias_name = 3;
  void clear_enum_use_alias_name() ;
  bool enum_use_alias_name() const;
  void set_enum_use_alias_name(bool value);

  private:
  bool _internal_enum_use_alias_name() const;
  void _internal_set_enum_use_alias_name(bool value);

  public:
  // bool enum_bit_flags = 7;
  void clear_enum_bit_flags() ;
  bool enum_bit_flags() const;
  void set_enum_bit_flags(bool value);

  private:
  bool _internal_enum_bit_flags() const;
  void _internal_set_enum_bit_flags(bool value);

  public:
  // bool enum_gen_to_string = 8;
  void clear_enum_gen_to_string() ;
  bool enum_gen_to_string() const;
  void set_enum_gen_to_string(bool value);

  private:
  bool _internal_enum_gen_to_string() const;
  void _internal_set_enum_gen_to_string(bool value);

  public:
  // .shark.idl.EnumUnderlyingType enum_underlying_type = 6;
  void clear_enum_underlying_type() ;
  ::shark::idl::EnumUnderlyingType enum_underlying_type() const;
  void set_enum_underlying_type(::shark::idl::EnumUnderlyingType value);

  private:
  ::shark::idl::EnumUnderlyingType _internal_enum_underlying_type() const;
  void _internal_set_enum_underlying_type(::shark::idl::EnumUnderlyingType value);

  public:
  // .shark.idl.EnumStringSource enum_string_source = 9;
  void clear_enum_string_source() ;
  ::shark::idl::EnumStringSource enum_string_source() const;
  void set_enum_string_source(::shark::idl::EnumStringSource value);

  private:
  ::shark::idl::EnumStringSource _internal_enum_string_source() const;
  void _internal_set_enum_string_source(::shark::idl::EnumStringSource value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkFieldOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 0,
      49, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkFieldOptions& from_msg);
    ::google::protobuf::internal::ArenaStringPtr ctype_;
    int enum_value_style_;
    int enum_storage_;
    bool nullable_;
    bool enum_use_alias_name_;
    bool enum_bit_flags_;
    bool enum_gen_to_string_;
    int enum_underlying_type_;
    int enum_string_source_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkEnumOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkEnumOptions) */ {
 public:
  inline SharkEnumOptions() : SharkEnumOptions(nullptr) {}
  ~SharkEnumOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkEnumOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkEnumOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkEnumOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkEnumOptions(const SharkEnumOptions& from) : SharkEnumOptions(nullptr, from) {}
  inline SharkEnumOptions(SharkEnumOptions&& from) noexcept
      : SharkEnumOptions(nullptr, std::move(from)) {}
  inline SharkEnumOptions& operator=(const SharkEnumOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkEnumOptions& operator=(SharkEnumOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkEnumOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkEnumOptions* internal_default_instance() {
    return reinterpret_cast<const SharkEnumOptions*>(
        &_SharkEnumOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SharkEnumOptions& a, SharkEnumOptions& b) { a.Swap(&b); }
  inline void Swap(SharkEnumOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkEnumOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkEnumOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkEnumOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkEnumOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkEnumOptions& from) { SharkEnumOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkEnumOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkEnumOptions"; }

 protected:
  explicit SharkEnumOptions(::google::protobuf::Arena* arena);
  SharkEnumOptions(::google::protobuf::Arena* arena, const SharkEnumOptions& from);
  SharkEnumOptions(::google::protobuf::Arena* arena, SharkEnumOptions&& from) noexcept
      : SharkEnumOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kValueStyleFieldNumber = 1,
    kStorageFieldNumber = 2,
    kUnderlyingTypeFieldNumber = 3,
    kBitFlagsFieldNumber = 4,
    kGenToStringFieldNumber = 5,
    kGenFromStringFieldNumber = 6,
    kPreserveUnknownNumericFieldNumber = 8,
    kStringSourceFieldNumber = 7,
  };
  // .shark.idl.EnumValueStyle value_style = 1;
  void clear_value_style() ;
  ::shark::idl::EnumValueStyle value_style() const;
  void set_value_style(::shark::idl::EnumValueStyle value);

  private:
  ::shark::idl::EnumValueStyle _internal_value_style() const;
  void _internal_set_value_style(::shark::idl::EnumValueStyle value);

  public:
  // .shark.idl.EnumStorageKind storage = 2;
  void clear_storage() ;
  ::shark::idl::EnumStorageKind storage() const;
  void set_storage(::shark::idl::EnumStorageKind value);

  private:
  ::shark::idl::EnumStorageKind _internal_storage() const;
  void _internal_set_storage(::shark::idl::EnumStorageKind value);

  public:
  // .shark.idl.EnumUnderlyingType underlying_type = 3;
  void clear_underlying_type() ;
  ::shark::idl::EnumUnderlyingType underlying_type() const;
  void set_underlying_type(::shark::idl::EnumUnderlyingType value);

  private:
  ::shark::idl::EnumUnderlyingType _internal_underlying_type() const;
  void _internal_set_underlying_type(::shark::idl::EnumUnderlyingType value);

  public:
  // bool bit_flags = 4;
  void clear_bit_flags() ;
  bool bit_flags() const;
  void set_bit_flags(bool value);

  private:
  bool _internal_bit_flags() const;
  void _internal_set_bit_flags(bool value);

  public:
  // bool gen_to_string = 5;
  void clear_gen_to_string() ;
  bool gen_to_string() const;
  void set_gen_to_string(bool value);

  private:
  bool _internal_gen_to_string() const;
  void _internal_set_gen_to_string(bool value);

  public:
  // bool gen_from_string = 6;
  void clear_gen_from_string() ;
  bool gen_from_string() const;
  void set_gen_from_string(bool value);

  private:
  bool _internal_gen_from_string() const;
  void _internal_set_gen_from_string(bool value);

  public:
  // bool preserve_unknown_numeric = 8;
  void clear_preserve_unknown_numeric() ;
  bool preserve_unknown_numeric() const;
  void set_preserve_unknown_numeric(bool value);

  private:
  bool _internal_preserve_unknown_numeric() const;
  void _internal_set_preserve_unknown_numeric(bool value);

  public:
  // .shark.idl.EnumStringSource string_source = 7;
  void clear_string_source() ;
  ::shark::idl::EnumStringSource string_source() const;
  void set_string_source(::shark::idl::EnumStringSource value);

  private:
  ::shark::idl::EnumStringSource _internal_string_source() const;
  void _internal_set_string_source(::shark::idl::EnumStringSource value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkEnumOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 8, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkEnumOptions& from_msg);
    int value_style_;
    int storage_;
    int underlying_type_;
    bool bit_flags_;
    bool gen_to_string_;
    bool gen_from_string_;
    bool preserve_unknown_numeric_;
    int string_source_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};

// ===================================================================



static const int kSharkFileFieldNumber = 52001;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FileOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkFileOptions >, 11,
    false>
    shark_file;
static const int kSharkMessageFieldNumber = 52002;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkMessageOptions >, 11,
    false>
    shark_message;
static const int kSharkEnumFieldNumber = 52004;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkEnumOptions >, 11,
    false>
    shark_enum;
static const int kSharkFieldFieldNumber = 52003;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkFieldOptions >, 11,
    false>
    shark_field;

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SharkFileOptions

// string runtime_namespace = 1;
inline void SharkFileOptions::clear_runtime_namespace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.runtime_namespace_.ClearToEmpty();
}
inline const std::string& SharkFileOptions::runtime_namespace() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.runtime_namespace)
  return _internal_runtime_namespace();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFileOptions::set_runtime_namespace(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.runtime_namespace_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.runtime_namespace)
}
inline std::string* SharkFileOptions::mutable_runtime_namespace() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_runtime_namespace();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFileOptions.runtime_namespace)
  return _s;
}
inline const std::string& SharkFileOptions::_internal_runtime_namespace() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.runtime_namespace_.Get();
}
inline void SharkFileOptions::_internal_set_runtime_namespace(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.runtime_namespace_.Set(value, GetArena());
}
inline std::string* SharkFileOptions::_internal_mutable_runtime_namespace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.runtime_namespace_.Mutable( GetArena());
}
inline std::string* SharkFileOptions::release_runtime_namespace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFileOptions.runtime_namespace)
  return _impl_.runtime_namespace_.Release();
}
inline void SharkFileOptions::set_allocated_runtime_namespace(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.runtime_namespace_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.runtime_namespace_.IsDefault()) {
    _impl_.runtime_namespace_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFileOptions.runtime_namespace)
}

// bool gen_sk = 2;
inline void SharkFileOptions::clear_gen_sk() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_sk_ = false;
}
inline bool SharkFileOptions::gen_sk() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.gen_sk)
  return _internal_gen_sk();
}
inline void SharkFileOptions::set_gen_sk(bool value) {
  _internal_set_gen_sk(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.gen_sk)
}
inline bool SharkFileOptions::_internal_gen_sk() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gen_sk_;
}
inline void SharkFileOptions::_internal_set_gen_sk(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_sk_ = value;
}

// .shark.idl.EnumValueStyle enum_value_style = 3;
inline void SharkFileOptions::clear_enum_value_style() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_value_style_ = 0;
}
inline ::shark::idl::EnumValueStyle SharkFileOptions::enum_value_style() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.enum_value_style)
  return _internal_enum_value_style();
}
inline void SharkFileOptions::set_enum_value_style(::shark::idl::EnumValueStyle value) {
  _internal_set_enum_value_style(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.enum_value_style)
}
inline ::shark::idl::EnumValueStyle SharkFileOptions::_internal_enum_value_style() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumValueStyle>(_impl_.enum_value_style_);
}
inline void SharkFileOptions::_internal_set_enum_value_style(::shark::idl::EnumValueStyle value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_value_style_ = value;
}

// .shark.idl.EnumStorageKind enum_storage = 4;
inline void SharkFileOptions::clear_enum_storage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_storage_ = 0;
}
inline ::shark::idl::EnumStorageKind SharkFileOptions::enum_storage() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.enum_storage)
  return _internal_enum_storage();
}
inline void SharkFileOptions::set_enum_storage(::shark::idl::EnumStorageKind value) {
  _internal_set_enum_storage(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.enum_storage)
}
inline ::shark::idl::EnumStorageKind SharkFileOptions::_internal_enum_storage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumStorageKind>(_impl_.enum_storage_);
}
inline void SharkFileOptions::_internal_set_enum_storage(::shark::idl::EnumStorageKind value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_storage_ = value;
}

// .shark.idl.EnumUnderlyingType enum_underlying_type = 5;
inline void SharkFileOptions::clear_enum_underlying_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_underlying_type_ = 0;
}
inline ::shark::idl::EnumUnderlyingType SharkFileOptions::enum_underlying_type() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.enum_underlying_type)
  return _internal_enum_underlying_type();
}
inline void SharkFileOptions::set_enum_underlying_type(::shark::idl::EnumUnderlyingType value) {
  _internal_set_enum_underlying_type(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.enum_underlying_type)
}
inline ::shark::idl::EnumUnderlyingType SharkFileOptions::_internal_enum_underlying_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumUnderlyingType>(_impl_.enum_underlying_type_);
}
inline void SharkFileOptions::_internal_set_enum_underlying_type(::shark::idl::EnumUnderlyingType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_underlying_type_ = value;
}

// .shark.idl.EnumStringSource enum_string_source = 6;
inline void SharkFileOptions::clear_enum_string_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_string_source_ = 0;
}
inline ::shark::idl::EnumStringSource SharkFileOptions::enum_string_source() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.enum_string_source)
  return _internal_enum_string_source();
}
inline void SharkFileOptions::set_enum_string_source(::shark::idl::EnumStringSource value) {
  _internal_set_enum_string_source(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.enum_string_source)
}
inline ::shark::idl::EnumStringSource SharkFileOptions::_internal_enum_string_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumStringSource>(_impl_.enum_string_source_);
}
inline void SharkFileOptions::_internal_set_enum_string_source(::shark::idl::EnumStringSource value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_string_source_ = value;
}

// -------------------------------------------------------------------

// SharkEnumOptions

// .shark.idl.EnumValueStyle value_style = 1;
inline void SharkEnumOptions::clear_value_style() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_style_ = 0;
}
inline ::shark::idl::EnumValueStyle SharkEnumOptions::value_style() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.value_style)
  return _internal_value_style();
}
inline void SharkEnumOptions::set_value_style(::shark::idl::EnumValueStyle value) {
  _internal_set_value_style(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.value_style)
}
inline ::shark::idl::EnumValueStyle SharkEnumOptions::_internal_value_style() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumValueStyle>(_impl_.value_style_);
}
inline void SharkEnumOptions::_internal_set_value_style(::shark::idl::EnumValueStyle value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.value_style_ = value;
}

// .shark.idl.EnumStorageKind storage = 2;
inline void SharkEnumOptions::clear_storage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_ = 0;
}
inline ::shark::idl::EnumStorageKind SharkEnumOptions::storage() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.storage)
  return _internal_storage();
}
inline void SharkEnumOptions::set_storage(::shark::idl::EnumStorageKind value) {
  _internal_set_storage(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.storage)
}
inline ::shark::idl::EnumStorageKind SharkEnumOptions::_internal_storage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumStorageKind>(_impl_.storage_);
}
inline void SharkEnumOptions::_internal_set_storage(::shark::idl::EnumStorageKind value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.storage_ = value;
}

// .shark.idl.EnumUnderlyingType underlying_type = 3;
inline void SharkEnumOptions::clear_underlying_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_type_ = 0;
}
inline ::shark::idl::EnumUnderlyingType SharkEnumOptions::underlying_type() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.underlying_type)
  return _internal_underlying_type();
}
inline void SharkEnumOptions::set_underlying_type(::shark::idl::EnumUnderlyingType value) {
  _internal_set_underlying_type(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.underlying_type)
}
inline ::shark::idl::EnumUnderlyingType SharkEnumOptions::_internal_underlying_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumUnderlyingType>(_impl_.underlying_type_);
}
inline void SharkEnumOptions::_internal_set_underlying_type(::shark::idl::EnumUnderlyingType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_type_ = value;
}

// bool bit_flags = 4;
inline void SharkEnumOptions::clear_bit_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bit_flags_ = false;
}
inline bool SharkEnumOptions::bit_flags() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.bit_flags)
  return _internal_bit_flags();
}
inline void SharkEnumOptions::set_bit_flags(bool value) {
  _internal_set_bit_flags(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.bit_flags)
}
inline bool SharkEnumOptions::_internal_bit_flags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bit_flags_;
}
inline void SharkEnumOptions::_internal_set_bit_flags(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bit_flags_ = value;
}

// bool gen_to_string = 5;
inline void SharkEnumOptions::clear_gen_to_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_to_string_ = false;
}
inline bool SharkEnumOptions::gen_to_string() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.gen_to_string)
  return _internal_gen_to_string();
}
inline void SharkEnumOptions::set_gen_to_string(bool value) {
  _internal_set_gen_to_string(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.gen_to_string)
}
inline bool SharkEnumOptions::_internal_gen_to_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gen_to_string_;
}
inline void SharkEnumOptions::_internal_set_gen_to_string(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_to_string_ = value;
}

// bool gen_from_string = 6;
inline void SharkEnumOptions::clear_gen_from_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_from_string_ = false;
}
inline bool SharkEnumOptions::gen_from_string() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.gen_from_string)
  return _internal_gen_from_string();
}
inline void SharkEnumOptions::set_gen_from_string(bool value) {
  _internal_set_gen_from_string(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.gen_from_string)
}
inline bool SharkEnumOptions::_internal_gen_from_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gen_from_string_;
}
inline void SharkEnumOptions::_internal_set_gen_from_string(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_from_string_ = value;
}

// .shark.idl.EnumStringSource string_source = 7;
inline void SharkEnumOptions::clear_string_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_source_ = 0;
}
inline ::shark::idl::EnumStringSource SharkEnumOptions::string_source() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.string_source)
  return _internal_string_source();
}
inline void SharkEnumOptions::set_string_source(::shark::idl::EnumStringSource value) {
  _internal_set_string_source(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.string_source)
}
inline ::shark::idl::EnumStringSource SharkEnumOptions::_internal_string_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumStringSource>(_impl_.string_source_);
}
inline void SharkEnumOptions::_internal_set_string_source(::shark::idl::EnumStringSource value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_source_ = value;
}

// bool preserve_unknown_numeric = 8;
inline void SharkEnumOptions::clear_preserve_unknown_numeric() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.preserve_unknown_numeric_ = false;
}
inline bool SharkEnumOptions::preserve_unknown_numeric() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.preserve_unknown_numeric)
  return _internal_preserve_unknown_numeric();
}
inline void SharkEnumOptions::set_preserve_unknown_numeric(bool value) {
  _internal_set_preserve_unknown_numeric(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.preserve_unknown_numeric)
}
inline bool SharkEnumOptions::_internal_preserve_unknown_numeric() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.preserve_unknown_numeric_;
}
inline void SharkEnumOptions::_internal_set_preserve_unknown_numeric(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.preserve_unknown_numeric_ = value;
}

// -------------------------------------------------------------------

// SharkMessageOptions

// bool gen_owned = 1;
inline void SharkMessageOptions::clear_gen_owned() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_owned_ = false;
}
inline bool SharkMessageOptions::gen_owned() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkMessageOptions.gen_owned)
  return _internal_gen_owned();
}
inline void SharkMessageOptions::set_gen_owned(bool value) {
  _internal_set_gen_owned(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkMessageOptions.gen_owned)
}
inline bool SharkMessageOptions::_internal_gen_owned() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gen_owned_;
}
inline void SharkMessageOptions::_internal_set_gen_owned(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_owned_ = value;
}

// bool gen_view = 2;
inline void SharkMessageOptions::clear_gen_view() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_view_ = false;
}
inline bool SharkMessageOptions::gen_view() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkMessageOptions.gen_view)
  return _internal_gen_view();
}
inline void SharkMessageOptions::set_gen_view(bool value) {
  _internal_set_gen_view(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkMessageOptions.gen_view)
}
inline bool SharkMessageOptions::_internal_gen_view() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.gen_view_;
}
inline void SharkMessageOptions::_internal_set_gen_view(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.gen_view_ = value;
}

// -------------------------------------------------------------------

// SharkFieldOptions

// string ctype = 1;
inline void SharkFieldOptions::clear_ctype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ctype_.ClearToEmpty();
}
inline const std::string& SharkFieldOptions::ctype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.ctype)
  return _internal_ctype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFieldOptions::set_ctype(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ctype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.ctype)
}
inline std::string* SharkFieldOptions::mutable_ctype() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ctype();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFieldOptions.ctype)
  return _s;
}
inline const std::string& SharkFieldOptions::_internal_ctype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ctype_.Get();
}
inline void SharkFieldOptions::_internal_set_ctype(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ctype_.Set(value, GetArena());
}
inline std::string* SharkFieldOptions::_internal_mutable_ctype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.ctype_.Mutable( GetArena());
}
inline std::string* SharkFieldOptions::release_ctype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFieldOptions.ctype)
  return _impl_.ctype_.Release();
}
inline void SharkFieldOptions::set_allocated_ctype(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ctype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ctype_.IsDefault()) {
    _impl_.ctype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFieldOptions.ctype)
}

// bool nullable = 2;
inline void SharkFieldOptions::clear_nullable() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nullable_ = false;
}
inline bool SharkFieldOptions::nullable() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.nullable)
  return _internal_nullable();
}
inline void SharkFieldOptions::set_nullable(bool value) {
  _internal_set_nullable(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.nullable)
}
inline bool SharkFieldOptions::_internal_nullable() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.nullable_;
}
inline void SharkFieldOptions::_internal_set_nullable(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.nullable_ = value;
}

// bool enum_use_alias_name = 3;
inline void SharkFieldOptions::clear_enum_use_alias_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_use_alias_name_ = false;
}
inline bool SharkFieldOptions::enum_use_alias_name() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_use_alias_name)
  return _internal_enum_use_alias_name();
}
inline void SharkFieldOptions::set_enum_use_alias_name(bool value) {
  _internal_set_enum_use_alias_name(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_use_alias_name)
}
inline bool SharkFieldOptions::_internal_enum_use_alias_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enum_use_alias_name_;
}
inline void SharkFieldOptions::_internal_set_enum_use_alias_name(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_use_alias_name_ = value;
}

// .shark.idl.EnumValueStyle enum_value_style = 4;
inline void SharkFieldOptions::clear_enum_value_style() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_value_style_ = 0;
}
inline ::shark::idl::EnumValueStyle SharkFieldOptions::enum_value_style() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_value_style)
  return _internal_enum_value_style();
}
inline void SharkFieldOptions::set_enum_value_style(::shark::idl::EnumValueStyle value) {
  _internal_set_enum_value_style(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_value_style)
}
inline ::shark::idl::EnumValueStyle SharkFieldOptions::_internal_enum_value_style() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumValueStyle>(_impl_.enum_value_style_);
}
inline void SharkFieldOptions::_internal_set_enum_value_style(::shark::idl::EnumValueStyle value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_value_style_ = value;
}

// .shark.idl.EnumStorageKind enum_storage = 5;
inline void SharkFieldOptions::clear_enum_storage() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_storage_ = 0;
}
inline ::shark::idl::EnumStorageKind SharkFieldOptions::enum_storage() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_storage)
  return _internal_enum_storage();
}
inline void SharkFieldOptions::set_enum_storage(::shark::idl::EnumStorageKind value) {
  _internal_set_enum_storage(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_storage)
}
inline ::shark::idl::EnumStorageKind SharkFieldOptions::_internal_enum_storage() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumStorageKind>(_impl_.enum_storage_);
}
inline void SharkFieldOptions::_internal_set_enum_storage(::shark::idl::EnumStorageKind value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_storage_ = value;
}

// .shark.idl.EnumUnderlyingType enum_underlying_type = 6;
inline void SharkFieldOptions::clear_enum_underlying_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_underlying_type_ = 0;
}
inline ::shark::idl::EnumUnderlyingType SharkFieldOptions::enum_underlying_type() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_underlying_type)
  return _internal_enum_underlying_type();
}
inline void SharkFieldOptions::set_enum_underlying_type(::shark::idl::EnumUnderlyingType value) {
  _internal_set_enum_underlying_type(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_underlying_type)
}
inline ::shark::idl::EnumUnderlyingType SharkFieldOptions::_internal_enum_underlying_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumUnderlyingType>(_impl_.enum_underlying_type_);
}
inline void SharkFieldOptions::_internal_set_enum_underlying_type(::shark::idl::EnumUnderlyingType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_underlying_type_ = value;
}

// bool enum_bit_flags = 7;
inline void SharkFieldOptions::clear_enum_bit_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_bit_flags_ = false;
}
inline bool SharkFieldOptions::enum_bit_flags() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_bit_flags)
  return _internal_enum_bit_flags();
}
inline void SharkFieldOptions::set_enum_bit_flags(bool value) {
  _internal_set_enum_bit_flags(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_bit_flags)
}
inline bool SharkFieldOptions::_internal_enum_bit_flags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enum_bit_flags_;
}
inline void SharkFieldOptions::_internal_set_enum_bit_flags(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_bit_flags_ = value;
}

// bool enum_gen_to_string = 8;
inline void SharkFieldOptions::clear_enum_gen_to_string() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_gen_to_string_ = false;
}
inline bool SharkFieldOptions::enum_gen_to_string() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_gen_to_string)
  return _internal_enum_gen_to_string();
}
inline void SharkFieldOptions::set_enum_gen_to_string(bool value) {
  _internal_set_enum_gen_to_string(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_gen_to_string)
}
inline bool SharkFieldOptions::_internal_enum_gen_to_string() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.enum_gen_to_string_;
}
inline void SharkFieldOptions::_internal_set_enum_gen_to_string(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_gen_to_string_ = value;
}

// .shark.idl.EnumStringSource enum_string_source = 9;
inline void SharkFieldOptions::clear_enum_string_source() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_string_source_ = 0;
}
inline ::shark::idl::EnumStringSource SharkFieldOptions::enum_string_source() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.enum_string_source)
  return _internal_enum_string_source();
}
inline void SharkFieldOptions::set_enum_string_source(::shark::idl::EnumStringSource value) {
  _internal_set_enum_string_source(value);
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.enum_string_source)
}
inline ::shark::idl::EnumStringSource SharkFieldOptions::_internal_enum_string_source() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumStringSource>(_impl_.enum_string_source_);
}
inline void SharkFieldOptions::_internal_set_enum_string_source(::shark::idl::EnumStringSource value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.enum_string_source_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace idl
}  // namespace shark


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::shark::idl::EnumValueStyle> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::EnumValueStyle>() {
  return ::shark::idl::EnumValueStyle_descriptor();
}
template <>
struct is_proto_enum<::shark::idl::EnumStorageKind> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::EnumStorageKind>() {
  return ::shark::idl::EnumStorageKind_descriptor();
}
template <>
struct is_proto_enum<::shark::idl::EnumUnderlyingType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::EnumUnderlyingType>() {
  return ::shark::idl::EnumUnderlyingType_descriptor();
}
template <>
struct is_proto_enum<::shark::idl::EnumStringSource> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::EnumStringSource>() {
  return ::shark::idl::EnumStringSource_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // shark_2fidl_2fshark_5foptions_2eproto_2epb_2eh
