// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: shark/idl/shark_options.proto
// Protobuf C++ Version: 5.29.5

#ifndef shark_2fidl_2fshark_5foptions_2eproto_2epb_2eh
#define shark_2fidl_2fshark_5foptions_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/generated_enum_reflection.h"
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/descriptor.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_shark_2fidl_2fshark_5foptions_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_shark_2fidl_2fshark_5foptions_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_shark_2fidl_2fshark_5foptions_2eproto;
namespace shark {
namespace idl {
class SharkEnumOptions;
struct SharkEnumOptionsDefaultTypeInternal;
extern SharkEnumOptionsDefaultTypeInternal _SharkEnumOptions_default_instance_;
class SharkEnumValueOptions;
struct SharkEnumValueOptionsDefaultTypeInternal;
extern SharkEnumValueOptionsDefaultTypeInternal _SharkEnumValueOptions_default_instance_;
class SharkFieldOptions;
struct SharkFieldOptionsDefaultTypeInternal;
extern SharkFieldOptionsDefaultTypeInternal _SharkFieldOptions_default_instance_;
class SharkFileOptions;
struct SharkFileOptionsDefaultTypeInternal;
extern SharkFileOptionsDefaultTypeInternal _SharkFileOptions_default_instance_;
class SharkMessageOptions;
struct SharkMessageOptionsDefaultTypeInternal;
extern SharkMessageOptionsDefaultTypeInternal _SharkMessageOptions_default_instance_;
}  // namespace idl
}  // namespace shark
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace shark {
namespace idl {
enum EnumUnderlyingType : int {
  ENUM_UNDERLYING_UNSPECIFIED = 0,
  ENUM_UNDERLYING_U8 = 1,
  ENUM_UNDERLYING_U16 = 2,
  ENUM_UNDERLYING_U32 = 3,
};

bool EnumUnderlyingType_IsValid(int value);
extern const uint32_t EnumUnderlyingType_internal_data_[];
constexpr EnumUnderlyingType EnumUnderlyingType_MIN = static_cast<EnumUnderlyingType>(0);
constexpr EnumUnderlyingType EnumUnderlyingType_MAX = static_cast<EnumUnderlyingType>(3);
constexpr int EnumUnderlyingType_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
EnumUnderlyingType_descriptor();
template <typename T>
const std::string& EnumUnderlyingType_Name(T value) {
  static_assert(std::is_same<T, EnumUnderlyingType>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnumUnderlyingType_Name().");
  return EnumUnderlyingType_Name(static_cast<EnumUnderlyingType>(value));
}
template <>
inline const std::string& EnumUnderlyingType_Name(EnumUnderlyingType value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EnumUnderlyingType_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool EnumUnderlyingType_Parse(absl::string_view name, EnumUnderlyingType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumUnderlyingType>(
      EnumUnderlyingType_descriptor(), name, value);
}
enum EnumStringSource : int {
  ENUM_STRING_SOURCE_UNSPECIFIED = 0,
  ENUM_STRING_SOURCE_PROTO_REFLECTION = 1,
  ENUM_STRING_SOURCE_CUSTOM_TABLE = 2,
};

bool EnumStringSource_IsValid(int value);
extern const uint32_t EnumStringSource_internal_data_[];
constexpr EnumStringSource EnumStringSource_MIN = static_cast<EnumStringSource>(0);
constexpr EnumStringSource EnumStringSource_MAX = static_cast<EnumStringSource>(2);
constexpr int EnumStringSource_ARRAYSIZE = 2 + 1;
const ::google::protobuf::EnumDescriptor*
EnumStringSource_descriptor();
template <typename T>
const std::string& EnumStringSource_Name(T value) {
  static_assert(std::is_same<T, EnumStringSource>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to EnumStringSource_Name().");
  return EnumStringSource_Name(static_cast<EnumStringSource>(value));
}
template <>
inline const std::string& EnumStringSource_Name(EnumStringSource value) {
  return ::google::protobuf::internal::NameOfDenseEnum<EnumStringSource_descriptor,
                                                 0, 2>(
      static_cast<int>(value));
}
inline bool EnumStringSource_Parse(absl::string_view name, EnumStringSource* value) {
  return ::google::protobuf::internal::ParseNamedEnum<EnumStringSource>(
      EnumStringSource_descriptor(), name, value);
}
enum CppStand : int {
  CXX_UNSPECIFIED = 0,
  CXX_17 = 1,
  CXX_20 = 2,
  CXX_23 = 3,
};

bool CppStand_IsValid(int value);
extern const uint32_t CppStand_internal_data_[];
constexpr CppStand CppStand_MIN = static_cast<CppStand>(0);
constexpr CppStand CppStand_MAX = static_cast<CppStand>(3);
constexpr int CppStand_ARRAYSIZE = 3 + 1;
const ::google::protobuf::EnumDescriptor*
CppStand_descriptor();
template <typename T>
const std::string& CppStand_Name(T value) {
  static_assert(std::is_same<T, CppStand>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to CppStand_Name().");
  return CppStand_Name(static_cast<CppStand>(value));
}
template <>
inline const std::string& CppStand_Name(CppStand value) {
  return ::google::protobuf::internal::NameOfDenseEnum<CppStand_descriptor,
                                                 0, 3>(
      static_cast<int>(value));
}
inline bool CppStand_Parse(absl::string_view name, CppStand* value) {
  return ::google::protobuf::internal::ParseNamedEnum<CppStand>(
      CppStand_descriptor(), name, value);
}
enum SharkEdition : int {
  EDITION_UNSPECIFIED = 0,
  SK_EDITION = 2026,
};

bool SharkEdition_IsValid(int value);
extern const uint32_t SharkEdition_internal_data_[];
constexpr SharkEdition SharkEdition_MIN = static_cast<SharkEdition>(0);
constexpr SharkEdition SharkEdition_MAX = static_cast<SharkEdition>(2026);
constexpr int SharkEdition_ARRAYSIZE = 2026 + 1;
const ::google::protobuf::EnumDescriptor*
SharkEdition_descriptor();
template <typename T>
const std::string& SharkEdition_Name(T value) {
  static_assert(std::is_same<T, SharkEdition>::value ||
                    std::is_integral<T>::value,
                "Incorrect type passed to SharkEdition_Name().");
  return ::google::protobuf::internal::NameOfEnum(SharkEdition_descriptor(), value);
}
inline bool SharkEdition_Parse(absl::string_view name, SharkEdition* value) {
  return ::google::protobuf::internal::ParseNamedEnum<SharkEdition>(
      SharkEdition_descriptor(), name, value);
}

// ===================================================================


// -------------------------------------------------------------------

class SharkMessageOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkMessageOptions) */ {
 public:
  inline SharkMessageOptions() : SharkMessageOptions(nullptr) {}
  ~SharkMessageOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkMessageOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkMessageOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkMessageOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkMessageOptions(const SharkMessageOptions& from) : SharkMessageOptions(nullptr, from) {}
  inline SharkMessageOptions(SharkMessageOptions&& from) noexcept
      : SharkMessageOptions(nullptr, std::move(from)) {}
  inline SharkMessageOptions& operator=(const SharkMessageOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkMessageOptions& operator=(SharkMessageOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkMessageOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkMessageOptions* internal_default_instance() {
    return reinterpret_cast<const SharkMessageOptions*>(
        &_SharkMessageOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(SharkMessageOptions& a, SharkMessageOptions& b) { a.Swap(&b); }
  inline void Swap(SharkMessageOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkMessageOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkMessageOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkMessageOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkMessageOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkMessageOptions& from) { SharkMessageOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkMessageOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkMessageOptions"; }

 protected:
  explicit SharkMessageOptions(::google::protobuf::Arena* arena);
  SharkMessageOptions(::google::protobuf::Arena* arena, const SharkMessageOptions& from);
  SharkMessageOptions(::google::protobuf::Arena* arena, SharkMessageOptions&& from) noexcept
      : SharkMessageOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kVirtualDtorFieldNumber = 1,
    kPrivateCtorFieldNumber = 2,
    kIsInstanceFieldNumber = 3,
  };
  // optional bool virtual_dtor = 1;
  bool has_virtual_dtor() const;
  void clear_virtual_dtor() ;
  bool virtual_dtor() const;
  void set_virtual_dtor(bool value);

  private:
  bool _internal_virtual_dtor() const;
  void _internal_set_virtual_dtor(bool value);

  public:
  // optional bool private_ctor = 2;
  bool has_private_ctor() const;
  void clear_private_ctor() ;
  bool private_ctor() const;
  void set_private_ctor(bool value);

  private:
  bool _internal_private_ctor() const;
  void _internal_set_private_ctor(bool value);

  public:
  // optional bool is_instance = 3;
  bool has_is_instance() const;
  void clear_is_instance() ;
  bool is_instance() const;
  void set_is_instance(bool value);

  private:
  bool _internal_is_instance() const;
  void _internal_set_is_instance(bool value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkMessageOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkMessageOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    bool virtual_dtor_;
    bool private_ctor_;
    bool is_instance_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkFileOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkFileOptions) */ {
 public:
  inline SharkFileOptions() : SharkFileOptions(nullptr) {}
  ~SharkFileOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkFileOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkFileOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkFileOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkFileOptions(const SharkFileOptions& from) : SharkFileOptions(nullptr, from) {}
  inline SharkFileOptions(SharkFileOptions&& from) noexcept
      : SharkFileOptions(nullptr, std::move(from)) {}
  inline SharkFileOptions& operator=(const SharkFileOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkFileOptions& operator=(SharkFileOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkFileOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkFileOptions* internal_default_instance() {
    return reinterpret_cast<const SharkFileOptions*>(
        &_SharkFileOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(SharkFileOptions& a, SharkFileOptions& b) { a.Swap(&b); }
  inline void Swap(SharkFileOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkFileOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkFileOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkFileOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkFileOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkFileOptions& from) { SharkFileOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkFileOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkFileOptions"; }

 protected:
  explicit SharkFileOptions(::google::protobuf::Arena* arena);
  SharkFileOptions(::google::protobuf::Arena* arena, const SharkFileOptions& from);
  SharkFileOptions(::google::protobuf::Arena* arena, SharkFileOptions&& from) noexcept
      : SharkFileOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCppIncludesFieldNumber = 2,
    kRuntimeNamespaceFieldNumber = 1,
    kSkMapTypeFieldNumber = 3,
    kSkVectorFieldNumber = 4,
    kCPackageFieldNumber = 15,
    kNoGenerateFieldNumber = 10,
    kUseOneofFieldNameFieldNumber = 14,
    kSkStandFieldNumber = 5,
    kEditionFieldNumber = 6,
  };
  // repeated string cpp_includes = 2;
  int cpp_includes_size() const;
  private:
  int _internal_cpp_includes_size() const;

  public:
  void clear_cpp_includes() ;
  const std::string& cpp_includes(int index) const;
  std::string* mutable_cpp_includes(int index);
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_cpp_includes(int index, Arg_&& value, Args_... args);
  std::string* add_cpp_includes();
  template <typename Arg_ = const std::string&, typename... Args_>
  void add_cpp_includes(Arg_&& value, Args_... args);
  const ::google::protobuf::RepeatedPtrField<std::string>& cpp_includes() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_cpp_includes();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_cpp_includes() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_cpp_includes();

  public:
  // optional string runtime_namespace = 1;
  bool has_runtime_namespace() const;
  void clear_runtime_namespace() ;
  const std::string& runtime_namespace() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_runtime_namespace(Arg_&& arg, Args_... args);
  std::string* mutable_runtime_namespace();
  PROTOBUF_NODISCARD std::string* release_runtime_namespace();
  void set_allocated_runtime_namespace(std::string* value);

  private:
  const std::string& _internal_runtime_namespace() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_runtime_namespace(
      const std::string& value);
  std::string* _internal_mutable_runtime_namespace();

  public:
  // optional string sk_map_type = 3 [default = "std::unordered_map<%s, %s>"];
  bool has_sk_map_type() const;
  void clear_sk_map_type() ;
  const std::string& sk_map_type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sk_map_type(Arg_&& arg, Args_... args);
  std::string* mutable_sk_map_type();
  PROTOBUF_NODISCARD std::string* release_sk_map_type();
  void set_allocated_sk_map_type(std::string* value);

  private:
  const std::string& _internal_sk_map_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sk_map_type(
      const std::string& value);
  std::string* _internal_mutable_sk_map_type();

  public:
  // optional string sk_vector = 4 [default = "std::vector<%s>"];
  bool has_sk_vector() const;
  void clear_sk_vector() ;
  const std::string& sk_vector() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sk_vector(Arg_&& arg, Args_... args);
  std::string* mutable_sk_vector();
  PROTOBUF_NODISCARD std::string* release_sk_vector();
  void set_allocated_sk_vector(std::string* value);

  private:
  const std::string& _internal_sk_vector() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sk_vector(
      const std::string& value);
  std::string* _internal_mutable_sk_vector();

  public:
  // optional string c_package = 15;
  bool has_c_package() const;
  void clear_c_package() ;
  const std::string& c_package() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_c_package(Arg_&& arg, Args_... args);
  std::string* mutable_c_package();
  PROTOBUF_NODISCARD std::string* release_c_package();
  void set_allocated_c_package(std::string* value);

  private:
  const std::string& _internal_c_package() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_c_package(
      const std::string& value);
  std::string* _internal_mutable_c_package();

  public:
  // optional bool no_generate = 10 [default = false];
  bool has_no_generate() const;
  void clear_no_generate() ;
  bool no_generate() const;
  void set_no_generate(bool value);

  private:
  bool _internal_no_generate() const;
  void _internal_set_no_generate(bool value);

  public:
  // optional bool use_oneof_field_name = 14 [default = false];
  bool has_use_oneof_field_name() const;
  void clear_use_oneof_field_name() ;
  bool use_oneof_field_name() const;
  void set_use_oneof_field_name(bool value);

  private:
  bool _internal_use_oneof_field_name() const;
  void _internal_set_use_oneof_field_name(bool value);

  public:
  // optional .shark.idl.CppStand sk_stand = 5 [default = CXX_17];
  bool has_sk_stand() const;
  void clear_sk_stand() ;
  ::shark::idl::CppStand sk_stand() const;
  void set_sk_stand(::shark::idl::CppStand value);

  private:
  ::shark::idl::CppStand _internal_sk_stand() const;
  void _internal_set_sk_stand(::shark::idl::CppStand value);

  public:
  // optional .shark.idl.SharkEdition edition = 6 [default = SK_EDITION];
  bool has_edition() const;
  void clear_edition() ;
  ::shark::idl::SharkEdition edition() const;
  void set_edition(::shark::idl::SharkEdition value);

  private:
  ::shark::idl::SharkEdition _internal_edition() const;
  void _internal_set_edition(::shark::idl::SharkEdition value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkFileOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      4, 9, 2,
      101, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkFileOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> cpp_includes_;
    ::google::protobuf::internal::ArenaStringPtr runtime_namespace_;
    static const ::google::protobuf::internal::LazyString _i_give_permission_to_break_this_code_default_sk_map_type_;
    ::google::protobuf::internal::ArenaStringPtr sk_map_type_;
    static const ::google::protobuf::internal::LazyString _i_give_permission_to_break_this_code_default_sk_vector_;
    ::google::protobuf::internal::ArenaStringPtr sk_vector_;
    ::google::protobuf::internal::ArenaStringPtr c_package_;
    bool no_generate_;
    bool use_oneof_field_name_;
    int sk_stand_;
    int edition_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkFieldOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkFieldOptions) */ {
 public:
  inline SharkFieldOptions() : SharkFieldOptions(nullptr) {}
  ~SharkFieldOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkFieldOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkFieldOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkFieldOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkFieldOptions(const SharkFieldOptions& from) : SharkFieldOptions(nullptr, from) {}
  inline SharkFieldOptions(SharkFieldOptions&& from) noexcept
      : SharkFieldOptions(nullptr, std::move(from)) {}
  inline SharkFieldOptions& operator=(const SharkFieldOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkFieldOptions& operator=(SharkFieldOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkFieldOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkFieldOptions* internal_default_instance() {
    return reinterpret_cast<const SharkFieldOptions*>(
        &_SharkFieldOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(SharkFieldOptions& a, SharkFieldOptions& b) { a.Swap(&b); }
  inline void Swap(SharkFieldOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkFieldOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkFieldOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkFieldOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkFieldOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkFieldOptions& from) { SharkFieldOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkFieldOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkFieldOptions"; }

 protected:
  explicit SharkFieldOptions(::google::protobuf::Arena* arena);
  SharkFieldOptions(::google::protobuf::Arena* arena, const SharkFieldOptions& from);
  SharkFieldOptions(::google::protobuf::Arena* arena, SharkFieldOptions&& from) noexcept
      : SharkFieldOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kCtypeFieldNumber = 1,
    kIsAtomicFieldNumber = 2,
    kStringAsBytesFieldNumber = 11,
  };
  // optional string ctype = 1;
  bool has_ctype() const;
  void clear_ctype() ;
  const std::string& ctype() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_ctype(Arg_&& arg, Args_... args);
  std::string* mutable_ctype();
  PROTOBUF_NODISCARD std::string* release_ctype();
  void set_allocated_ctype(std::string* value);

  private:
  const std::string& _internal_ctype() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_ctype(
      const std::string& value);
  std::string* _internal_mutable_ctype();

  public:
  // optional bool is_atomic = 2;
  bool has_is_atomic() const;
  void clear_is_atomic() ;
  bool is_atomic() const;
  void set_is_atomic(bool value);

  private:
  bool _internal_is_atomic() const;
  void _internal_set_is_atomic(bool value);

  public:
  // optional bool string_as_bytes = 11 [default = false];
  bool has_string_as_bytes() const;
  void clear_string_as_bytes() ;
  bool string_as_bytes() const;
  void set_string_as_bytes(bool value);

  private:
  bool _internal_string_as_bytes() const;
  void _internal_set_string_as_bytes(bool value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkFieldOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      41, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkFieldOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr ctype_;
    bool is_atomic_;
    bool string_as_bytes_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkEnumValueOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkEnumValueOptions) */ {
 public:
  inline SharkEnumValueOptions() : SharkEnumValueOptions(nullptr) {}
  ~SharkEnumValueOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkEnumValueOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkEnumValueOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkEnumValueOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkEnumValueOptions(const SharkEnumValueOptions& from) : SharkEnumValueOptions(nullptr, from) {}
  inline SharkEnumValueOptions(SharkEnumValueOptions&& from) noexcept
      : SharkEnumValueOptions(nullptr, std::move(from)) {}
  inline SharkEnumValueOptions& operator=(const SharkEnumValueOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkEnumValueOptions& operator=(SharkEnumValueOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkEnumValueOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkEnumValueOptions* internal_default_instance() {
    return reinterpret_cast<const SharkEnumValueOptions*>(
        &_SharkEnumValueOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 4;
  friend void swap(SharkEnumValueOptions& a, SharkEnumValueOptions& b) { a.Swap(&b); }
  inline void Swap(SharkEnumValueOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkEnumValueOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkEnumValueOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkEnumValueOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkEnumValueOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkEnumValueOptions& from) { SharkEnumValueOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkEnumValueOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkEnumValueOptions"; }

 protected:
  explicit SharkEnumValueOptions(::google::protobuf::Arena* arena);
  SharkEnumValueOptions(::google::protobuf::Arena* arena, const SharkEnumValueOptions& from);
  SharkEnumValueOptions(::google::protobuf::Arena* arena, SharkEnumValueOptions&& from) noexcept
      : SharkEnumValueOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kSkEnumNameFieldNumber = 1,
  };
  // optional string sk_enum_name = 1;
  bool has_sk_enum_name() const;
  void clear_sk_enum_name() ;
  const std::string& sk_enum_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_sk_enum_name(Arg_&& arg, Args_... args);
  std::string* mutable_sk_enum_name();
  PROTOBUF_NODISCARD std::string* release_sk_enum_name();
  void set_allocated_sk_enum_name(std::string* value);

  private:
  const std::string& _internal_sk_enum_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_sk_enum_name(
      const std::string& value);
  std::string* _internal_mutable_sk_enum_name();

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkEnumValueOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      0, 1, 0,
      52, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkEnumValueOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::internal::ArenaStringPtr sk_enum_name_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};
// -------------------------------------------------------------------

class SharkEnumOptions final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:shark.idl.SharkEnumOptions) */ {
 public:
  inline SharkEnumOptions() : SharkEnumOptions(nullptr) {}
  ~SharkEnumOptions() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(SharkEnumOptions* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(SharkEnumOptions));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR SharkEnumOptions(
      ::google::protobuf::internal::ConstantInitialized);

  inline SharkEnumOptions(const SharkEnumOptions& from) : SharkEnumOptions(nullptr, from) {}
  inline SharkEnumOptions(SharkEnumOptions&& from) noexcept
      : SharkEnumOptions(nullptr, std::move(from)) {}
  inline SharkEnumOptions& operator=(const SharkEnumOptions& from) {
    CopyFrom(from);
    return *this;
  }
  inline SharkEnumOptions& operator=(SharkEnumOptions&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SharkEnumOptions& default_instance() {
    return *internal_default_instance();
  }
  static inline const SharkEnumOptions* internal_default_instance() {
    return reinterpret_cast<const SharkEnumOptions*>(
        &_SharkEnumOptions_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(SharkEnumOptions& a, SharkEnumOptions& b) { a.Swap(&b); }
  inline void Swap(SharkEnumOptions* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SharkEnumOptions* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  SharkEnumOptions* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<SharkEnumOptions>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const SharkEnumOptions& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const SharkEnumOptions& from) { SharkEnumOptions::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(SharkEnumOptions* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "shark.idl.SharkEnumOptions"; }

 protected:
  explicit SharkEnumOptions(::google::protobuf::Arena* arena);
  SharkEnumOptions(::google::protobuf::Arena* arena, const SharkEnumOptions& from);
  SharkEnumOptions(::google::protobuf::Arena* arena, SharkEnumOptions&& from) noexcept
      : SharkEnumOptions(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kUnderlyingTypeFieldNumber = 1,
    kBitFlagsFieldNumber = 4,
  };
  // optional .shark.idl.EnumUnderlyingType underlying_type = 1 [default = ENUM_UNDERLYING_UNSPECIFIED];
  bool has_underlying_type() const;
  void clear_underlying_type() ;
  ::shark::idl::EnumUnderlyingType underlying_type() const;
  void set_underlying_type(::shark::idl::EnumUnderlyingType value);

  private:
  ::shark::idl::EnumUnderlyingType _internal_underlying_type() const;
  void _internal_set_underlying_type(::shark::idl::EnumUnderlyingType value);

  public:
  // optional bool bit_flags = 4;
  bool has_bit_flags() const;
  void clear_bit_flags() ;
  bool bit_flags() const;
  void set_bit_flags(bool value);

  private:
  bool _internal_bit_flags() const;
  void _internal_set_bit_flags(bool value);

  public:
  // @@protoc_insertion_point(class_scope:shark.idl.SharkEnumOptions)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 1,
      0, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const SharkEnumOptions& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    int underlying_type_;
    bool bit_flags_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_shark_2fidl_2fshark_5foptions_2eproto;
};

// ===================================================================



static const int kSharkFileFieldNumber = 52001;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FileOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkFileOptions >, 11,
    false>
    shark_file;
static const int kSharkMessageFieldNumber = 52002;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::MessageOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkMessageOptions >, 11,
    false>
    shark_message;
static const int kSharkEnumFieldNumber = 52004;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkEnumOptions >, 11,
    false>
    shark_enum;
static const int kSkEnumValueFieldNumber = 52005;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::EnumValueOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkEnumValueOptions >, 11,
    false>
    sk_enum_value;
static const int kSharkFieldFieldNumber = 52006;
extern ::google::protobuf::internal::ExtensionIdentifier<
    ::google::protobuf::FieldOptions, ::google::protobuf::internal::MessageTypeTraits< ::shark::idl::SharkFieldOptions >, 11,
    false>
    shark_field;

// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// SharkFileOptions

// optional string runtime_namespace = 1;
inline bool SharkFileOptions::has_runtime_namespace() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SharkFileOptions::clear_runtime_namespace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.runtime_namespace_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SharkFileOptions::runtime_namespace() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.runtime_namespace)
  return _internal_runtime_namespace();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFileOptions::set_runtime_namespace(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.runtime_namespace_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.runtime_namespace)
}
inline std::string* SharkFileOptions::mutable_runtime_namespace() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_runtime_namespace();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFileOptions.runtime_namespace)
  return _s;
}
inline const std::string& SharkFileOptions::_internal_runtime_namespace() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.runtime_namespace_.Get();
}
inline void SharkFileOptions::_internal_set_runtime_namespace(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.runtime_namespace_.Set(value, GetArena());
}
inline std::string* SharkFileOptions::_internal_mutable_runtime_namespace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.runtime_namespace_.Mutable( GetArena());
}
inline std::string* SharkFileOptions::release_runtime_namespace() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFileOptions.runtime_namespace)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.runtime_namespace_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.runtime_namespace_.Set("", GetArena());
  }
  return released;
}
inline void SharkFileOptions::set_allocated_runtime_namespace(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.runtime_namespace_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.runtime_namespace_.IsDefault()) {
    _impl_.runtime_namespace_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFileOptions.runtime_namespace)
}

// repeated string cpp_includes = 2;
inline int SharkFileOptions::_internal_cpp_includes_size() const {
  return _internal_cpp_includes().size();
}
inline int SharkFileOptions::cpp_includes_size() const {
  return _internal_cpp_includes_size();
}
inline void SharkFileOptions::clear_cpp_includes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cpp_includes_.Clear();
}
inline std::string* SharkFileOptions::add_cpp_includes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  std::string* _s = _internal_mutable_cpp_includes()->Add();
  // @@protoc_insertion_point(field_add_mutable:shark.idl.SharkFileOptions.cpp_includes)
  return _s;
}
inline const std::string& SharkFileOptions::cpp_includes(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.cpp_includes)
  return _internal_cpp_includes().Get(index);
}
inline std::string* SharkFileOptions::mutable_cpp_includes(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFileOptions.cpp_includes)
  return _internal_mutable_cpp_includes()->Mutable(index);
}
template <typename Arg_, typename... Args_>
inline void SharkFileOptions::set_cpp_includes(int index, Arg_&& value, Args_... args) {
  ::google::protobuf::internal::AssignToString(
      *_internal_mutable_cpp_includes()->Mutable(index),
      std::forward<Arg_>(value), args... );
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.cpp_includes)
}
template <typename Arg_, typename... Args_>
inline void SharkFileOptions::add_cpp_includes(Arg_&& value, Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::google::protobuf::internal::AddToRepeatedPtrField(*_internal_mutable_cpp_includes(),
                               std::forward<Arg_>(value),
                               args... );
  // @@protoc_insertion_point(field_add:shark.idl.SharkFileOptions.cpp_includes)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
SharkFileOptions::cpp_includes() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:shark.idl.SharkFileOptions.cpp_includes)
  return _internal_cpp_includes();
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
SharkFileOptions::mutable_cpp_includes() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:shark.idl.SharkFileOptions.cpp_includes)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cpp_includes();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
SharkFileOptions::_internal_cpp_includes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cpp_includes_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
SharkFileOptions::_internal_mutable_cpp_includes() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cpp_includes_;
}

// optional string sk_map_type = 3 [default = "std::unordered_map<%s, %s>"];
inline bool SharkFileOptions::has_sk_map_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SharkFileOptions::clear_sk_map_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sk_map_type_.ClearToDefault(::shark::idl::SharkFileOptions::Impl_::_i_give_permission_to_break_this_code_default_sk_map_type_, GetArena());
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const std::string& SharkFileOptions::sk_map_type() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.sk_map_type)
  if (_impl_.sk_map_type_.IsDefault()) {
    return Impl_::_i_give_permission_to_break_this_code_default_sk_map_type_.get();
  }
  return _internal_sk_map_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFileOptions::set_sk_map_type(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sk_map_type_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.sk_map_type)
}
inline std::string* SharkFileOptions::mutable_sk_map_type() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sk_map_type();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFileOptions.sk_map_type)
  return _s;
}
inline const std::string& SharkFileOptions::_internal_sk_map_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sk_map_type_.Get();
}
inline void SharkFileOptions::_internal_set_sk_map_type(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  _impl_.sk_map_type_.Set(value, GetArena());
}
inline std::string* SharkFileOptions::_internal_mutable_sk_map_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000002u;
  return _impl_.sk_map_type_.Mutable(::shark::idl::SharkFileOptions::Impl_::_i_give_permission_to_break_this_code_default_sk_map_type_, GetArena());
}
inline std::string* SharkFileOptions::release_sk_map_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFileOptions.sk_map_type)
  if ((_impl_._has_bits_[0] & 0x00000002u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000002u;
  return _impl_.sk_map_type_.Release();
}
inline void SharkFileOptions::set_allocated_sk_map_type(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  _impl_.sk_map_type_.SetAllocated(value, GetArena());
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFileOptions.sk_map_type)
}

// optional string sk_vector = 4 [default = "std::vector<%s>"];
inline bool SharkFileOptions::has_sk_vector() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SharkFileOptions::clear_sk_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sk_vector_.ClearToDefault(::shark::idl::SharkFileOptions::Impl_::_i_give_permission_to_break_this_code_default_sk_vector_, GetArena());
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline const std::string& SharkFileOptions::sk_vector() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.sk_vector)
  if (_impl_.sk_vector_.IsDefault()) {
    return Impl_::_i_give_permission_to_break_this_code_default_sk_vector_.get();
  }
  return _internal_sk_vector();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFileOptions::set_sk_vector(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.sk_vector_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.sk_vector)
}
inline std::string* SharkFileOptions::mutable_sk_vector() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sk_vector();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFileOptions.sk_vector)
  return _s;
}
inline const std::string& SharkFileOptions::_internal_sk_vector() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sk_vector_.Get();
}
inline void SharkFileOptions::_internal_set_sk_vector(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  _impl_.sk_vector_.Set(value, GetArena());
}
inline std::string* SharkFileOptions::_internal_mutable_sk_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000004u;
  return _impl_.sk_vector_.Mutable(::shark::idl::SharkFileOptions::Impl_::_i_give_permission_to_break_this_code_default_sk_vector_, GetArena());
}
inline std::string* SharkFileOptions::release_sk_vector() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFileOptions.sk_vector)
  if ((_impl_._has_bits_[0] & 0x00000004u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000004u;
  return _impl_.sk_vector_.Release();
}
inline void SharkFileOptions::set_allocated_sk_vector(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000004u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000004u;
  }
  _impl_.sk_vector_.SetAllocated(value, GetArena());
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFileOptions.sk_vector)
}

// optional .shark.idl.CppStand sk_stand = 5 [default = CXX_17];
inline bool SharkFileOptions::has_sk_stand() const {
  bool value = (_impl_._has_bits_[0] & 0x00000040u) != 0;
  return value;
}
inline void SharkFileOptions::clear_sk_stand() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sk_stand_ = 1;
  _impl_._has_bits_[0] &= ~0x00000040u;
}
inline ::shark::idl::CppStand SharkFileOptions::sk_stand() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.sk_stand)
  return _internal_sk_stand();
}
inline void SharkFileOptions::set_sk_stand(::shark::idl::CppStand value) {
  _internal_set_sk_stand(value);
  _impl_._has_bits_[0] |= 0x00000040u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.sk_stand)
}
inline ::shark::idl::CppStand SharkFileOptions::_internal_sk_stand() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::CppStand>(_impl_.sk_stand_);
}
inline void SharkFileOptions::_internal_set_sk_stand(::shark::idl::CppStand value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::shark::idl::CppStand_IsValid(value));
  _impl_.sk_stand_ = value;
}

// optional .shark.idl.SharkEdition edition = 6 [default = SK_EDITION];
inline bool SharkFileOptions::has_edition() const {
  bool value = (_impl_._has_bits_[0] & 0x00000080u) != 0;
  return value;
}
inline void SharkFileOptions::clear_edition() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.edition_ = 2026;
  _impl_._has_bits_[0] &= ~0x00000080u;
}
inline ::shark::idl::SharkEdition SharkFileOptions::edition() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.edition)
  return _internal_edition();
}
inline void SharkFileOptions::set_edition(::shark::idl::SharkEdition value) {
  _internal_set_edition(value);
  _impl_._has_bits_[0] |= 0x00000080u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.edition)
}
inline ::shark::idl::SharkEdition SharkFileOptions::_internal_edition() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::SharkEdition>(_impl_.edition_);
}
inline void SharkFileOptions::_internal_set_edition(::shark::idl::SharkEdition value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::shark::idl::SharkEdition_IsValid(value));
  _impl_.edition_ = value;
}

// optional bool no_generate = 10 [default = false];
inline bool SharkFileOptions::has_no_generate() const {
  bool value = (_impl_._has_bits_[0] & 0x00000010u) != 0;
  return value;
}
inline void SharkFileOptions::clear_no_generate() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.no_generate_ = false;
  _impl_._has_bits_[0] &= ~0x00000010u;
}
inline bool SharkFileOptions::no_generate() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.no_generate)
  return _internal_no_generate();
}
inline void SharkFileOptions::set_no_generate(bool value) {
  _internal_set_no_generate(value);
  _impl_._has_bits_[0] |= 0x00000010u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.no_generate)
}
inline bool SharkFileOptions::_internal_no_generate() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.no_generate_;
}
inline void SharkFileOptions::_internal_set_no_generate(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.no_generate_ = value;
}

// optional bool use_oneof_field_name = 14 [default = false];
inline bool SharkFileOptions::has_use_oneof_field_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000020u) != 0;
  return value;
}
inline void SharkFileOptions::clear_use_oneof_field_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.use_oneof_field_name_ = false;
  _impl_._has_bits_[0] &= ~0x00000020u;
}
inline bool SharkFileOptions::use_oneof_field_name() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.use_oneof_field_name)
  return _internal_use_oneof_field_name();
}
inline void SharkFileOptions::set_use_oneof_field_name(bool value) {
  _internal_set_use_oneof_field_name(value);
  _impl_._has_bits_[0] |= 0x00000020u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.use_oneof_field_name)
}
inline bool SharkFileOptions::_internal_use_oneof_field_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.use_oneof_field_name_;
}
inline void SharkFileOptions::_internal_set_use_oneof_field_name(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.use_oneof_field_name_ = value;
}

// optional string c_package = 15;
inline bool SharkFileOptions::has_c_package() const {
  bool value = (_impl_._has_bits_[0] & 0x00000008u) != 0;
  return value;
}
inline void SharkFileOptions::clear_c_package() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.c_package_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000008u;
}
inline const std::string& SharkFileOptions::c_package() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFileOptions.c_package)
  return _internal_c_package();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFileOptions::set_c_package(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.c_package_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFileOptions.c_package)
}
inline std::string* SharkFileOptions::mutable_c_package() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_c_package();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFileOptions.c_package)
  return _s;
}
inline const std::string& SharkFileOptions::_internal_c_package() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.c_package_.Get();
}
inline void SharkFileOptions::_internal_set_c_package(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  _impl_.c_package_.Set(value, GetArena());
}
inline std::string* SharkFileOptions::_internal_mutable_c_package() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000008u;
  return _impl_.c_package_.Mutable( GetArena());
}
inline std::string* SharkFileOptions::release_c_package() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFileOptions.c_package)
  if ((_impl_._has_bits_[0] & 0x00000008u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000008u;
  auto* released = _impl_.c_package_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.c_package_.Set("", GetArena());
  }
  return released;
}
inline void SharkFileOptions::set_allocated_c_package(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000008u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000008u;
  }
  _impl_.c_package_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.c_package_.IsDefault()) {
    _impl_.c_package_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFileOptions.c_package)
}

// -------------------------------------------------------------------

// SharkEnumOptions

// optional .shark.idl.EnumUnderlyingType underlying_type = 1 [default = ENUM_UNDERLYING_UNSPECIFIED];
inline bool SharkEnumOptions::has_underlying_type() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SharkEnumOptions::clear_underlying_type() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.underlying_type_ = 0;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline ::shark::idl::EnumUnderlyingType SharkEnumOptions::underlying_type() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.underlying_type)
  return _internal_underlying_type();
}
inline void SharkEnumOptions::set_underlying_type(::shark::idl::EnumUnderlyingType value) {
  _internal_set_underlying_type(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.underlying_type)
}
inline ::shark::idl::EnumUnderlyingType SharkEnumOptions::_internal_underlying_type() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return static_cast<::shark::idl::EnumUnderlyingType>(_impl_.underlying_type_);
}
inline void SharkEnumOptions::_internal_set_underlying_type(::shark::idl::EnumUnderlyingType value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  assert(::shark::idl::EnumUnderlyingType_IsValid(value));
  _impl_.underlying_type_ = value;
}

// optional bool bit_flags = 4;
inline bool SharkEnumOptions::has_bit_flags() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SharkEnumOptions::clear_bit_flags() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bit_flags_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool SharkEnumOptions::bit_flags() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumOptions.bit_flags)
  return _internal_bit_flags();
}
inline void SharkEnumOptions::set_bit_flags(bool value) {
  _internal_set_bit_flags(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumOptions.bit_flags)
}
inline bool SharkEnumOptions::_internal_bit_flags() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bit_flags_;
}
inline void SharkEnumOptions::_internal_set_bit_flags(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bit_flags_ = value;
}

// -------------------------------------------------------------------

// SharkMessageOptions

// optional bool virtual_dtor = 1;
inline bool SharkMessageOptions::has_virtual_dtor() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SharkMessageOptions::clear_virtual_dtor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.virtual_dtor_ = false;
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline bool SharkMessageOptions::virtual_dtor() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkMessageOptions.virtual_dtor)
  return _internal_virtual_dtor();
}
inline void SharkMessageOptions::set_virtual_dtor(bool value) {
  _internal_set_virtual_dtor(value);
  _impl_._has_bits_[0] |= 0x00000001u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkMessageOptions.virtual_dtor)
}
inline bool SharkMessageOptions::_internal_virtual_dtor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.virtual_dtor_;
}
inline void SharkMessageOptions::_internal_set_virtual_dtor(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.virtual_dtor_ = value;
}

// optional bool private_ctor = 2;
inline bool SharkMessageOptions::has_private_ctor() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SharkMessageOptions::clear_private_ctor() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.private_ctor_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool SharkMessageOptions::private_ctor() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkMessageOptions.private_ctor)
  return _internal_private_ctor();
}
inline void SharkMessageOptions::set_private_ctor(bool value) {
  _internal_set_private_ctor(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkMessageOptions.private_ctor)
}
inline bool SharkMessageOptions::_internal_private_ctor() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.private_ctor_;
}
inline void SharkMessageOptions::_internal_set_private_ctor(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.private_ctor_ = value;
}

// optional bool is_instance = 3;
inline bool SharkMessageOptions::has_is_instance() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SharkMessageOptions::clear_is_instance() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_instance_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool SharkMessageOptions::is_instance() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkMessageOptions.is_instance)
  return _internal_is_instance();
}
inline void SharkMessageOptions::set_is_instance(bool value) {
  _internal_set_is_instance(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkMessageOptions.is_instance)
}
inline bool SharkMessageOptions::_internal_is_instance() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_instance_;
}
inline void SharkMessageOptions::_internal_set_is_instance(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_instance_ = value;
}

// -------------------------------------------------------------------

// SharkFieldOptions

// optional string ctype = 1;
inline bool SharkFieldOptions::has_ctype() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SharkFieldOptions::clear_ctype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.ctype_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SharkFieldOptions::ctype() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.ctype)
  return _internal_ctype();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkFieldOptions::set_ctype(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ctype_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.ctype)
}
inline std::string* SharkFieldOptions::mutable_ctype() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_ctype();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkFieldOptions.ctype)
  return _s;
}
inline const std::string& SharkFieldOptions::_internal_ctype() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.ctype_.Get();
}
inline void SharkFieldOptions::_internal_set_ctype(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.ctype_.Set(value, GetArena());
}
inline std::string* SharkFieldOptions::_internal_mutable_ctype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.ctype_.Mutable( GetArena());
}
inline std::string* SharkFieldOptions::release_ctype() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkFieldOptions.ctype)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.ctype_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.ctype_.Set("", GetArena());
  }
  return released;
}
inline void SharkFieldOptions::set_allocated_ctype(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.ctype_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.ctype_.IsDefault()) {
    _impl_.ctype_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkFieldOptions.ctype)
}

// optional bool is_atomic = 2;
inline bool SharkFieldOptions::has_is_atomic() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline void SharkFieldOptions::clear_is_atomic() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_atomic_ = false;
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline bool SharkFieldOptions::is_atomic() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.is_atomic)
  return _internal_is_atomic();
}
inline void SharkFieldOptions::set_is_atomic(bool value) {
  _internal_set_is_atomic(value);
  _impl_._has_bits_[0] |= 0x00000002u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.is_atomic)
}
inline bool SharkFieldOptions::_internal_is_atomic() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.is_atomic_;
}
inline void SharkFieldOptions::_internal_set_is_atomic(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.is_atomic_ = value;
}

// optional bool string_as_bytes = 11 [default = false];
inline bool SharkFieldOptions::has_string_as_bytes() const {
  bool value = (_impl_._has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline void SharkFieldOptions::clear_string_as_bytes() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_as_bytes_ = false;
  _impl_._has_bits_[0] &= ~0x00000004u;
}
inline bool SharkFieldOptions::string_as_bytes() const {
  // @@protoc_insertion_point(field_get:shark.idl.SharkFieldOptions.string_as_bytes)
  return _internal_string_as_bytes();
}
inline void SharkFieldOptions::set_string_as_bytes(bool value) {
  _internal_set_string_as_bytes(value);
  _impl_._has_bits_[0] |= 0x00000004u;
  // @@protoc_insertion_point(field_set:shark.idl.SharkFieldOptions.string_as_bytes)
}
inline bool SharkFieldOptions::_internal_string_as_bytes() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.string_as_bytes_;
}
inline void SharkFieldOptions::_internal_set_string_as_bytes(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.string_as_bytes_ = value;
}

// -------------------------------------------------------------------

// SharkEnumValueOptions

// optional string sk_enum_name = 1;
inline bool SharkEnumValueOptions::has_sk_enum_name() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline void SharkEnumValueOptions::clear_sk_enum_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.sk_enum_name_.ClearToEmpty();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const std::string& SharkEnumValueOptions::sk_enum_name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:shark.idl.SharkEnumValueOptions.sk_enum_name)
  return _internal_sk_enum_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void SharkEnumValueOptions::set_sk_enum_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sk_enum_name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:shark.idl.SharkEnumValueOptions.sk_enum_name)
}
inline std::string* SharkEnumValueOptions::mutable_sk_enum_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_sk_enum_name();
  // @@protoc_insertion_point(field_mutable:shark.idl.SharkEnumValueOptions.sk_enum_name)
  return _s;
}
inline const std::string& SharkEnumValueOptions::_internal_sk_enum_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.sk_enum_name_.Get();
}
inline void SharkEnumValueOptions::_internal_set_sk_enum_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  _impl_.sk_enum_name_.Set(value, GetArena());
}
inline std::string* SharkEnumValueOptions::_internal_mutable_sk_enum_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_._has_bits_[0] |= 0x00000001u;
  return _impl_.sk_enum_name_.Mutable( GetArena());
}
inline std::string* SharkEnumValueOptions::release_sk_enum_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:shark.idl.SharkEnumValueOptions.sk_enum_name)
  if ((_impl_._has_bits_[0] & 0x00000001u) == 0) {
    return nullptr;
  }
  _impl_._has_bits_[0] &= ~0x00000001u;
  auto* released = _impl_.sk_enum_name_.Release();
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString()) {
    _impl_.sk_enum_name_.Set("", GetArena());
  }
  return released;
}
inline void SharkEnumValueOptions::set_allocated_sk_enum_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  _impl_.sk_enum_name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.sk_enum_name_.IsDefault()) {
    _impl_.sk_enum_name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:shark.idl.SharkEnumValueOptions.sk_enum_name)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace idl
}  // namespace shark


namespace google {
namespace protobuf {

template <>
struct is_proto_enum<::shark::idl::EnumUnderlyingType> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::EnumUnderlyingType>() {
  return ::shark::idl::EnumUnderlyingType_descriptor();
}
template <>
struct is_proto_enum<::shark::idl::EnumStringSource> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::EnumStringSource>() {
  return ::shark::idl::EnumStringSource_descriptor();
}
template <>
struct is_proto_enum<::shark::idl::CppStand> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::CppStand>() {
  return ::shark::idl::CppStand_descriptor();
}
template <>
struct is_proto_enum<::shark::idl::SharkEdition> : std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor<::shark::idl::SharkEdition>() {
  return ::shark::idl::SharkEdition_descriptor();
}

}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // shark_2fidl_2fshark_5foptions_2eproto_2epb_2eh
