// Copyright (C) Kumo inc. and its affiliates.
// Author: Jeff.li lijippy@163.com
// All rights reserved.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Generated by protoc-gen-kmcc


#include "tests/v1.sk.h"

#include <mutex>



namespace v1::pb {

    const std::string& EchoRequest::Inner::get_in_message() const {
        return _in_message;
    }

    void EchoRequest::Inner::set_in_message(std::string value) {
        _in_message =  std::move(value);
    }

    int64_t EchoRequest::Inner::get_in_cnt() const {
        return _in_cnt.load();
    }

    void EchoRequest::Inner::set_in_cnt(int64_t value) {
        _in_cnt.store(value);
    }

    v1::pb::EchoRequest::Inner EchoRequest::Inner::pb_serialize() const {
        v1::pb::EchoRequest::Inner pb_var;
        pb_var.set_in_message(_in_message);
        pb_var.set_in_cnt(_in_cnt);
        return pb_var;
    }

    turbo::Status EchoRequest::Inner::pb_deserialize(const v1::pb::EchoRequest::Inner &pb_var) {
        _in_message = pb_var.in_message();
        _in_cnt = pb_var.in_cnt();
        return turbo::OkStatus();
    }

    const std::string& EchoRequest::get_message() const {
        return _message;
    }

    void EchoRequest::set_message(std::string value) {
        _message =  std::move(value);
    }

    int64_t EchoRequest::get_cnt() const {
        return _cnt;
    }

    void EchoRequest::set_cnt(int64_t value) {
        _cnt =  std::move(value);
    }

    int8_t EchoRequest::get_total() const {
        std::unique_lock<std::mutex> lk(_total_mutex);
        return _total;
    }

    void EchoRequest::set_total(int8_t value) {
    std::unique_lock<std::mutex> lk(_total_mutex);
        _total =  std::move(value);
    }

    const std::deque<std::string>& EchoRequest::get_names() const {
        return _names;
    }

    std::mutex& EchoRequest::get_names_mutex() {
        return _names_mutex;
    }

    void EchoRequest::names_resize(size_t n) {
        std::unique_lock<std::mutex> lk(_names_mutex);
        _names.resize(n);
    }

    void EchoRequest::names_reserve(size_t n) {
        std::unique_lock<std::mutex> lk(_names_mutex);
        _names.reserve(n);
    }

    void EchoRequest::set_names(size_t index, std::string value) {
        std::unique_lock<std::mutex> lk(_names_mutex);
        _names[index] =  std::move(value);
    }

    void EchoRequest::append_names(std::string value) {
        std::unique_lock<std::mutex> lk(_names_mutex);
        _names.push_back(std::move(value));
    }

    v1::pb::EchoRequest EchoRequest::pb_serialize() const {
        v1::pb::EchoRequest pb_var;
        pb_var.set_message(_message);
        pb_var.set_cnt(_cnt);
        pb_var.set_total(_total);
        auto *mutable_ptr = pb_var.mutable_names();
        mutable_ptr->Reserve(_names.size());
        for(const auto &it : _names) {
            *mutable_ptr->Add() = it;
        }
        return pb_var;
    }

    turbo::Status EchoRequest::pb_deserialize(const v1::pb::EchoRequest &pb_var) {
        _message = pb_var.message();
        _cnt = pb_var.cnt();
        _total = pb_var.total();
        const auto &ref = pb_var.names();
        _names.reserve(pb_var.names_size());
        for(const auto &it : ref) {
            _names.push_back(it);
        }
        return turbo::OkStatus();
    }

    const std::string& EchoResponse::get_message() const {
        return _message;
    }

    void EchoResponse::set_message(std::string value) {
        _message =  std::move(value);
    }

    v1::pb::EchoResponse EchoResponse::pb_serialize() const {
        v1::pb::EchoResponse pb_var;
        pb_var.set_message(_message);
        return pb_var;
    }

    turbo::Status EchoResponse::pb_deserialize(const v1::pb::EchoResponse &pb_var) {
        _message = pb_var.message();
        return turbo::OkStatus();
    }


}  // namespace v1::pb


