// Copyright (C) Kumo inc. and its affiliates.
// Author: Jeff.li lijippy@163.com
// All rights reserved.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

// Generated by protoc-gen-kmcc

#pragma once


#include <utility>

#include "tests/v1.pb.h"
#include <turbo/base/macros.h>
#include <turbo/utility/status.h>
#include <vector>
#include <atomic>
#include <mutex>
#include <deque>

namespace v1::pb {

    class EchoRequest {
    public:
        /// public declares
        class Inner {
        public:
            /// public functions declares
            Inner() = default;

            ~Inner() = default;

            const std::string& get_in_message() const;

            void set_in_message(std::string value);

            int64_t get_in_cnt() const;

            void set_in_cnt(int64_t value);

            

            //////////////////////////////////////////////////////////////////
            /// serialize/deserialize with pb message
            v1::pb::EchoRequest::Inner pb_serialize() const;

            turbo::Status pb_deserialize(const v1::pb::EchoRequest::Inner &pb);

            

            //////////////////////////////////////////////////////////////////
            /// serialize/deserialize with km message, the message design for
            /// zero copy decode and encode, absolutely for simd computing
            std::string serialize() const;

            turbo::Status deserialize(std::string_view array);

        
        private:
            /// private variable declares
            std::string             _in_message{"inner"};
            std::atomic<int64_t>    _in_cnt;
        
        };
        
    
    public:
        /// public functions declares
        EchoRequest() = default;

        ~EchoRequest() = default;

        const std::string& get_message() const;

        void set_message(std::string value);

        int64_t get_cnt() const;

        void set_cnt(int64_t value);

        int8_t get_total() const;

        void set_total(int8_t value);

        const std::deque<std::string>& get_names() const;

        std::mutex& get_names_mutex();

        void names_resize(size_t n);

        void names_reserve(size_t n);

        /// index must be < the field size.
        void set_names(size_t index, std::string value);

        void append_names(std::string value);
        

        //////////////////////////////////////////////////////////////////
        /// serialize/deserialize with pb message
        v1::pb::EchoRequest pb_serialize() const;

        turbo::Status pb_deserialize(const v1::pb::EchoRequest &pb);

        

        //////////////////////////////////////////////////////////////////
        /// serialize/deserialize with km message, the message design for
        /// zero copy decode and encode, absolutely for simd computing
        std::string serialize() const;

        turbo::Status deserialize(std::string_view array);

    
    private:
        /// private variable declares
        std::string                _message{"EchoRequestmsg"};
        int64_t                    _cnt;
        mutable std::mutex         _total_mutex;
        int8_t                     _total{20};
        mutable std::mutex         _names_mutex;
        std::deque<std::string>    _names;
    
    };
    
    class EchoResponse {
    public:
        /// public functions declares
        EchoResponse() = default;

        ~EchoResponse() = default;

        const std::string& get_message() const;

        void set_message(std::string value);

        

        //////////////////////////////////////////////////////////////////
        /// serialize/deserialize with pb message
        v1::pb::EchoResponse pb_serialize() const;

        turbo::Status pb_deserialize(const v1::pb::EchoResponse &pb);

        

        //////////////////////////////////////////////////////////////////
        /// serialize/deserialize with km message, the message design for
        /// zero copy decode and encode, absolutely for simd computing
        std::string serialize() const;

        turbo::Status deserialize(std::string_view array);

    
    private:
        /// private variable declares
        std::string    _message{"EchoResponseMsg"};
    
    };
    

}  // namespace v1::pb


