// Copyright (C) Kumo inc. and its affiliates.
// Author: Jeff.li lijippy@163.com
// All rights reserved.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//

#include <shark/cpp/generator.h>
#include <shark/names.h>
#include <turbo/strings/substitute.h>
#include <turbo/strings/str_format.h>
#include <shark/cpp/message_generator.h>


namespace shark {

    const std::string CppGenerator::kLicense = R"(// Copyright (C) Kumo inc. and its affiliates.
// Author: Jeff.li lijippy@163.com
// All rights reserved.
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as published
// by the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
//
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.
//
)";

    const std::string CppGenerator::kGenWarning = "// Generated by protoc-gen-kmcc\n";

    const std::string CppGenerator::kPragma = "#pragma once\n";
    
    bool CppGenerator::Generate(const google::protobuf::FileDescriptor *file,
                        const std::string &parameter,
                        google::protobuf::compiler::GeneratorContext *generator_context,
                        std::string *error) const {
        if (file->message_type_count() == 0 && file->enum_type_count() == 0) {
            // skip the file.
            return true;
        }

        CodeWriter &writer = CodeWriter::get_instance();
        if (!writer.init(file, generator_context)) {
            return false;
        }

        // Generate code.
        generate_prologue(file, &writer);
        std::unique_ptr<NamespaceBlock> hns = std::make_unique<NamespaceBlock>();
        std::unique_ptr<NamespaceBlock> sns = std::make_unique<NamespaceBlock>();
        hns->name = writer.option().km_namespace();
        sns->name = writer.option().km_namespace();
        for (int i = 0; i != file->message_type_count(); ++i) {
            GenerateCodeFor(&writer.option(), &writer.option().message(i), hns.get(), sns.get());
        }
        std::cerr << "Generated protoc-gen-kmcc code generator." << std::endl;
        writer.add_header_namespace(std::move(hns));
        writer.add_source_namespace(std::move(sns));
        writer.flush();
        return true;
    }


void CppGenerator::generate_prologue(const google::protobuf::FileDescriptor* file,
                                   CodeWriter* writer) const {
    // Headers.
    auto header_incls = turbo::str_format(
      "#include <utility>\n"
      "\n"
      // `.pb.h` comes before Protocol Buffers' header to avoid missing deps.
      "#include \"%s\"\n"
      "\n"
      "\n",
      get_file_prefix(file) + ".pb.h");

    for (auto &it : writer->option().c_includes()) {
        header_incls += turbo::str_format("#include <%s>\n", it);
    }

    auto source_incls =
      turbo::str_format("#include \"%s\"\n", get_file_prefix(file) + ".sk.h") +
      "\n"
      "#include <mutex>\n" +
      "\n";
    writer->add_header_header(std::make_unique<PlainBlockWriter>(kLicense));
    writer->add_header_header(std::make_unique<PlainBlockWriter>(kGenWarning));
    writer->add_header_header(std::make_unique<PlainBlockWriter>(kPragma));
    
    writer->add_header_include(std::make_unique<PlainBlockWriter>(header_incls));

    writer->add_source_header(std::make_unique<PlainBlockWriter>(kLicense));
    writer->add_source_header(std::make_unique<PlainBlockWriter>(kGenWarning));
    writer->add_source_include(std::make_unique<PlainBlockWriter>(source_incls));

    }


void CppGenerator::GenerateCodeFor(
    const KmgenOption* file,
    const MessageOption* service,
    NamespaceBlock* hns, NamespaceBlock* sns) const {
    // Unlike generator V1, we don't have to bother generating class that provides
    // the same interface as `cc_generic_services`.

    MessageGenerator().generate_message(file, service, hns, sns);
}


}  // namespace shark
