/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: examples/example.proto */

#pragma once

#include <cstdint>
#include <string>
#include <optional>
#include <turbo/utility/status.h>

#include <turbo/container/flat_hash_map.h>

#include <xtoml/toml.h>
#include <turbo/container/flat_hash_map.h>



namespace demo::gateway {

    class TlsConfig;
    class RateLimit;
    class Backend;
    class Route;
    class GatewayConfig;



    /// --- enums ---

    /// LogLevel defines the severity of logging.
    enum class LogLevel : uint32_t{
        DEBUG = 0,
        INFO = 1,
        WARN = 2,
        ERROR = 3
    };  // 
    std::optional<LogLevel> parse_LogLevel(std::string_view value);

    /// --- messages --- 


    //////////////////////////////////////////////////////////////////////
    /// TlsConfig 
    /// TlsConfig holds TLS related settings.
    class  TlsConfig {
    public:

    ///  runtime identify for traits
    static constexpr bool is_runtime_type = true;


    public:
        /// TlsConfig holds TLS related settings.
        /// -----enums-------- 
    public:
        ///////////////////////////////////////////////////////////////////////// 
        /// transfers 
        turbo::Status parse_toml_str(const std::string& path);

        turbo::Status parse_toml_file(const std::string& str);

        void add_checker(std::shared_ptr<xtoml::BasicHandler> handler);

        const xtoml::HandlerMap &checkers() const;

        turbo::Status parse_toml(const xtoml::Value& v, const xtoml::TomlUri &prefix, const xtoml::HandlerMap &map);

        xtoml::Value serialize_toml() const;

        turbo::Result<std::string> serialize_to_string() const;

        xtoml::Value serialize_required_toml() const;

        turbo::Result<std::string> serialize_required_to_string() const;


    //////////////////////////////////////////////////////////////////////
    /// members
    /// Keep members protected for inheritance and extension
    public:
        /// Path to certificate file.
        std::string cert_file{""};
        /// Path to private key file.
        std::string key_file{""};
        /// Optional CA certificate for client verification.
        std::string ca_file{""};
        /// Minimum TLS version.
        std::string min_version{"1.2"};

        //////////////////////////////////////////////////////////////////////
        /// global checkers

        xtoml::TomlUri    _uri_prefix;
        xtoml::HandlerMap _handler_map;
    };


    //////////////////////////////////////////////////////////////////////
    /// RateLimit 
    /// RateLimit defines token bucket based rate limiting.
    class  RateLimit {
    public:

    ///  runtime identify for traits
    static constexpr bool is_runtime_type = true;


    public:
        /// RateLimit defines token bucket based rate limiting.
        /// -----enums-------- 
    public:
        ///////////////////////////////////////////////////////////////////////// 
        /// transfers 
        turbo::Status parse_toml_str(const std::string& path);

        turbo::Status parse_toml_file(const std::string& str);

        void add_checker(std::shared_ptr<xtoml::BasicHandler> handler);

        const xtoml::HandlerMap &checkers() const;

        turbo::Status parse_toml(const xtoml::Value& v, const xtoml::TomlUri &prefix, const xtoml::HandlerMap &map);

        xtoml::Value serialize_toml() const;

        turbo::Result<std::string> serialize_to_string() const;

        xtoml::Value serialize_required_toml() const;

        turbo::Result<std::string> serialize_required_to_string() const;


    //////////////////////////////////////////////////////////////////////
    /// members
    /// Keep members protected for inheritance and extension
    public:
        /// Requests per second (steady state).
        int64_t requests_per_sec{0ll};
        /// Maximum burst size.
        int64_t burst{1ll};

        //////////////////////////////////////////////////////////////////////
        /// global checkers

        xtoml::TomlUri    _uri_prefix;
        xtoml::HandlerMap _handler_map;
    };


    //////////////////////////////////////////////////////////////////////
    /// Backend 
    /// Backend describes an upstream service.
    class  Backend {
    public:

    ///  runtime identify for traits
    static constexpr bool is_runtime_type = true;


    public:
        /// Backend describes an upstream service.
        /// -----enums-------- 
    public:
        ///////////////////////////////////////////////////////////////////////// 
        /// transfers 
        turbo::Status parse_toml_str(const std::string& path);

        turbo::Status parse_toml_file(const std::string& str);

        void add_checker(std::shared_ptr<xtoml::BasicHandler> handler);

        const xtoml::HandlerMap &checkers() const;

        turbo::Status parse_toml(const xtoml::Value& v, const xtoml::TomlUri &prefix, const xtoml::HandlerMap &map);

        xtoml::Value serialize_toml() const;

        turbo::Result<std::string> serialize_to_string() const;

        xtoml::Value serialize_required_toml() const;

        turbo::Result<std::string> serialize_required_to_string() const;


    //////////////////////////////////////////////////////////////////////
    /// members
    /// Keep members protected for inheritance and extension
    public:
        /// Unique name for the backend.
        std::string name{""};
        /// Address (host:port or unix socket).
        std::string address{""};
        /// Connection timeout in milliseconds.
        int32_t connect_timeout_ms{1000};
        /// Optional custom headers to inject.
        std::vector<std::string> extra_headers;
        /// Whether this backend is required to be present.
        bool mandatory{0};

        //////////////////////////////////////////////////////////////////////
        /// global checkers

        xtoml::TomlUri    _uri_prefix;
        xtoml::HandlerMap _handler_map;
    };


    //////////////////////////////////////////////////////////////////////
    /// Route 
    /// Routing rule matching a request path.
    class  Route {
    public:

    ///  runtime identify for traits
    static constexpr bool is_runtime_type = true;


    public:
        /// Routing rule matching a request path.
        /// -----enums-------- 
    public:
        ///////////////////////////////////////////////////////////////////////// 
        /// transfers 
        turbo::Status parse_toml_str(const std::string& path);

        turbo::Status parse_toml_file(const std::string& str);

        void add_checker(std::shared_ptr<xtoml::BasicHandler> handler);

        const xtoml::HandlerMap &checkers() const;

        turbo::Status parse_toml(const xtoml::Value& v, const xtoml::TomlUri &prefix, const xtoml::HandlerMap &map);

        xtoml::Value serialize_toml() const;

        turbo::Result<std::string> serialize_to_string() const;

        xtoml::Value serialize_required_toml() const;

        turbo::Result<std::string> serialize_required_to_string() const;


    //////////////////////////////////////////////////////////////////////
    /// members
    /// Keep members protected for inheritance and extension
    public:
        /// Path pattern (e.g., "/api/v1 *").
        std::string pattern{""};
        /// Name of the target backend.
        std::string backend_name{""};
        /// Timeout override in milliseconds.
        int32_t timeout_ms{0};
        /// Enable compression for this route.
        bool enable_compression{1};
        /// Ordered list of allowed methods (GET, POST, ...). Empty = allow all.
        std::vector<std::string> allowed_methods;

        //////////////////////////////////////////////////////////////////////
        /// global checkers

        xtoml::TomlUri    _uri_prefix;
        xtoml::HandlerMap _handler_map;
    };


    //////////////////////////////////////////////////////////////////////
    /// GatewayConfig 
    /// GatewayConfig is the top‑level configuration for the gateway service.
    class  GatewayConfig {
    public:

    ///  runtime identify for traits
    static constexpr bool is_runtime_type = true;


    public:
        /// GatewayConfig is the top‑level configuration for the gateway service.
        /// -----enums-------- 
    public:
        ///////////////////////////////////////////////////////////////////////// 
        /// transfers 
        turbo::Status parse_toml_str(const std::string& path);

        turbo::Status parse_toml_file(const std::string& str);

        void add_checker(std::shared_ptr<xtoml::BasicHandler> handler);

        const xtoml::HandlerMap &checkers() const;

        turbo::Status parse_toml(const xtoml::Value& v, const xtoml::TomlUri &prefix, const xtoml::HandlerMap &map);

        xtoml::Value serialize_toml() const;

        turbo::Result<std::string> serialize_to_string() const;

        xtoml::Value serialize_required_toml() const;

        turbo::Result<std::string> serialize_required_to_string() const;


    //////////////////////////////////////////////////////////////////////
    /// members
    /// Keep members protected for inheritance and extension
    public:
        /// Service name (used for discovery and logging).
        std::string service_name{""};
        /// Port the gateway listens on.
        int32_t listen_port{8080};
        /// Number of worker threads. 0 means auto = CPU cores.
        int32_t worker_threads{0};
        /// Global log level.
        LogLevel log_level{LogLevel::INFO};
        /// Write timeout in seconds.
        int32_t write_timeout_sec{30};
        /// Read timeout in seconds.
        int32_t read_timeout_sec{30};
        /// TLS settings (optional, if absent server runs plain HTTP).
        TlsConfig tls;
        /// Global rate limit (optional, if absent no global limit).
        RateLimit global_rate_limit;
        /// List of available backends.
        std::vector<Backend> backends;
        /// List of routing rules.
        std::vector<Route> routes;
        /// Must have at least one backend (is_required on repeated).
        std::vector<Backend> required_backends;

        //////////////////////////////////////////////////////////////////////
        /// global checkers

        xtoml::TomlUri    _uri_prefix;
        xtoml::HandlerMap _handler_map;
    };


    ///////////////////////////////////////////////////////////
    inline std::string_view to_string(LogLevel value) {
        switch (value) {
          case LogLevel::DEBUG: return "DEBUG";
          case LogLevel::INFO: return "INFO";
          case LogLevel::WARN: return "WARN";
          case LogLevel::ERROR: return "ERROR";
          default: return "UNKNOWN";
        }
    }

}  // demo::gateway


