// SPDX-License-Identifier: BSD-3-Clause
// Based on Google Protobuf (https://github.com/protocolbuffers/protobuf) and protobuf-c
// (https://github.com/protobuf-c/protobuf-c)
// Copyright 2008 Google Inc., 2008-2025 protobuf-c authors. Modifications for C++ generation.
// Copyright (C) 2026 Kumo inc. and its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//


#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>

#include <shark/idl/shark_options.pb.h>

#include <shark/generator/enum.h>
#include <shark/generator/extension.h>
#include <shark/generator/file.h>
#include <shark/generator/helpers.h>
#include <shark/generator/message.h>
#include <shark/generator/service.h>
#include <shark/version.h>
#include <turbo/strings/str_replace.h>
#include <shark/generator/global_state.h>

namespace shark {
    // ===================================================================

    FileGenerator::FileGenerator(const google::protobuf::FileDescriptor *file,
                                 const std::string &dllexport_decl)
        : file_(file),
          message_generators_(
              new std::unique_ptr<MessageGenerator>[file->message_type_count()]),
          enum_generators_(
              new std::unique_ptr<EnumGenerator>[file->enum_type_count()]),
          service_generators_(
              new std::unique_ptr<ServiceGenerator>[file->service_count()]),
          extension_generators_(
              new std::unique_ptr<ExtensionGenerator>[file->extension_count()]) {
        GlobalState::instance().registry(file);

        for (int i = 0; i < file->message_type_count(); i++) {
            message_generators_[i].reset(
                new MessageGenerator(file->message_type(i), dllexport_decl, nullptr));
            if (!_have_one_of) {
                _have_one_of = message_generators_[i]->have_oneof();
            }
        }

        for (int i = 0; i < file->enum_type_count(); i++) {
            enum_generators_[i].reset(
                new EnumGenerator(file->enum_type(i), dllexport_decl));
        }

        for (int i = 0; i < file->service_count(); i++) {
            service_generators_[i].reset(
                new ServiceGenerator(file->service(i), dllexport_decl));
        }

        for (int i = 0; i < file->extension_count(); i++) {
            extension_generators_[i].reset(
                new ExtensionGenerator(file->extension(i), dllexport_decl));
        }
    }

    FileGenerator::~FileGenerator() {
    }

    void FileGenerator::GenerateHeader(google::protobuf::io::Printer *printer) {
        std::string filename_identifier = FilenameIdentifier(file_->name());

        // Generate top of header.
        std::string inc;
        if (!GlobalState::instance().includes.empty()) {
            for (auto &it: GlobalState::instance().includes) {
                inc += it + "\n";
            }
        }
        printer->Print(
            "/* Generated by the protocol buffer compiler.  DO NOT EDIT! */\n"
            "/* Generated from: $filename$ */\n"
            "\n"
            "#pragma once\n"
            "\n"
            "#include <cstdint>\n"
            "#include <string>\n"
            "#include <optional>\n"
            "#include <google/protobuf/descriptor.h>\n"
            "#include <$basename$.pb.h>\n"
            "$INC$"
            "\n"
            "\n",
            "INC", inc,
            "filename", file_->name(),
            "basename", StripProto(file_->name()),
            "filename_identifier", filename_identifier);

        for (int i = 0; i < file_->dependency_count(); i++) {
            if (!GlobalState::instance().ext_file_options.no_generate()) {
                if (turbo::starts_with(file_->dependency(i)->name(), "shark/idl")) {
                    continue;
                }
                if (turbo::starts_with(file_->dependency(i)->name(), "google/protobuf/any")) {
                    continue;
                }
                printer->Print(
                    "#include \"$dependency$.sk.h\"\n",
                    "dependency", StripProto(file_->dependency(i)->name()));
            }
        }

        printer->Print("\n");
        printer->Print("namespace $NS$ {\n\n", "NS", GlobalState::instance().cnamespace);
        printer->Indent();
        // Generate forward declarations of classes.
        for (int i = 0; i < file_->message_type_count(); i++) {
            message_generators_[i]->generate_struct_typedef(printer);
        }

        printer->Print("\n");

        // Generate enum definitions.
        printer->Print("\n/// --- enums ---\n\n");
        for (int i = 0; i < file_->enum_type_count(); i++) {
            enum_generators_[i]->generate_definition(printer);
        }

        // Generate class definitions.
        printer->Print("\n/// --- messages --- \n\n");
        for (int i = 0; i < file_->message_type_count(); i++) {
            message_generators_[i]->generate_struct_definition(printer);
        }

        // Generate service definitions.
        printer->Print("\n/* --- services --- */\n\n");
        for (int i = 0; i < file_->service_count(); i++) {
            service_generators_[i]->GenerateMainHFile(printer);
        }

        // Declare extension identifiers.
        for (int i = 0; i < file_->extension_count(); i++) {
            extension_generators_[i]->GenerateDeclaration(printer);
        }

        printer->Print("\n/* --- descriptors --- */\n\n");
        for (int i = 0; i < file_->enum_type_count(); i++) {
            enum_generators_[i]->generate_inline_definition(printer, nullptr);
        }

        for (int i = 0; i < file_->service_count(); i++) {
            service_generators_[i]->GenerateDescriptorDeclarations(printer);
        }
        printer->Print("\n///////////////////////////////////////////////////////////\n");
        printer->Print("/// --- inlines ---\n");
        //////// inlines
        for (int i = 0; i < file_->message_type_count(); i++) {
            message_generators_[i]->generate_struct_inl(printer);
        }
        printer->Outdent();
        printer->Print(
            "\n"
            "}  // $NS$\n"
            "\n\n",
            "NS", GlobalState::instance().cnamespace,
            "filename_identifier", filename_identifier);
    }

    void FileGenerator::GenerateSource(google::protobuf::io::Printer *printer) {
        printer->Print(
            "/* Generated by the protocol buffer compiler.  DO NOT EDIT! */\n"
            "/* Generated from: $filename$ */\n"
            "\n"
            "/* Do not generate deprecated warnings for self */\n"
            "\n"
            "#include <$basename$.sk.h>\n"
            "#include <google/protobuf/json/json.h>\n\n"
            "namespace $NS$ {\n",
            "filename", file_->name(),
            "NS", GlobalState::instance().cnamespace,
            "basename", StripProto(file_->name()));
        printer->Indent();
        for (int i = 0; i < file_->message_type_count(); i++) {
            message_generators_[i]->generate_struct_transfer(printer);
        }

        for (int i = 0; i < file_->message_type_count(); i++) {
            message_generators_[i]->GenerateMessageDescriptor(printer);
        }
        for (int i = 0; i < file_->enum_type_count(); i++) {
            enum_generators_[i]->GenerateEnumDescriptor(printer);
        }
        for (int i = 0; i < file_->service_count(); i++) {
            service_generators_[i]->GenerateCFile(printer);
        }
        printer->Outdent();
        printer->Print("}  // $NS$\n\n",
                       "NS", GlobalState::instance().cnamespace);
    }
} // namespace shark
