// Copyright (C) 2026 Kumo inc. and its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//



#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>

#include <shark/idl/shark_options.pb.h>

#include <shark/builder/enum.h>
#include <shark/builder/extension.h>
#include <shark/generator/skb_file.h>
#include <shark/utility/helpers.h>
#include <shark/builder/message.h>
#include <shark/view/message.h>
#include <shark/version.h>
#include <turbo/strings/str_replace.h>
#include <shark/generator/global_state.h>

namespace shark {
    // ===================================================================

    FileSkbGenerator::FileSkbGenerator(const google::protobuf::FileDescriptor *file,
                                 const std::string &dllexport_decl)
        : FileGeneratorBase(file) {

        message_generators_.resize(file->message_type_count());
        for (int i = 0; i < file->message_type_count(); i++) {
            message_generators_[i].reset(
                new MessageSkbGenerator(file->message_type(i), dllexport_decl, nullptr));
            if (!_have_one_of) {
                _have_one_of = message_generators_[i]->have_oneof();
            }
        }
        enum_generators_.resize(file->enum_type_count());
        for (int i = 0; i < file->enum_type_count(); i++) {
            enum_generators_[i].reset(
                new EnumSkbGenerator(file->enum_type(i), dllexport_decl));
        }

        extension_generators_.resize(file->extension_count());
        for (int i = 0; i < file->extension_count(); i++) {
            extension_generators_[i].reset(
                new ExtensionSkbGenerator(file->extension(i), dllexport_decl));
        }

        message_view_generators_.resize(file->message_type_count());
        for (int i = 0; i < file->message_type_count(); i++) {
            message_view_generators_[i].reset(
                new MessageViewGenerator(file->message_type(i), dllexport_decl, nullptr));
            if (!_have_one_of) {
                _have_one_of = message_view_generators_[i]->have_oneof();
            }
        }
        enum_view_generators_.resize(file->enum_type_count());
        for (int i = 0; i < file->enum_type_count(); i++) {
            enum_view_generators_[i].reset(
                new EnumViewGenerator(file->enum_type(i), dllexport_decl));
        }


        extension_view_generators_.resize(file->extension_count());
        for (int i = 0; i < file->extension_count(); i++) {
            extension_view_generators_[i].reset(
                new ExtensionViewGenerator(file->extension(i), dllexport_decl));
        }
    }

    FileSkbGenerator::~FileSkbGenerator() {
    }

    void FileSkbGenerator::generate_header(google::protobuf::io::Printer *printer) {
        std::string filename_identifier = FilenameIdentifier(_file->name());

        // Generate top of header.
        std::string inc;
        if (!GlobalState::instance().includes.empty()) {
            for (auto &it: GlobalState::instance().includes) {
                inc += it + "\n";
            }
        }
        printer->Print(
            "/* Generated by the protocol buffer compiler.  DO NOT EDIT! */\n"
            "/* Generated from: $filename$ */\n"
            "\n"
            "#pragma once\n"
            "\n"
            "#include <cstdint>\n"
            "#include <string>\n"
            "#include <optional>\n"
            "#include <google/protobuf/descriptor.h>\n"
            "#include <$basename$.pb.h>\n"
            "#include <$basename$.sk.h>\n"
            "#include <shark/shark.h>\n"
            "$INC$"
            "\n"
            "\n",
            "INC", inc,
            "filename", _file->name(),
            "basename", StripProto(_file->name()),
            "filename_identifier", filename_identifier);

        for (int i = 0; i < _file->dependency_count(); i++) {
            if (!GlobalState::instance().ext_file_options.no_generate()) {
                if (turbo::starts_with(_file->dependency(i)->name(), "shark/idl")) {
                    continue;
                }
                if (turbo::starts_with(_file->dependency(i)->name(), "google/protobuf/any")) {
                    continue;
                }
                printer->Print(
                    "#include \"$dependency$.sk.h\"\n",
                    "dependency", StripProto(_file->dependency(i)->name()));
            }
        }

        printer->Print("\n");
        printer->Print("namespace $NS$ {\n\n", "NS", GlobalState::instance().cnamespace);
        printer->Indent();
        // Generate forward declarations of classes.
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_generators_[i]->generate_struct_typedef(printer);
        }
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_view_generators_[i]->generate_struct_typedef(printer);
        }

        printer->Print("\n");

        // Generate enum definitions.
        printer->Print("\n/// --- enums ---\n\n");
        for (int i = 0; i < _file->enum_type_count(); i++) {
            enum_generators_[i]->generate_definition(printer, nullptr);
        }

        for (int i = 0; i < _file->enum_type_count(); i++) {
            enum_view_generators_[i]->generate_definition(printer, nullptr);
        }

        // Generate class definitions.
        printer->Print("\n//////////////////////////////////////////////////////////////////////////\n");
        printer->Print("/// --- builders --- \n\n");
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_generators_[i]->generate_struct_definition(printer);
        }
        printer->Print("\n//////////////////////////////////////////////////////////////////////////\n");
        printer->Print("/// --- views ---\n\n");
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_view_generators_[i]->generate_struct_definition(printer);
        }


        // Declare extension identifiers.
        for (int i = 0; i < _file->extension_count(); i++) {
            extension_generators_[i]->GenerateDeclaration(printer);
        }
        for (int i = 0; i < _file->extension_count(); i++) {
            extension_view_generators_[i]->GenerateDeclaration(printer);
        }

        printer->Print("\n/* --- descriptors --- */\n\n");
        for (int i = 0; i < _file->enum_type_count(); i++) {
            enum_generators_[i]->generate_inline_definition(printer, nullptr);
        }


        printer->Print("\n///////////////////////////////////////////////////////////\n");
        printer->Print("/// --- inlines ---\n");
        //////// inlines
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_generators_[i]->generate_struct_inl(printer);
        }
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_view_generators_[i]->generate_struct_inl(printer);
        }
        printer->Outdent();
        printer->Print(
            "\n"
            "}  // $NS$\n"
            "\n\n",
            "NS", GlobalState::instance().cnamespace,
            "filename_identifier", filename_identifier);
    }

    void FileSkbGenerator::generate_source(google::protobuf::io::Printer *printer) {
        printer->Print(
            "/* Generated by the protocol buffer compiler.  DO NOT EDIT! */\n"
            "/* Generated from: $filename$ */\n"
            "\n"
            "/* Do not generate deprecated warnings for self */\n"
            "\n"
            "#include <$basename$.sk.h>\n"
            "#include <$basename$.skb.h>\n"
            "#include <google/protobuf/json/json.h>\n\n"
            "namespace $NS$ {\n",
            "filename", _file->name(),
            "NS", GlobalState::instance().cnamespace,
            "basename", StripProto(_file->name()));
        printer->Indent();
        /*
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_generators_[i]->generate_struct_transfer(printer);
        }*/
        for (int i = 0; i < _file->message_type_count(); i++) {
            message_view_generators_[i]->generate_struct_transfer(printer);
        }

        for (int i = 0; i < _file->message_type_count(); i++) {
            message_generators_[i]->GenerateMessageDescriptor(printer);
        }


        printer->Outdent();
        printer->Print("}  // $NS$\n\n",
                       "NS", GlobalState::instance().cnamespace);
    }
} // namespace shark
