// Copyright (C) 2026 Kumo inc. and its affiliates. All Rights Reserved.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//


#include <google/protobuf/descriptor.h>
#include <google/protobuf/io/printer.h>

#include <shark/idl/shark_options.pb.h>

#include <shark/tml/enum.h>
#include <shark/tml/extension.h>
#include <shark/generator/tml_file.h>
#include <shark/utility/helpers.h>
#include <shark/tml/message.h>
#include <shark/tml/service.h>
#include <shark/version.h>
#include <turbo/strings/str_replace.h>
#include <shark/generator/global_state.h>

namespace shark {
    // ===================================================================

    FileRtGenerator::FileRtGenerator(const google::protobuf::FileDescriptor *file,
                                     const std::string &dllexport_decl)
        : FileGeneratorBase(file) {
        _rt_file = std::make_unique<RtFileGenerator>(file, dllexport_decl);

    }

    FileRtGenerator::~FileRtGenerator() {
    }

    void FileRtGenerator::generate_header(google::protobuf::io::Printer *printer) {
        std::string filename_identifier = FilenameIdentifier(_file->name());
        // Generate top of header.
        std::string inc;
        if (!GlobalState::instance().includes.empty()) {
            for (auto &it: GlobalState::instance().includes) {
                inc += it + "\n";
            }
        }

        _rt_file->generate_preprocessor_before_include(printer);

        printer->Print(
            "/* Generated by the protocol buffer compiler.  DO NOT EDIT! */\n"
            "/* Generated from: $filename$ */\n"
            "\n"
            "#pragma once\n"
            "\n"
            "#include <cstdint>\n"
            "#include <string>\n"
            "#include <optional>\n"
            "#include <turbo/utility/status.h>\n\n"
            "#include <turbo/container/flat_hash_map.h>\n\n"
            "#include <xtoml/toml.h>\n"
            "$INC$"
            "\n"
            "\n",
            "INC", inc,
            "filename", _file->name(),
            "basename", StripProto(_file->name()),
            "filename_identifier", filename_identifier);

        for (int i = 0; i < _file->dependency_count(); i++) {
            if (!GlobalState::instance().ext_file_options.no_generate()) {
                if (turbo::starts_with(_file->dependency(i)->name(), "shark/idl")) {
                    continue;
                }
                if (turbo::starts_with(_file->dependency(i)->name(), "google/protobuf/any")) {
                    continue;
                }
                printer->Print(
                    "#include <$dependency$.tml.h>\n",
                    "dependency", StripProto(_file->dependency(i)->name()));
            }
        }

        _rt_file->generate_header_include(printer);

        _rt_file->generate_preprocessor_after_include(printer);

        printer->Print("\n");
        printer->Print("namespace $NS$ {\n\n", "NS", GlobalState::instance().cnamespace);
        printer->Indent();
        // Generate forward declarations of classes.

        _rt_file->generate_fwd_typedef(printer);
        printer->Print("\n");


        _rt_file->generate_definition(printer);


        _rt_file->generate_inline_implement(printer);


        printer->Outdent();
        printer->Print(
            "\n"
            "}  // $NS$\n"
            "\n\n",
            "NS", GlobalState::instance().cnamespace,
            "filename_identifier", filename_identifier);
        _rt_file->generate_preprocessor_end(printer);

    }

    void FileRtGenerator::generate_source(google::protobuf::io::Printer *printer) {

        printer->Print(
            "/* Generated by the protocol buffer compiler.  DO NOT EDIT! */\n"
            "/* Generated from: $filename$ */\n"
            "\n"
            "/* Do not generate deprecated warnings for self */\n"
            "\n"
            "#include <$basename$.tml.h>\n\n"
            "#include <turbo/log/logging.h>\n\n",
            "filename", _file->name(),
            "basename", StripProto(_file->name()));

        _rt_file->generate_source_include(printer);

        printer->Print("\n\n");

        printer->Print(
            "namespace $NS$ {\n",
            "NS", GlobalState::instance().cnamespace);

        printer->Indent();

        _rt_file->generate_static_variable(printer);


        _rt_file->generate_static_functions(printer);


        _rt_file->generate_implement(printer);


        printer->Outdent();
        printer->Print("}  // $NS$\n\n",
                       "NS", GlobalState::instance().cnamespace);

    }
} // namespace shark
